### ISSUE TITLE
Remove n_estimators as a parameter from the random forest operator and other ensemble methods

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#119]
There's really no point to optimizing the number of estimators in ensemble models: Basically, the more estimators they're provided, the better they perform. Let's remove `n_estimators` as an optimizable parameter for all ensemble models and instead default it to, say, 100 or 500 estimators.

**Comment by rhiever** [comment]
The RF operator has had its n_estimators parameter removed, and it now defaults to 500 for n_estimators. The remaining ensemble operators still need to be reworked.

**Comment by minimumnz** [comment]
Increasing the estimators will increase performance, but I would think when you're trying a lot of different parameters it will increase the time for all those decision trees to run, and whether it wouldn't be better to increase n_estimators later. I guess if they don't perform well enough in the first instance they're not going to make it into the next generation. Really just curious on your thoughts.

**Comment by rhiever** [comment]
I suppose the default could be n_estimators=100 and it should still work fine. I just want to make sure that RFs and other ensemble methods don't get skipped over simply because they didn't have enough estimators.
