### ISSUE TITLE
Examples: provide an example based a real dataset

### ISSUE THREAD

**Issue by loretoparisi** [rhiever/tpot#125]
I'm trying to figure out a real-world example with `tpot` to learn how it works, step by step.

So, I will take [this](http://stackoverflow.com/questions/36535239/natural-language-processing-of-topics/36538038#36538038) dataset as example, that looks like

```json
{
    "laughter-good-conversation-friendships": {
        "category": "socializing",
        "category_id": 31,
        "score": 2.5,
        "topic_id": 27166
    },
    "live-theatre": {
        "category": "socializing",
        "category_id": 31,
        "score": 2.5,
        "topic_id": 23274
    },
    "nightlife": {
        "category": "socializing",
        "category_id": 31,
        "score": 2.5,
        "topic_id": 4392
    },
    "wine-tasting": {
        "category": "socializing",
        "category_id": 31,
        "score": 2.5,
        "topic_id": 15139
    },
    "women": {
        "category": "socializing",
        "category_id": 31,
        "score": 2.5,
        "topic_id": 10232
    },
    "business-entrepreneur-networking": {
        "category": "career-business",
        "category_id": 2,
        "score": 0,
        "topic_id": 20060
    },
    "business-referral-networking": {
        "category": "career-business",
        "category_id": 2,
        "score": 0,
        "topic_id": 15405
    },
    "christian": {
        "category": "career-business",
        "category_id": 2,
        "score": 0,
        "topic_id": 17963
    },
    "financial-chaos-to-financial-freedom": {
        "category": "career-business",
        "category_id": 2,
        "score": 0,
        "topic_id": 79053
    },
    "insprofs": {
        "category": "career-business",
        "category_id": 2,
        "score": 0,
        "topic_id": 10042
    },
    "professional-networking": {
        "category": "career-business",
        "category_id": 2,
        "score": 0,
        "topic_id": 15720
    },
    "real-estate-investors": {
        "category": "career-business",
        "category_id": 2,
        "score": 0,
        "topic_id": 16165
    },
    "retirement": {
        "category": "career-business",
        "category_id": 2,
        "score": 0,
        "topic_id": 6364
    },
    "socialnetwork": {
        "category": "career-business",
        "category_id": 2,
        "score": 0,
        "topic_id": 4422
    }
}
```

each item in this json is a topic like `socialnetwork`  that belongs to a category like `career-business`. More topics may belong to the same category, like `wine-tasting` and `nightlife` belongs to `socializing`, son in a 1 to N relationship.
Now, the are some topics that may affer to the same topic like here:

```json
"dragons": {
        "category": "lifestyle",
        "category_id": 17,
        "score": 0.279108277990115,
        "topic_id": 2137
    },
    "furry-fandom": {
        "category": "lifestyle",
        "category_id": 17,
        "score": 0.279108277990115,
        "topic_id": 48595
    },
    "legendarycreatures": {
        "category": "lifestyle",
        "category_id": 17,
        "score": 0.279108277990115,
        "topic_id": 10523
    }
```

Topics like `dragons` and `legendarycreatures` could be considered part of a new topic like `fantasy`.
So, assumed that `tpot` can analyze dataset automatically, how to describe this dataset in order that our `objective function` is to collect / aggregate topics in new topics, so new categories that are not defined in this dataset?

**Comment by rhiever** [comment]
Currently, TPOT only supports supervised classification tasks. Is what you're describing a supervised classification task, i.e., do you have a set of features with labels that you're attempted to model?

**Comment by loretoparisi** [comment]
Ok thanks. Let's suppose that I have manually tagged features (i.e. in this case topics), so labelled them in order to belong to a most generic topic (new one) so let's say we have a test set with a initial classification in N categories/topics.

**Comment by rhiever** [comment]
What features would the algorithm have to classify the topic with?

**Comment by loretoparisi** [comment]
So, since I have no description of a `topic` then the `label`, I thought to set as metrics word2vec features vector for each `label`, so I have the distances basically.

**Comment by rhiever** [comment]
Gotcha. If you can feed TPOT features such as those distances (or even the vector values from word2vec) and provide it labels for those features, then it can try to optimize a pipeline that maximizes classification accuracy for that data set.

**Comment by loretoparisi** [comment]
@rhiever ok, which is the input data format, let's say a typical row I would have from the `word2vec` vector for a label is the array of floating point numbers, do this work?

**Comment by rhiever** [comment]
Check these example notebooks:

* https://github.com/rhiever/tpot/blob/master/tutorials/IRIS.ipynb

* https://github.com/rhiever/tpot/blob/master/tutorials/MNIST.ipynb

* https://github.com/rhiever/tpot/blob/master/tutorials/Titanic_Kaggle.ipynb

TPOT requires the "standard" supervised data set format. Check this tutorial to see what that entails: https://github.com/amueller/scipy_2015_sklearn_tutorial/blob/master/notebooks/01.3%20Data%20Representation%20for%20Machine%20Learning.ipynb
