### ISSUE TITLE
Revisit evolvable parameters for existing classifier operators

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#129]
Here are some parameters that we should consider adding to the existing classifier operators.

SVC is currently removed from TPOT, and we may remove it entirely because it requires too much parameter tuning to perform well.

# DecisionTreeClassifier

http://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html

Existing evolvable parameters: max_features, max_depth

New evolvable parameters: criterion

# RandomForestClassifier

http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

Existing evolvable parameters: max_features

New evolvable parameters: criterion

# LogisticRegression

http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

Existing evolvable parameters: C

New evolvable parameters: fit_intercept, dual, penalty

# SVC

http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html

Existing evolvable parameters: C

New evolvable parameters: kernel, gamma, coef0

# KNeighborsClassifier

http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

Existing evolvable parameters: n_neighbors

New evolvable parameters: none

**Comment by rhiever** [comment]
@teaearlgraycold, forget this issue for now. I will have an updated version of it in a separate issue soon.

**Comment by teaearlgraycold** [comment]
Alright. I had not started work on it yet so that's fine.
