### ISSUE TITLE
Add features based on counts of zero's, na's, etc.

### ISSUE THREAD

**Issue by KobaKhit** [rhiever/tpot#133]
Randal once mentioned that the structure of a data set was captured by the number of missing values. Similarly, in [this kaggle](https://www.kaggle.com/c/santander-customer-satisfaction) competition count of zero's per row turned out to be an important feature. I think it is worth having a function that adds the count of zeros per row and the count of non-zero values per row in case these features happen to be important.

**Comment by rhiever** [comment]
Sounds good to me! I have marked it as being worked on.

**Comment by teaearlgraycold** [comment]
Currently working on this.

**Comment by rhiever** [comment]
I think @KobaKhit is working on this issue. Can you please confirm @KobaKhit?

**Comment by teaearlgraycold** [comment]
Oh, my bad. Well if not I've pretty much finished it

**Comment by rhiever** [comment]
Well, send in the PR once it's finished and we'll compare with what @KobaKhit has. :-)

**Comment by KobaKhit** [comment]
Sorry for late reply. Thats fine. Looking forward to your pr.

**Comment by teaearlgraycold** [comment]
Threw it into my existing PR for new preprocessors
