### ISSUE TITLE
Assume no knowledge of parameters

### ISSUE THREAD

**Issue by salamanders** [rhiever/tpot#136]
After reading the (very good) [intro documentation](http://rhiever.github.io/tpot/using/), it isn't clear to the first-time user which parameters I need to read up on and make an educated guess, and which I can leave with the default.

For example: -mr  

* Should I set it?  
* Is the default set to a good value?
* If the default works most of the time, when should I set it?

I'd love it if the "interesting" settings like (GENERATIONS,  POPULATION_SIZE, MUTATION_RATE, CROSSOVER_RATE) were documented something like this.  (I'm totally making up the specifics, but you get the idea)

"-gp GP mutation rate in the range [0.0, 1.0]  Default of 0.72, **which will work in the vast majority of cases.**  It is worth trying one run with this set to .3 and your initial POPULATION_SIZE increased 10x which will run longer but not get caught in local minima"

**Comment by rhiever** [comment]
Good idea. Most of the defaults are ideal according to a benchmark we did a while back, and we regularly re-benchmark TPOT to re-evaluate these defaults. The main parameter that you might change is `generations`, depending on whether you need to give TPOT more or less time to optimize the pipeline.

Perhaps an extra section -- something like a "Field Guide for TPOT" -- would be useful. Either way, 👍 to this suggestion.

**Comment by salamanders** [comment]
My vote is put exactly what you said here into the help output, and avoid a Field Guide until absolutely necessary.  I really like the idea of "I can run this out of the box, and it will start with sane defaults, and I know this because it tells me so, and I don't feel like I need to go read up on stuff first"

**Comment by rhiever** [comment]
All done. This update be in the next release.

**Comment by salamanders** [comment]
Yay!  In the meantime is there a way to install from github to see the results of this?

**Comment by rhiever** [comment]
Yes. You can download this repo and run `python setup.py install` in the base directory (make sure to `pip uninstall tpot` first), although we haven't done full QA on v0.4 yet. If you run into any bugs, please file them. :-)

**Comment by rhiever** [comment]
Yes. If you download this repo and run `python setup.py install` in the base directory (make sure to `pip uninstall tpot` first, you'll have access to the current dev state of TPOT 0.4. No guarantees that it it's bug-free yet, though. :-)
