### ISSUE TITLE
TPOT module for Orange Data Mining?

### ISSUE THREAD

**Issue by brylie** [rhiever/tpot#137]
The [Orange Data Mining](http://orange.biolab.si) project makes machine learning accessible to people without extensive programming skills. It would be really cool to see a TPOT module somehow integrated into Orange, so that people could use TPOT through an elegant UI. What are your thoughts regarding the possibility to create a TPOT UI, such as in Orange Data Mining?

**Comment by teaearlgraycold** [comment]
There is #51 already in consideration. Not *exactly* what you're requesting, though.

**Comment by rhiever** [comment]
A GUI is in the long-term plans. In the meantime, #51 (as @teaearlgraycold mentioned) is very similar to what you seek.

**Comment by brylie** [comment]
@teaearlgraycold thanks! Very similar indeed.
