### ISSUE TITLE
cross_val_score does not work

### ISSUE THREAD

**Issue by VedAustin** [rhiever/tpot#142]
## Attempting to run cross_val_score

TypeError: Cannot clone object '<tpot.tpot.TPOT object at 0x0000000006A8C390>' (type <class 'tpot.tpot.TPOT'>): it does not seem to be a scikit-learn estimator as it does not implement a 'get_params' methods.

## Process to reproduce the issue
`X_train, X_test, y_train, y_test = train_test_split(X_data, y_data,train_size=0.95, test_size=0.05)`
`tpot = TPOT(generations=2)`
`tpot.fit(X_train, y_train)`
`np.mean(cross_val_score(tpot,X_data,y_data,cv=10,scoring='accuracy'))`

**Comment by rhiever** [comment]
Confirmed. We need to implement `get_params` as the other sklearn models do.

**Comment by rhiever** [comment]
@teaearlgraycold is working on a `get_params` function for TPOT.

**Comment by VedAustin** [comment]
Awesome. Thank you!

**Comment by VedAustin** [comment]
Accidentely closed this issue.

**Comment by rhiever** [comment]
This feature is now implemented and will be included in the TPOT v0.4 release.
