### ISSUE TITLE
libxgboostwrapper.so: invalid elf header

### ISSUE THREAD

**Issue by nbernini** [rhiever/tpot#150]
[provide general introduction to the issue and why it is relevant to this repository]

## Context of the issue

[provide more detailed introduction to the issue itself and why it is relevant]

[the remaining entries are only necessary if you are reporting a bug]

## Process to reproduce the issue

[ordered list the process to finding and recreating the issue, example below]

1. User creates TPOT instance
2. User calls TPOT `fit()` function with training data
3. TPOT crashes with a `KeyError` after 5 generations

## Expected result

[describe what you would expect to have resulted from this process]

## Current result

[describe what you currently experience from this process, and thereby explain the bug]

## Possible fix

[not necessary, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by nbernini** [comment]
using python3.5 on Ubuntu.
getting the following error during import

# Code
from tpot import TPOT

# Error
/home/ubuntu/anaconda2/lib/python2.7/site-packages/xgboost-0.4a30-py2.7.egg/xgboost/./wrapper/libxgboostwrapper.so: invalid elf header

**Comment by rhiever** [comment]
Looks like an XGBoost install issue. Check out this page and see if it can address your issue: https://github.com/dmlc/xgboost/blob/master/python-package/build_trouble_shooting.md

**Comment by rhiever** [comment]
We've removed XGBoost from the upcoming release of TPOT.
