### ISSUE TITLE
Make XGBoost an optional dependency

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#154]
Due to several users having install issues with XGBoost, we have decided to make XGBoost an optional dependency. Currently, XGBoost is not supported by TPOT. If you would like to implement XGBoost as an optional model in TPOT, please make suggestions here.

**Comment by KhaoticMind** [comment]
I'll try to implement it and send a PR when I get it done.

This will be my first contribution to TPOT (and one of the few in general) so be patient ;)

**Comment by rhiever** [comment]
Sounds good! Thanks @KhaoticMind. :-)

**Comment by rhiever** [comment]
How's this coming along, @KhaoticMind? Need any feedback?

**Comment by KhaoticMind** [comment]
Hello @rhiever. The last couple of weeks I'm having a lot of work at Day Job (where I can do most of my contribution). I hope to get something  done by next week or so.

In the mean time, If there is any one else interested on it, please don't be shy to jump in :) (But I'm still committed to it!).

**Comment by rhiever** [comment]
No problem! We'll slate it for a later release than the one coming up this
week.

On Monday, June 20, 2016, Antonio Augusto Santos <notifications@github.com>
wrote:

> Hello @rhiever <https://github.com/rhiever>. The last couple of weeks I'm
> having a lot of work at Day Job (where I can do most of my contribution). I
> hope to get something done by next week or so.
>
> In the mean time, If there is any one else interested on it, please don't
> be shy to jump in :) (But I'm still committed to it!).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/rhiever/tpot/issues/154#issuecomment-227115420>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABo7tzdR1AR3-wssVNI12chSNJ_zyALSks5qNnbigaJpZM4Ikwbk>
> .
>


-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by KhaoticMind** [comment]
@rhiever Found some time, and already sent a pull request. Please be free to point any issues (as I said, my first big PR ;) .)
