### ISSUE TITLE
TPOT has different behavior when seeding the random library due to PRNG changes in Python 3.2

### ISSUE THREAD

**Issue by teaearlgraycold** [rhiever/tpot#159]
## Context of the issue

While writing unit tests that depend on seeded TPOT instances I learned that the tests would all fail under a Python 2.7 installation because the seeds behaved differently with the older PRNG algorithm.

## Possible fix

Assuming Sklearn and DEAP use numpy's random, all we need to do is eliminate instances of std. lib random from TPOT and replace them with numpy's RNG.

**Comment by rhiever** [comment]
Damn, looks like DEAP uses base Python's random: https://github.com/DEAP/deap/blob/af334219c168ed6c30403c587064a03f39d7d12a/deap/tools/mutation.py#L40

**Comment by rhiever** [comment]
but we should still fix this.

**Comment by rhiever** [comment]
From what I can tell, sklearn solely uses the numpy RNG. Good news there. I filed an issue on the DEAP repo suggesting that they switch over to the numpy RNG.
