### ISSUE TITLE
Implement command-line call for TPOT

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#16]
Currently, the only way to call TPOT is to point Python to the `tpot.py` file, which obviously isn't useful for people who installed TPOT via e.g. `pip`. Make the `pip` installer create an entry point for the command line.

See https://github.com/rhiever/reddit-analysis/blob/master/setup.py#L41 for an example.

**Comment by rasbt** [comment]
May I ask why you chose this design decision over a regular module? Just an idea, but I'd consider changing it to a standard package/module layout and provide "example scripts" and or the command line interfaces extra, which import for the package. What do you think? This way it's much more flexible and you can make different flavors of command line executable scripts. (I am doing this for one of my projects as well, the "large scale virtual screening" one. For example, I would have all the base classes and function as a module, and then I have command line scripts such as "parse database", "overlay molecules" etc.

**Comment by rhiever** [comment]
Check the README. It supports both. ;-)

**Comment by rasbt** [comment]
Ahh, you updated it! Nice, and never-mind.
