### ISSUE TITLE
Remove mathematical operators from the TPOT primitives

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#162]
Currently, TPOT has mathematical primitives (add, subtract, multiply, divide) that act on integers and floats to decide the parameters of various models and feature preprocessors. I suspect that the mathematical primitives have been causing several issues in TPOT:

1) **They cause bloat.** Since the mathematical operators don't count against the pipeline size (which is part of the Pareto fitness), GP tends to add tons of mathematical operators to the pipelines. This in turn causes most of the mutation and crossover events to affect the mathematical operators rather than exploring different pipeline operators in the pipeline. (The latter has yet to be experimentally verified, but is probable.)

2) **They produce extreme values.** Many of the model parameters in TPOT are capped in a certain range. Thus, the mathematical operators will tend to produce values that are at the extremes of those caps, which is probably not ideal.

With these issues in mind, I propose that we remove the mathematical operators and have a fixed set of integer and float terminals that TPOT uses. We will need to choose these terminals wisely, as (if we make this change) TPOT will not be able to produce arbitrary terminals any more.

**Comment by rhiever** [comment]
Considerations for `float` terminals:

* We will need good coverage in the range `[0., 1.]`, as many models and preprocessors use values in that range to specify percentages

* We will need good coverage in the much lower ranges (<= 0.01), as many models with the `C` and `learning_rate` parameters require lower float values

* We will need moderate coverage in the higher ranges (>=1), as some models benefit from e.g. higher `C` values. It's still unclear to us what specific values are useful here.

* SelectFwe uses `float`s in the range `[0.001, 0.05]`

* VarianceThreshold, Binarizer, RBFSampler, & Nystroem use `float`s in an unknown range


Considerations for `int` terminals:

* We use `int`s to encode multi-choice model parameters (e.g., options A, B, or C), so we need good coverage between 1-10

* The KNeighborsClassifier uses `int`s for its `n_neighbors` parameter, but `n_neighbors` doesn't seem to be useful beyond 25

* RFE & SelectKBest use `int`s to specify the number of features to select

* RandomizedPCA, RBF, FastICA, FeatureAgglomeration, & Nystroem use `int`s to specify the number of components

So we need to decide on terminal sets that account for all these use cases without creating a huge search space.

**Comment by rhiever** [comment]
So perhaps a good `float` terminal set would be:

```
[0.0001, 0.001, 0.01] + np.arange(0.05, 1., 0.05) + np.arange(1, 50, 1)
```

and a good `int` terminal set would be:

```
np.arange(0, 51, 1)
```

Am I missing any use cases here? @amueller, thoughts?

**Comment by amueller** [comment]
Do you mean "list of possible parameters to choose from"?

Btw ``np.arange(1., 101.) / 100. == np.linspace(0.01, 1.00, 100)`` which might be more readable.

I often use C=100, which is currently not covered.
Some parameters can be floats or integers, like ``max_features`` and ``min_samples_split`` in trees. How do you deal with that?

if you use integers for ``max_features`` and ``min_samples_split`` the first scales with the number of features and the second (maybe?) with the number of samples. I guess that's a good argument to use floats there? Otherwise you'd need to expand your range. Do you search n_estimators on trees still?

I'm not sure where you use integers and where you use floats, so I can't tell you if the ranges are good.
If you're searching over ``tol``, ``0.0001`` might be a bit big. In general maybe just also add 1e-5 and 1-e6 to the floats.

**Comment by rhiever** [comment]
>Do you mean "list of possible parameters to choose from"?

Yep!

>Btw `np.arange(1., 101.) / 100. == np.linspace(0.01, 1.00, 100)` which might be more readable.

The main difference is that `np.linspace` produces imprecise floats, e.g., it represents 0.05 as 0.049999999999. Obviously not a huge deal for most use cases, but I don't want to be outputting 0.049999999999 in the exported code when it should be 0.05. (Stupid floating point precision issues.)

>I often use C=100, which is currently not covered.

We can add coarse coverage beyond 50 (e.g., 60, 70, 80, 90, 100) in the float terminal set.

>Some parameters can be floats or integers, like max_features and min_samples_split in trees. How do you deal with that?

The GP trees are strongly typed, so we pre-select a type for each parameter. So yes, we tend to favor floats when choosing the type because they tend to represent fractions rather than counts.

>I'm not sure where you use integers and where you use floats, so I can't tell you if the ranges are good.
If you're searching over tol, 0.0001 might be a bit big. In general maybe just also add 1e-5 and 1-e6 to the floats.

#161 includes many of the parameters and types that we will be optimizing. https://github.com/rhiever/tpot/issues/162#issuecomment-223482183 is a pretty exhaustive list of our use cases, I believe.

**Comment by amueller** [comment]
> Obviously not a huge deal for most use cases, but I don't want to be outputting 0.049999999999 in the exported code when it should be 0.05. (Stupid floating point precision issues.)
How about limiting the precision?

**Comment by rhiever** [comment]
e.g. `[round(x, 2) for x in np.linspace(0.01, 1.00, 100).tolist()]`?

Just remembered that the issue only rises when I convert the numpy array to a list.

**Comment by amueller** [comment]
``n_components`` scales with the number of features (kind of). For ``RBFSampler``, it could be hundreds or thousands even if the dimensionality of the original data is small.

**Comment by amueller** [comment]
no I meant when printing!

**Comment by rhiever** [comment]
Okay, I updated https://github.com/rhiever/tpot/issues/162#issuecomment-223483641 with a more "numpythonic" way of creating the list. :-P

**Comment by rhiever** [comment]
>``n_components`` scales with the number of features (kind of).

Typically people use PCA etc. to compress the features, right? Is it useful to use PCA and maintain the same feature space?

We *could* just remove `n_components` as an evolvable parameter and always use the default, which in most cases equals the original number of features.

>For ``RBFSampler``, it could be hundreds or thousands even if the dimensionality of the original data is small.

Is it typical to create hundreds/thousands of features from a `RBFSampler`?

**Comment by amueller** [comment]
> Is it typical to create hundreds/thousands of features from a RBFSampler?
yes. I wouldn't go below hundreds.

> Typically people use PCA etc. to compress the features, right? Is it useful to use PCA and maintain the same feature space?
Depends. But with "scales with" I meant "is on the order of". So if you want half as many components as you had features, it might be a large number.

**Comment by rhiever** [comment]
That's fair. Can you think of anything wrong with simply removing `n_components` as an evolvable feature and using the defaults? Worst case, "just" has extra not-so-useful features that can be pruned by feature selection, yeah?

**Comment by amueller** [comment]
Not really. That's only true for PCA. For all other methods, changing ``n_components`` changes all components. And for NMF for example, it is not limited by the number of features in the original set.

**Comment by rhiever** [comment]
👍 Will raise a new issue for that then.

Otherwise, do you think the terminal (parameter) set in https://github.com/rhiever/tpot/issues/162#issuecomment-223483641 looks good, considering the use cases?

**Comment by amueller** [comment]
I'd add 1e-4, 1e-5, 1e-6 but otherwise looks good.
