### ISSUE TITLE
Documentation - example with csv file

### ISSUE THREAD

**Issue by mglowacki100** [rhiever/tpot#166]
It is a trivial issue, but for people on entry level there should be example in documentation how to load data from csv file (e.g. iris.csv). In such way, it'd be easy for completly newcomers.

**Comment by rhiever** [comment]
Hi @mglowacki100! We have an example notebook [here](https://github.com/rhiever/tpot/blob/master/tutorials/Titanic_Kaggle.ipynb) (linked in the [docs](http://rhiever.github.io/tpot/)) showing how to do that. But do you mean putting such an example in the README?

**Comment by mglowacki100** [comment]
Sorry, didn't notice it. It should be closed.
