### ISSUE TITLE
reference error in export pipeline

### ISSUE THREAD

**Issue by RoelantStegmann** [rhiever/tpot#167]
Found a small bug where the learning rate is referenced before assigning. 

## Context of the issue

The error occurred when exporting the TPOT pipeline, and is listed below. I have not been able to reproduce it (I guess due to the random nature of TPOTs generations?). 

  File "tpot/tpot.py", line 439, in export
    pipeline_text += replace_function_calls(pipeline_list)
  File "tpot/export_utils.py", line 446, in replace_function_calls
    learning_rate = max(learning_rate, 0.0001)
UnboundLocalError: local variable 'learning_rate' referenced before assignment

**Comment by rhiever** [comment]
Confirmed. Looks like the same is true for all GradientBoostingClassifier export code: https://github.com/rhiever/tpot/blob/master/tpot/export_utils.py#L445

Let's make sure this doesn't happen in any of the export code.

Adding this bugfix request to the 0.4 release.
