### ISSUE TITLE
Possible error in final model selection

### ISSUE THREAD

**Issue by robotijn** [rhiever/tpot#172]
I am running many experiments with tpot but I sometimes get the impression that the final model is not the best one. Take this run for example:

-------------------------------------------------------------------------

amount of generations:	 20 
amount of population:	 100
gen	nevals	Minimum score	Average score	Maximum score
0  	100   	0.5          	0.578771     	0.793401     
1  	90    	0.5          	0.72187      	0.812255     
2  	89    	0.5          	0.744521     	0.898665     
3  	89    	0.5          	0.759533     	0.898665     
4  	89    	0.258445     	0.762023     	0.868814     
5  	92    	0.5          	0.769804     	0.868814     
6  	94    	0.5          	0.788303     	0.906127     
7  	93    	0.5          	0.769297     	0.906127     
8  	87    	0.5          	0.77425      	0.906127     
9  	86    	0.5          	0.766893     	0.812255     
10 	94    	0.5          	0.772907     	0.812255     
11 	92    	0.5          	0.786905     	0.812255     
12 	91    	0.5          	0.788555     	0.835035     
13 	93    	0.5          	0.770169     	0.835035     
14 	87    	0.5          	0.762196     	0.835035     
15 	89    	0.5          	0.762262     	0.835035     
16 	92    	0.5          	0.7676       	0.827573     
17 	92    	0.5          	0.789081     	0.827573     
18 	92    	0.5          	0.772694     	0.812255     
19 	90    	0.5          	0.788225     	0.812255     
20 	94    	0.5          	0.771284     	0.812255     

Best pipeline: _max_abs_scaler(_knnc(_binarizer(ARG0, 0.0001), 61))
0.5

-------------------------------------------------------------------------

I find it difficult to believe that 0.5 is the best outcome on the hold out data set when the best score in this run is 0.906 in the 6th generation.

Also the maximum fitness goes down quite often, probably due to the selection method that is used in the DEAP part. For a user this is rather awkward and should either be explained, or an elitist approach should be used.

**Comment by rhiever** [comment]
What version of TPOT are you using that still has SVM in it? I believe we
dropped SVM because it has a tendency to overfit just like you're
experiencing.


On Monday, June 20, 2016, robotijn <notifications@github.com> wrote:

> I am running many experiments with tpot but I sometimes get the impression
> that the final model is not the best one. Take this run for example:
>
> amount of generations: 20
> amount of population: 100
> gen nevals Minimum score Average score Maximum score
> 0 100 0.5 0.578771 0.793401
>
> 1 90 0.5 0.72187 0.812255
>
> 2 89 0.5 0.744521 0.898665
>
> 3 89 0.5 0.759533 0.898665
>
> 4 89 0.258445 0.762023 0.868814
>
> 5 92 0.5 0.769804 0.868814
>
> 6 94 0.5 0.788303 0.906127
>
> 7 93 0.5 0.769297 0.906127
>
> 8 87 0.5 0.77425 0.906127
>
> 9 86 0.5 0.766893 0.812255
>
> 10 94 0.5 0.772907 0.812255
>
> 11 92 0.5 0.786905 0.812255
>
> 12 91 0.5 0.788555 0.835035
>
> 13 93 0.5 0.770169 0.835035
>
> 14 87 0.5 0.762196 0.835035
>
> 15 89 0.5 0.762262 0.835035
>
> 16 92 0.5 0.7676 0.827573
>
> 17 92 0.5 0.789081 0.827573
>
> 18 92 0.5 0.772694 0.812255
>
> 19 90 0.5 0.788225 0.812255
>
> 20 94 0.5 0.771284 0.812255
>
> Best pipeline: _max_abs_scaler(_knnc(_binarizer(ARG0, 0.0001), 61))
> 0.5
>
> I find it difficult to believe that 0.5 is the best outcome on the hold
> out data set when the best score in this run is 0.906
>
> Also the maximum fitness goes down quite often, probably due to the
> selection method that is used in the DEAP part. For a user this is rather
> awkward and should either be explained, or an elitist approach should be
> used.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rhiever/tpot/issues/172>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABo7t3or3WyxH-vXuWjShv-tmTM6-vapks5qNqGBgaJpZM4I5vuL>
> .
>


-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by robotijn** [comment]
In [4]: tpot.__version__
Out[4]: '0.3.0'

I installed it using pip

**Comment by rhiever** [comment]
👍 Let us know how it goes. If you still have issues, please share your data set (if possible) and I'll try to find out what's going on.

**Comment by robotijn** [comment]
0.4.0 works pretty good except for the model saving, this is giving an error sometimes (I posted the error). I can't share my data set, unfortunately...

**Comment by rhiever** [comment]
Good to hear. We refined TPOT's optimization process pretty significantly
in 0.4. Hopefully you won't have major overfitting issues now.

On Tuesday, June 21, 2016, robotijn <notifications@github.com> wrote:

> 0.4.0 works pretty good except for the model saving, this is giving an
> error sometimes (I posted the error). I can't share my data set,
> unfortunately...
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/rhiever/tpot/issues/172#issuecomment-227431277>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABo7t1YogFIyZscaDJet0CkArWsPzj-_ks5qN9_QgaJpZM4I5vuL>
> .
>


-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by ankitshah009** [comment]
@robotijn - 
In the 0.4.0 version of tpot, were you able to solve the model saving error?
Also - please share whether just by changing the version from 0.3 to 0.4 solved the overfitting issue or were there some more modifications done locally to the tpot code?
