### ISSUE TITLE
Index error on operator

### ISSUE THREAD

**Issue by robotijn** [rhiever/tpot#179]
When saving the outcome of a run to a file I got the following error:

IndexError                                Traceback (most recent call last)
<ipython-input-52-9b28c13fc5d3> in <module>()
      2     for gens in [i*20 for i in range(1, 10)]:
      3         for popsize in [i*50 for i in range(1,20)]:
----> 4             runTpot(gens, popsize)

<ipython-input-50-f3cd95feb8b1> in runTpot(gens, popsize)
      5     score = my_tpot.score(X_test, y_test)
      6     print(score)
----> 7     my_tpot.export('exported_pipeline_score_' + str(score) + '_popsize_' + str(popsize) + '_gens_' + str(gens) + '.py')

/home/deep/anaconda3/envs/ml/lib/python3.5/site-packages/TPOT-0.4-py3.5.egg/tpot/tpot.py in export(self, output_file_name)
    478 
    479         # Replace the function calls with their corresponding Python code. Check export_utils.py for details.
--> 480         pipeline_text += replace_function_calls(pipeline_list)
    481 
    482         with open(output_file_name, 'w') as output_file:

/home/deep/anaconda3/envs/ml/lib/python3.5/site-packages/TPOT-0.4-py3.5.egg/tpot/export_utils.py in replace_function_calls(pipeline_list)
    386             learning_rate = min(1., max(float(operator[3]), 0.0001))
    387             max_features = min(1., max(0., float(operator[4])))
--> 388             min_weight = min(0.5, max(0., float(operator[6])))
    389 
    390             if result_name != operator[2]:

IndexError: list index out of range

**Comment by rhiever** [comment]
@teaearlgraycold, can you please look into this? We should thoroughly test all of the operators for exporting before the 0.4 release.

**Comment by teaearlgraycold** [comment]
Got it
