### ISSUE TITLE
Nystroem operator: UserWarning: n_components > n_samples. This is not possible.

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#182]
When `n_components` is larger than the training set size in the `Nystroem` operator, TPOT throws a warning:

>UserWarning: n_components > n_samples. This is not possible.

I assume this only happens with smaller data sets. Regardless, let's make sure that `n_components` is always <= the training set size in TPOT so this warning is not thrown.

We can ignore that case in the exported code for now.

**Comment by rhiever** [comment]
cc @teaearlgraycold

**Comment by KhaoticMind** [comment]
The idea is to thrown an exception on TPOT when `fit` is called with data in this condition?
Or to make it so that `Nystroem` doesn't make part of the population when this is the case?

**Comment by rhiever** [comment]
It's mostly to make sure that it doesn't throw the error while running, so we cap the parameter value when running Nystroem.

**Comment by teaearlgraycold** [comment]
Just to threshold the parameter value under these conditions so the sklearn
classifier isn't so noisy
