### ISSUE TITLE
Set up Travis-CI to automatically rebuild the docs when a commit is merged on master

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#185]
No reason this needs to be done manually. We just need to get Travis-CI to run:

```
mkdocs build --clean
mkdocs gh-deploy
```

**Comment by teaearlgraycold** [comment]
Can Travis push to a branch?

**Comment by rhiever** [comment]
I believe so. I've seen other repos, e.g. sklearn, do this.

**Comment by teaearlgraycold** [comment]
[This](https://github.com/conda/conda-docs/blob/master/update-gh-pages.sh) seems like a good starting point.

**Comment by westurner** [comment]
cookiecutter-pypackage defines a ``[docs]`` tox env:
- https://github.com/audreyr/cookiecutter-pypackage/blob/master/tox.ini

conda-docs now calls doctr to deploy from Travis-CI to GitHub Pages:
- https://github.com/conda/conda-docs/blob/master/.travis.yml
  - https://pypi.python.org/pypi/doctr (Python >= 3.5)

- [ ] Add tox.ini
  - https://tox.readthedocs.io/en/latest/
  - https://tox.readthedocs.io/en/latest/config.html
  - https://tox.readthedocs.io/en/latest/examples.html
  - [ ] Port https://github.com/rhiever/tpot/blob/master/ci/.travis_install.sh to tox
  - [ ] Port https://github.com/rhiever/tpot/blob/master/ci/.travis_test.sh to tox
- [ ] Update .travis.yml to call tox and then doctr
  - https://github.com/audreyr/cookiecutter-pypackage/blob/master/.travis.yml

**Comment by westurner** [comment]
- https://github.com/rhiever/tpot/blob/master/docs/mkdocs.yml
  - https://github.com/mkdocs/mkdocs/

- mkdocs has a ReadTheDocs theme:
  - https://github.com/rhiever/tpot/blob/master/docs/mkdocs.yml
  - https://github.com/snide/sphinx_rtd_theme
  - http://www.mkdocs.org/user-guide/styling-your-docs/#readthedocs

- ReadTheDocs now also supports Markdown, but IDK about mkdocs:
 - ``sphinx-quickstart`` (scikit-learn, statsmodels, ...)
 - http://blog.readthedocs.com/adding-markdown-support/
   - CommonMark w/ recommonmark
     - http://spec.commonmark.org/
 - http://read-the-docs.readthedocs.io/en/latest/getting_started.html#in-markdown

**Comment by westurner** [comment]
> sphinx-quickstart (scikit-learn, statsmodels, ...)

- pandoc is written in haskell!

**Comment by mfeurer** [comment]
To the best of my knowledge they're using circle-ci to build the documentation. You can also find a simple example in the repository [scikit-learn-contrib](https://github.com/scikit-learn-contrib/project-template).
