### ISSUE TITLE
Regression with TPOT?

### ISSUE THREAD

**Issue by dbikard** [rhiever/tpot#186]
This might be more of a feature request, but I'm wondering if it's possible to use TPOT to perform a regression task instead of a classification task. Maybe this is already possible and I'm missing something? Could someone point me in the right direction?

Thanks for your help.
David

**Comment by rhiever** [comment]
TPOT doesn't currently support regression, but we have plans to do so in the near future once we have the basic algorithm worked out in the supervised classification case.

**Comment by rhiever** [comment]
@teaearlgraycold / @tonyfast, it should be pretty easy to swap out the classifiers for regressors, the scoring function with MSE, and have TPOT work the same otherwise, yes? Am I missing anything? Maybe we should prioritize this addition.

**Comment by tonyfast** [comment]
This should be a constraint in the [refactor](https://github.com/rhiever/tpot/issues/91).  

[`ClassifierMixins`](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/base.py#L301) and [`RegessorMixins`](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/base.py#L330) define their own scoring functions.  I have been experimenting in this [notebook](https://github.com/tonyfast/tpot/blob/refactor/Untitled163.ipynb).

**Comment by rhiever** [comment]
Hi @dbikard, we just released TPOT v0.6 today with regression support. Try upgrading TPOT via pip and using it on your regression data set. Usage docs: [link](http://rhiever.github.io/tpot/using/)

**Comment by dbikard** [comment]
Awesome! Thanks.
