### ISSUE TITLE
Explicitly define API types

### ISSUE THREAD

**Issue by rlnsanz** [rhiever/tpot#189]
TPOT dependencies, such as scikit-learn, implicitly define types in their API. For example, an SVM kernel can be any string in the following set: {"linear", "polynomial", "rbf", "sigmoid"}.

These types should be made explicit with DEAP, to improve readability and take full advantage of GP.

```python
class Kernel(object): pass

self._pset.addTerminal("linear", Kernel)
self._pset.addTerminal("polynomial", Kernel)
self._pset.addTerminal("rbf", Kernel)
self._pset.addTerminal("sigmoid", Kernel)

self._pset.addPrimitive(self._rfe, [pd.DataFrame, int, float, Kernel], pd.DataFrame)
```

**Comment by teaearlgraycold** [comment]
Sounds cool to me

**Comment by rhiever** [comment]
👍 This is a better way to represent categorical parameters than integers.

**Comment by rhiever** [comment]
This issue is now encapsulated in #206, so I'm going to close this issue.
