### ISSUE TITLE
TPOT.export function is unable to dump the optimised pipeline

### ISSUE THREAD

**Issue by ankitshah009** [rhiever/tpot#190]
This is in relation to TPOT release version 0.4 

TPOT generated output pipeline - has no information on classifier. 
The behavior is seen when feature selection is done with SelectPercentile classifier and another classifier model fitted training set.
The below is a sample TPOT generated pipeline where the classifier information is missing.
 
=====================================================================
import numpy as np
import pandas as pd

from sklearn.cross_validation import train_test_split
from sklearn.feature_selection import SelectPercentile, f_classif

'# NOTE: Make sure that the class is labeled 'class' in the data file
tpot_data = pd.read_csv('PATH/TO/DATA/FILE', sep='COLUMN_SEPARATOR')
training_indices, testing_indices = train_test_split(tpot_data.index, stratify = tpot_data['class'].values, train_size=0.75, test_size=0.25)

result1 = tpot_data.copy()

'#Use Scikit-learn's SelectPercentile for feature selection
training_features = result1.loc[training_indices].drop('class', axis=1)
training_class_vals = result1.loc[training_indices, 'class'].values

if len(training_features.columns.values) == 0:
    result1 = result1.copy()
else:
    selector = SelectPercentile(f_classif, percentile=40)
    selector.fit(training_features.values, training_class_vals)
    mask = selector.get_support(True)
    mask_cols = list(training_features.iloc[:, mask].columns) + ['class']
    result1 = result1[mask_cols]

=====================================================================

On debugging further with adding prints in export_utils.py found the following 

**Best pipeline: _extra_trees(_select_percentile(input_df, 40), 32, 0.62, 0.45000000000000001)**
0.696427835936
node_params
[<deap.gp.Terminal object at 0x7f3372a7a140>, <deap.gp.Terminal object at 0x7f3372a8f320>]
new_val is
result1
operator_list
**['result1', '_select_percentile']**
pipeline_list
**[['result1', '_select_percentile', 'ARG0', '40']]**
node_params
[<deap.gp.Terminal object at 0x7f33717998c0>, <deap.gp.Terminal object at 0x7f3372a8f0a0>, <deap.gp.Terminal object at 0x7f3372a91e10>, <deap.gp.Terminal object at 0x7f3372a918c0>]
new_val is
result2
operator_list
**['result2', '_extra_trees']**
pipeline_list
[['result1', '_select_percentile', 'ARG0', '40'], ['result2', '_extra_trees', 'result1', '32', '0.62', '0.45']]
linesdasdf node_index
0
line40 - node
<deap.gp.Terminal object at 0x7f3371799500>
pipeline_list[0] - ankit
**['result1', '_select_percentile', 'ARG0', '40']**
x is
result1
x is
**_select_percentile**

Carefully observing the bold parts we see for result2 also result1 object is being picked causing extra_trees not being picked and thus the incomplete pipeline dump.

**Comment by rhiever** [comment]
Can you please add more detail to your issue? Do you have a stack trace of the error? Is the error repeatable?

**Comment by ankitshah009** [comment]
Yes - Please give me 30 mins of time to put up more details on the issue.
As currently using test train split function - the error is repeatable however depends on the split data as well.

**Comment by ankitshah009** [comment]
The issue is updated now. Please review the same. 
In export_utils.py, we are using pipeline_list[0] to generate the pipeline list as return value from function def unroll_nested_fuction_calls

Thus select_pipeline is being called twice.

**Comment by rhiever** [comment]
cc @teaearlgraycold

**Comment by teaearlgraycold** [comment]
@ankitshah009 so is there a stack trace?

**Comment by ankitshah009** [comment]
@ teaearlgraycold currently dont have a stack trace for the issue.

**Comment by teaearlgraycold** [comment]
Alright, I'll look into this

**Comment by ankitshah009** [comment]
Please find the attached code essential to replicate the issue. 
1. generate_tpot_model.py - Used to generate the tpot generated pipeline
Command to use: - python generate_tpot_model.py fold1_train.txt 0.75 15 | tee tpot_run15.log

2. The above command would create a file similar to tpot_pipeline_fold1_train_15.py

We see here that in sample file tpot_pipeline_fold1_train_15.py the classifier output is not generated. Generally this is seen when is selecting best features is done before running classifier in the output tpot generated pipeline.  
Please let me know if further details are needed. 

[fold1_train.txt](https://github.com/rhiever/tpot/files/342037/fold1_train.txt)

**Comment by ankitshah009** [comment]
@teaearlgraycold 
Awaiting an update on this issue. Let me know if further information is needed. 
Thanks 
Ankit Shah

**Comment by teaearlgraycold** [comment]
@ankitshah009 I've solved the problem. The fix should be released in a bugfix version of 0.4 soon.

**Comment by ankitshah009** [comment]
@teaearlgraycold Thank you for addressing this problem and providing a quick resolution for the same.

**Comment by ankitshah009** [comment]
The above fix for #191  is not working fine. 
@teaearlgraycold - Is this the only fix done to the code in tpot/export_utils.py? Are there no changes done to the main tpot.py script?

Receiving these errors : - 
pipeline_list
[['result1', '_feat_agg', 'ARG0', '36', '13', '5'], ['result2', '_passive_aggressive', 'result1', '0.08', '11']]
File "generate_tpot_model.py", line 89, in 
runTpot(train_file, test_file, gen_num)
File "generate_tpot_model.py", line 80, in runTpot
tpot.export(name)
File "/usr/local/lib/python2.7/dist-packages/tpot/tpot.py", line 480, in export
pipeline_text += replace_function_calls(pipeline_list)
File "/usr/local/lib/python2.7/dist-packages/tpot/export_utils.py", line 191, in replace_function_calls
operator_num = int(operator[0].strip('result'))
ValueError: invalid literal for int() with base 10: ' '

**Comment by ankitshah009** [comment]
sudo pip install --upgrade tpot 
Installs the 0.4.1 version of the release - which solves the issue. 
Thank you.
