### ISSUE TITLE
A resulting pipeline appears to be a stacking, but its not build as such

### ISSUE THREAD

**Issue by KhaoticMind** [rhiever/tpot#192]
While running some tests for XGBoost on tpot, it output the bellow pipeline (I had only xgboost as a primitive):

``` python
import numpy as np
import pandas as pd

from sklearn.cross_validation import train_test_split
from xgboost import XGBClassifier

# NOTE: Make sure that the class is labeled 'class' in the data file
tpot_data = pd.read_csv('PATH/TO/DATA/FILE', sep='COLUMN_SEPARATOR')
training_indices, testing_indices = train_test_split(tpot_data.index, stratify = tpot_data['class'].values, train_size=0.75, test_size=0.25)

result1 = tpot_data.copy()

# Perform classification with a extreme gradient boosting classifier
xgbc1 = XGBClassifier(learning_rate=1.0, subsample=1.0, min_child_weight=1410, max_depth=100, n_estimators=740)
xgbc1.fit(result1.loc[training_indices].drop('class', axis=1).values, result1.loc[training_indices, 'class'].values)

result1['xgbc1-classification'] = xgbc1.predict(result1.drop('class', axis=1).values)

result2 = result1.copy()
# Perform classification with a extreme gradient boosting classifier
xgbc2 = XGBClassifier(learning_rate=0.31, subsample=0.42, min_child_weight=1, max_depth=100, n_estimators=780)
xgbc2.fit(result2.loc[training_indices].drop('class', axis=1).values, result2.loc[training_indices, 'class'].values)

result2['xgbc2-classification'] = xgbc2.predict(result2.drop('class', axis=1).values)
```

In this case xgbc2 is using the output of xgbc1 as a feature. For what I know this is a "stacking" of classifiers but, for the little I know, it is being done on the wrongly, since it can introduce some information leak on the results.

For what I've heard, the "correct" way to do stacking is to build the the first predictions on split subsets of the train data, as can be seen here http://www.kdnuggets.com/2016/02/ensemble-methods-techniques-produce-improved-machine-learning.html (Section "Stacking Multiple Machine Learning Models").

So, IMHO, pipelining classifiers like this is wrong approach.

Maybe there is a way that we can prevent classifiers from being pipelined?

PS.: Hope I made myself clear...

**Comment by rhiever** [comment]
Yes, this is also known as creating "synthetic features" -- basically using the output of one model as a feature for another model.

The code you show appears to be creating synthetic features correctly. It trains the first classifier on only the training data, then stores the predictions on all of the data as the synthetic feature. The same training subset is then used to train the second classifier, which then makes the final classification on the full data set.

**Comment by KhaoticMind** [comment]
Sorry, now you have enlightened me!
Althou I knew that the new features where being used WITH the original ones, I was under the impression that this was stacking, when it really was not.
