### ISSUE TITLE
Detect and handle missing values

### ISSUE THREAD

**Issue by rlnsanz** [rhiever/tpot#194]
We should support datasets with missing values. Scikit-learn already offers [a useful option](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.Imputer.html) for completing missing values. We can use strong typing to force DEAP to use an Imputer first, and we can automatically find a suitable value for the `strategy` hyper-parameter with program evolution.

```python
class Imputed_DF(object): pass
class Strategy(object): pass        #Strategy in {"mean", "median", "most_frequent"}
...
self._pset = gp.PrimitiveSetTyped('MAIN', [pd.DataFrame], Output_DF)
self._pset.addPrimitive(self._imputer, [pd.DataFrame, Strategy], Imputed_DF)
self._pset.addPrimitive(self._operator, [Imputed_DF, ...], Output_DF)

```

**Comment by rhiever** [comment]
This issue is now encapsulated in #206, so I'm going to close this issue.
