### ISSUE TITLE
Ensure Access to Model Parameters upon Early Termination

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#2]
From @rasbt:

Let's make sure that we don't lose the model parameters if the run is terminated early.

- Add a "verbose" parameter that writes to stderr. This way, the user can pipe the output (e.g., model parameters and metrics) to a log file. This is especially useful to keep track of the process if you are running TPOT as a PBS job, and it ensures that you have access to the model parameters when the job crashes (or hits the wall time)

- Also, make sure that the current state is saved gracefully if the program quits unexpectedly.

**Comment by MichaelMarkieta** [comment]
Keep in mind the usability of the temp output and what might be possible.... no big deal if its just a log of the current state of the model upon exit, but if you wanted to use that log as some sort parameterized object for specifying a new model run based on the last attempt, or (in some blue-sky thinking way), using the temp output from the previous model to train the new model to skip certain generations....

**Comment by rasbt** [comment]
@MichaelMarkieta I agree with you; maybe we should start with a simple log file to get it going, and we can later come up with a "parameter file" to directly initialize and parameterize the model as I mentioned above.
