### ISSUE TITLE
Add `--science` option to TPOT

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#200]
The progress bar is nice for regular TPOT users, but for me it's useful to have the stats on min/mean/max fitness etc. that we had in TPOT 0.3 and earlier. We should add a `--science` option to TPOT that replaces the progress bar with the old stats.

This would need to work in both the command-line and sklearn-compatible version of TPOT.

cc @teaearlgraycold

**Comment by teaearlgraycold** [comment]
That seems reasonable to me
