### ISSUE TITLE
data got 4 classes but error report The minimum number of labels for any class cannot be less than 2.

### ISSUE THREAD

**Issue by sherlockhoatszx** [rhiever/tpot#203]
## Context of the issue

I got a sentiment analysis data to set models for sentiment predict. the data contains 2 columns: text and label . the label means the sentiment. Roughly it got 4 classes : non-strong-emotions  happy angry and sad and they were reprinted by 0 1 2 3 . the dataset is a imbalanced class. the dataset total got 266 thousands lines . the non-strong -emotion got 150 thousands lines and the happy 44 thousands lines . the angry got 45 thousands lines and the sad got nearly 20 thousands lines .

after covectorize the data and count the tf-idf  i try to use TPOT like this : 

    
    X_train, X_test, y_train, y_test = train_test_split(train_data_features , train_data.label, train_size=0.75, test_size=0.25)
    
    tpot = TPOT(generations=5)
    tpot.fit(X_train, y_train)
    print(tpot.score(X_test, y_test))
    tpot.export('tpot_senti_pipeline2.py')

## Process to reproduce the issue
  
  befor: clean the data  word countvectorize and count the tf-idf data  then try to use TPOT as below:  
    X_train, X_test, y_train, y_test = train_test_split(train_data_features , train_data.label, train_size=0.75, test_size=0.25)
    
    tpot = TPOT(generations=5)
    tpot.fit(X_train, y_train)
    print(tpot.score(X_test, y_test))
    tpot.export('tpot_senti_pipeline2.py')

## Expected result

before using TPOT i have tried naive bayes and random forest . they both work well 
## Current result

Traceback (most recent call last):
  File "top_sentiAnaly.py", line 121, in <module>
    drawfeature(train_data_path,train_file_name,test_data_path,test_file_name)
  File "top_sentiAnaly.py", line 111, in drawfeature
    tpot.fit(X_train, y_train)
  File "/Applications/anaconda/lib/python2.7/site-packages/tpot/tpot.py", line 261, in fit
    test_size=0.25)
  File "/Applications/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py", line 1910, in train_test_split
    random_state=random_state)
  File "/Applications/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py", line 962, in __init__
    raise ValueError("The least populated class in y has only 1"
ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of labels for any class cannot be less than 2.
## Possible fix
i doubt it was caused by the imbalanced dataset . so I try to split the data in another way: straitifiedKFoldA

   skf = StratifiedKFold(train_data.label, n_folds=2)
    for train_index, test_index in skf:
        X_train, X_test = train_data_features[train_index], train_data_features[test_index]
        y_train, y_test = train_data.label[train_index],train_data.label[test_index]

but it still report error:Traceback (most recent call last):
  File "top_sentiAnaly.py", line 127, in <module>
    drawfeature(train_data_path,train_file_name,test_data_path,test_file_name)
  File "top_sentiAnaly.py", line 117, in drawfeature
    tpot.fit(X_train, y_train)
  File "/Applications/anaconda/lib/python2.7/site-packages/tpot/tpot.py", line 261, in fit
    test_size=0.25)
  File "/Applications/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py", line 1910, in train_test_split
    random_state=random_state)
  File "/Applications/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py", line 962, in __init__
    raise ValueError("The least populated class in y has only 1"
ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of labels for any class cannot be less than 2.

![screenshot](https://cloud.githubusercontent.com/assets/14892920/17376513/7f42681a-59e8-11e6-85fd-554e723bcfde.png)
![screen_shot2](https://cloud.githubusercontent.com/assets/14892920/17376984/7af9ae4c-59ea-11e6-9a72-5fa300d251cc.png)

**Comment by rhiever** [comment]
This looks like an issue with sklearn's `train_test_split` and related functionality. What do you get when you look at the unique values in `y_train`, e.g., `print(set(y_train))`?

**Comment by sherlockhoatszx** [comment]
input: print(set(y_train))

output:  set([0, 1, 2, 3])

**Comment by sherlockhoatszx** [comment]
y_train 's dtype is int64 while the the X_train is float ,a sparse represent . is that ok ?

**Comment by sherlockhoatszx** [comment]
should i change the column name 'label' to 'class'?

**Comment by rhiever** [comment]
If you're using the sklearn interface, the name of the columns shouldn't matter (since they're dropped once in numpy matrix format). Currently, we don't support sparse matrices, which may be the source of the issue. What happens if you try the same call and change your array to a dense matrix? (via `.toarray()`)

**Comment by sherlockhoatszx** [comment]
My train data has already been toarray  before feeding in.but they are word's tf-idf value .so the dense matrix have many zero value..

发自我的 iPhone

**Comment by rhiever** [comment]
One more thought I had: I noticed in the screenshot you posted, `y_train` is a pandas Series. Make sure to convert everything to numpy arrays of matrices (e.g. `y_train.values`) before passing it to TPOT or any sklearn object.

**Comment by sherlockhoatszx** [comment]
Yes using y_train.values in the TPOT that could work .many thanks for your help !

发自我的 iPhone

**Comment by rhiever** [comment]
Great! Let us know how TPOT works for you. 👍
