### ISSUE TITLE
Refine TPOT's pipeline grammar

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#206]
DELFT uses a relatively sophisticated [pipeline grammar](https://github.com/EpistasisLab/delft/blob/c924d61c885b13b4a82d86148e0b1fabd03a9cb0/delft/delft.py#L316) to restrict the forms that pipelines can take. For example:

1) An imputer must be the first step in the pipeline (see #194)

2) A scaler must be the second step in the pipeline

3) Only classifiers can be the final step in the pipeline

4) DELFT also has special terminal types for each parameter, such that it never, e.g., uses integers to encode string parameters (see #189)

Even if we keep the rest of the pipeline grammar relatively open for GP to tinker with, we should integrate all of these restrictions into TPOT's grammar.

**Comment by rhiever** [comment]
@teaearlgraycold, how much of this have we already integrated into the dev branch?

**Comment by teaearlgraycold** [comment]
So far -

- [ ] An imputer must be the first step in the pipeline (see #194)

- [ ] A scaler must be the second step in the pipeline

- [X] Only classifiers can be the final step in the pipeline

- [ ] special terminal types for each parameter, such that it never, e.g., uses integers to encode string parameters (see #189)

**Comment by rhiever** [comment]
Great. We'll focus on this once the refactor is rolled out.

**Comment by rhiever** [comment]
@teaearlgraycold, for 0.6 we're only implementing `3)` and `4)`, right?
