### ISSUE TITLE
Bug report: Crash during pipeline export 

### ISSUE THREAD

**Issue by campbx** [rhiever/tpot#210]
Thank you for an awesome library!  I have been putting it through its paces, and have been able to make it crash during pipeline export phase due to a type-casting error.  

## Process to reproduce the issue
`tpot.export('tpot_birth_pipeline.py')`

## Expected result
tpot_birth_pipeline.py

## Current result
```
TypeErrorTraceback (most recent call last)
<ipython-input-12-4fc922ef3696> in <module>()
----> 1 tpot.export('tpot_birth_pipeline.py')

/opt/conda/lib/python3.5/site-packages/tpot/tpot.py in export(self, output_file_name)
    478 
    479         # Replace the function calls with their corresponding Python code. Check export_utils.py for details.
--> 480         pipeline_text += replace_function_calls(pipeline_list)
    481 
    482         with open(output_file_name, 'w') as output_file:

/opt/conda/lib/python3.5/site-packages/tpot/export_utils.py in replace_function_calls(pipeline_list)
    206 
    207         elif operator_name == '_random_forest':
--> 208             min_weight = min(0.5, max(0., operator[3]))
    209 
    210             operator_text += '\n# Perform classification with a random forest classifier'

TypeError: unorderable types: str() > float()
```

## Possible fix
Looks like a type-casting error.

**Comment by rhiever** [comment]
Thank you @campbx! @teaearlgraycold, I think this will be handled in the 0.5 release, right?

**Comment by teaearlgraycold** [comment]
Yes.

0.5 should be out this week so honestly I'd recommend just waiting for the official 0.5 release.

**Comment by rhiever** [comment]
👍 Will close this issue them. @campbx, please re-open the issue if it persists in the 0.5 release later this week.
