### ISSUE TITLE
Guidance: Adding more algorithms to building blocks

### ISSUE THREAD

**Issue by FuriouslyCurious** [rhiever/tpot#211]
## Context of the issue

Hi Randy, I can chip in some code and add more algorithm "building blocks" to TPOT.  For example, I can add t-SNE which performs better than PCA.  

What is a good place to start with this?  Any code-traditions that you would like me to follow?

**Comment by rhiever** [comment]
Will definitely appreciate any and all code contributions! Adding t-SNE as an alternative to PCA sounds very interesting. Our latest dev version is on the `development` branch, so I'd start (and PR to) there. Here's the contribution guidelines: [link](http://rhiever.github.io/tpot/contributing/)

Basically, adding t-SNE would entail adding the operator to TPOT itself, adding unit tests, and adding an entry to the documentation.

**Comment by rhiever** [comment]
Hi, just wanted to check in on this. Do you plan to add t-SNE? We can slot it for the 0.7 release in a couple weeks.

**Comment by slcott** [comment]
I have a little experience with T-SNE. I think T-SNE was primarily created as a visualization tool and it wasn't designed to be an alternative to PCA, for example like ICA is.

**Comment by rhiever** [comment]
That's been my experience with t-SNE as well. @campbx, have you seen t-SNE used for non-visualization purposes?

**Comment by QueenB** [comment]
Not to hijack the thread, but i wanted to add AdaBoostClassifier into the model, what changes would be required to make in the code? besides the adding the classifier into the code.

**Comment by rhiever** [comment]
@QueenB, you would:

* Add the AdaBoostClassifier.py file in [this directory](https://github.com/rhiever/tpot/tree/master/tpot/operators/classifiers)

* Add the `import` statement to [this file](https://github.com/rhiever/tpot/blob/master/tpot/operators/classifiers/__init__.py)

And that's it. Note that we're working on a refactor of this interface to make it much easier to customize what algorithms and parameters TPOT optimizes over.
