### ISSUE TITLE
Add new feature selection operator based on ExtraTrees feature importances

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#212]
Use [SelectFromModel](http://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectFromModel.html) to select features based on [ExtraTrees](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.ExtraTreesClassifier.html) feature importances.

`threshold` should be an evolvable `float` parameter.

For the ExtraTrees model, we should open the same parameters to evolution as we do for the [ExtraTreesClassifier operator](https://github.com/rhiever/tpot/blob/development/tpot/operators/classifiers/extra_trees.py#L46).

**Comment by teaearlgraycold** [comment]
So, something like this:

```Python
SelectFromModel(ExtraTreesClassifier, threshold=0.1)
```

Or is that not how it would be done

**Comment by rhiever** [comment]
Close:

```
SelectFromModel(ExtraTreesClassifier(criterion=criterion, max_features=max_features, min_weight_fraction_leaf=mwfl), threshold=threshold)
```

where each setting is evolvable.

**Comment by teaearlgraycold** [comment]
Okay, I think that's possible
