### ISSUE TITLE
Add OneHotEncoder operator

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#215]
We should add the sklearn [OneHotEncoder](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html) operator to TPOT's primitive set. It's useful for many classifiers for making predictions from categorical features.

The OHE operator should append the one-hot encoded features to the original feature set.

However, we shouldn't apply it to all features, especially not continuous features. I think a smart way to handle this is to only apply OHE to values within features that comprise some minimum fraction of the feature's total.

e.g., if a feature's values are `[0, 0, 0, 1, 1, 1, 2, 2, 2, 3]` and the minimum fraction is `0.2`, then the OHE will one-hot encode only `0`, `1`, and `2` as separate features. auto-sklearn has a [custom implementation](https://github.com/automl/auto-sklearn/blob/development/autosklearn/pipeline/implementations/OneHotEncoder.py) of the OneHotEncoder that does this. We can make the minimum fraction an evolvable parameter, with a minimum of e.g. 0.01.

We should also set `handle_unknown` to `'ignore'` so TPOT doesn't crash if a value is encountered in the testing set that wasn't encountered in the training set.

**Comment by rhiever** [comment]
This issue seems necessarily linked to #29.

**Comment by slcott** [comment]
I'd like to help out with this one. I'm a little new to data science, about to complete an udacity machine learning nanodegree, worked for a few months doing software development for a machine learning startup. Udacity recommended I make contributions to github projects. 

I read over deap and tpot at a high level for a few hours and the examples to get a big picture of how it works. I'm a little confused about how to integrate auto-sklearn's implementation of OneHotEncoder functionality that you would like.

Here's a quick draft. I used nystroem.py as  a template to match style.

```
from .base import Preprocessor
from sklearn.preprocessing import OneHotEncoder


class TPOTOneHotEncoder(Preprocessor):
    """Uses scikit-learn's OneHotEncoder to transform the feature set

    Parameters
    ----------
    None

    """
    import_hash = {'sklearn.preprocessing': ['OneHotEncoder']}
    sklearn_class = OneHotEncoder
    arg_types = (float, )

    def __init__(self):
        pass

    def preprocess_args(self, categorical_features="all", dtype=np.float,
                 sparse=True, minimum_fraction=None): #, kernel, gamma, n_components):
        
        # kernel_types = ['rbf', 'cosine', 'chi2', 'laplacian', 'polynomial', 'poly', 'linear', 'additive_chi2', 'sigmoid']
        # kernel_name = kernel_types[kernel % len(kernel_types)]

        # n_components = max(1, n_components)

        return {
            'categorical_features': categorical_features,
            'dtype': dtype,
            'sparse': sparse,
            'minimum_fraction': minimum_fraction,
            # 'gamma': gamma,
            # 'n_components': n_components
        }
```

**Comment by rhiever** [comment]
Happy to hear you'd like to contribute to our project, @slcott! That's a good start toward implementing the OHE in TPOT. Perhaps we'd change the `sparse=True` setting to `sparse=False` for now until we have full support for sparse matrices in TPOT (see #29).

@teaearlgraycold could also chime in on this implementation. I think we could simply copy the auto-sklearn custom OHE implementation into TPOT and import that internally. Of course, we would have to make sure that we respect their license and attribution terms.

**Comment by slcott** [comment]
I followed your comments and created a pull request of the product. 

Honestly, it's my first PR so I hope it works.

I'm still getting used to the library so I haven't tested the code yet. Some guidance on that would help me make that for following some best practices.

**Comment by rhiever** [comment]
How's the refactor coming along, @teaearlgraycold?
