### ISSUE TITLE
Alternative documentation options

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#229]
I think our [current doc pages](http://rhiever.github.io/tpot/) look crappy, and we've had several issues with Mkdocs in the past year. I'd like to consider alternative documentation options. Please add your suggestions here.
- We could use [GitHub's built-in Wiki](https://github.com/rhiever/tpot/wiki), but that seems limited
- We could look into [Sphinx](http://www.sphinx-doc.org/en/stable/)
- ... or we could spend some serious time making the docs for TPOT look nicer with a better theme and better organization.

**Comment by bartleyn** [comment]
I'm +1 for trying a different theme before jumping to some other framework. If we're keeping the current relatively flat structure of the docs (without nesting the pages for each of the operators), then it should be easy to play with different themes.

**Comment by mfeurer** [comment]
When using sphink, you could use [bootstrap sphinx](https://ryan-roemer.github.io/sphinx-bootstrap-theme/). It makes the sphinx output look like a modern html5 website. That's what we use for [auto-sklearn](http://automl.github.io/auto-sklearn/stable/)

**Comment by rhiever** [comment]
👍 I like the clean layout of bootstrap sphinx. Thank you for the suggestion @mfeurer!

**Comment by slcott** [comment]
+1 for github wiki. I think it would be easier to use for users like me to add edits too.
