### ISSUE TITLE
System for adding arbitrary default parameters to each pipeline operator

### ISSUE THREAD

**Issue by teaearlgraycold** [rhiever/tpot#232]
This needs to only apply during the GP of TPOT, with the default parameters left out of exported pipelines.

**Comment by rhiever** [comment]
Do you mean making it so pipelines during optimization have e.g. a fixed `random_state` of 42?

**Comment by teaearlgraycold** [comment]
Yes

**Comment by rhiever** [comment]
For now, we decided to do this in the `_evaluate_individual` function. We will:

1) Compile the DEAP representation to a sklearn pipeline object

2) Recurse through the sklearn objects in the pipeline, use `hasattr('random_state', obj)` to determine if it has `random_state`, and set `random_state` to some fixed number.
