### ISSUE TITLE
TPOT should fail gracefully when all pipelines fail to evaluate

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#236]
Per #233 and #234, there are sometimes cases where TPOT does not give a useful failure message when all pipelines fail to evaluate. We should have TPOT gracefully fail and output a useful message if this occurs.

We can do so by wrapping the final pipeline compile function in `fit()`, and if it fails to compile, output an error message that no pipelines were able to evaluate on the data. This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOT classifier pipelines.

**Comment by earino** [comment]
@rhiever this sounds interesting! just making sure, is http://rhiever.github.io/tpot/contributing/ still the right contribution docs?

**Comment by rhiever** [comment]
Yep, those are the latest contribution docs. To clarify, [this](https://github.com/rhiever/tpot/blob/master/tpot/tpot.py#L307) is the final compile call that I referenced in the original issue.
