### ISSUE TITLE
ValueError: Precision not allowed after some generations.

### ISSUE THREAD

**Issue by bear0330** [rhiever/tpot#239]
I run tpot 0.5 with 5 generations, after some time (I don't know how many generations passed), I got this error:

![image](https://cloud.githubusercontent.com/assets/9865603/17934524/d36b1ef6-6a4a-11e6-91c0-7ee17db4f794.png)

## Context of the issue

The parameters I used was:

```
X, y, X_train, X_test, y_train, y_test = read_data(f_training_data)

tpot = TPOT(generations=5, verbosity=2)
tpot.fit(X_train, y_train)

print(tpot.score(X_test, y_test))

tpot.export('tpot_pipeline.py')
```
Almost the same as example.

## Process to reproduce the issue

1. User creates TPOT instance
2. User calls TPOT `fit()` function with training data
3. TPOT crashes with a `ValueError` after some generations

## Expected result

Export best generation pipleline.

## Current result

Crash

## Possible fix

I have no idea and not yet test it.

## `name of issue` screenshot

See introduction above.

**Comment by bear0330** [comment]
Oh, oops, this might be duplicated with #235.

**Comment by rhiever** [comment]
Closing this issue since it's already open at #235. Please report if TPOT 0.5.1 fixed this issue for you there.
