### ISSUE TITLE
Add warm_start functionality

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#246]
Some sklearn operators offer a `warm_start` functionality that, when set to `True`, reuses and builds upon the model constructed from the previous `fit` call on the object. We should offer the same functionality with TPOT.

Since TPOT has a population (`pop`) and a Pareto front (`self._hof`) at the end of the run, we can store these objects after the `fit` call and have the `fit` function reuse these objects if `fit` has previously been called.

`warm_start` should be `False` by default.

**Comment by kamalasaurus** [comment]
Hi!  So I made a crack at this after v0.6 appeared to push up, here's what I've got so far:

https://github.com/kamalasaurus/tpot/commit/e8f47f997255250043946f55a445595bb54cdf49

I'm storing/not-rewriting pop and _hof in the case of a warm_start; I -think- that was the general plan.

I've only made additions to tpot/base.py .  The existing nosetests all seem to run fine, but I feel like I should add some others–I'm not 100% sure what to test in terms of the tpot lifecycle and when the stored variables should exist, so I'd appreciate some guidance on that.  Would it be easier to do in the form of a Pull Request?

Also, I looked at driver.py (is this feature also meant to be accessible from the command line?) and thought I'd add something like this:

```python
    parser.add_argument('--warm-start', action='store', dest='WARM_START', default=False,
        choices=[True, False], type=bool, help='use previously generated models')
```

But I'm not entirely sure if that makes any sense (can the command line pass boolean arguments?  Wouldn't the api be better being something like `-ws` which if added will flag `warm_start` to `True`?) so yeah, some guidance there would also be appreciated as well.  I'm not 100% clear on how tpot is called from the command line either...  does it boot up a new python process whenever you do so?  In which case, is warm_start even possible in that context?

So!  That's where I'm at, hopefully I didn't miss the boat completely!

Let me know what you think at your convenience!
