### ISSUE TITLE
How to force not to use xgboost, even if installed?

### ISSUE THREAD

**Issue by matalab** [rhiever/tpot#260]
How to disable xgboost usage in tpot, even if it is installed?

**Comment by rhiever** [comment]
We're trying to figure out the best way to allow the user to limit the classifiers optimized over (see #146), but it's been a bit of an interface challenge. Please feel free to drop ideas on #146, and if it's an easy enough solution, we can aim to get that feature in the 0.7 release in 2 weeks.

In the meantime, if you absolutely don't want XGBoost in your TPOT pipelines, you have two options:

1) Uninstall XGBoost

2) Remove the following lines from your TPOT install:

[Lines 34-37](https://github.com/rhiever/tpot/blob/master/tpot/operators/classifiers/__init__.py#L34) and [lines 29-32](https://github.com/rhiever/tpot/blob/master/tpot/operators/regressors/__init__.py#L29).

**Comment by rhiever** [comment]
Hi @matalab, did what I suggested resolve your issue? Do you see it is a major use case to disable XGBoost even if it's installed? Hopefully once we address #146 this will no longer be an issue.

**Comment by matalab** [comment]
Yes, it's OK. Thanks.
