### ISSUE TITLE
Error: __init__() got an unexpected keyword argument 'scoring_function'"

### ISSUE THREAD

**Issue by matalab** [rhiever/tpot#262]
I have following code thatt worked OK with previous tpot versions:
```
                # TPOT pipeline optimizer
                try:
                    my_tpot = TPOTClassifier(generations = TPOT_GENERATIONS, random_state = 42, verbosity = TPOT_VERBOSE, scoring_function = f1) 
                    classifier_algorithms.append(my_tpot)
                    classifier_names.append("TPOT")        
                except Exception, e:       
                    print 'Error with TPOT classifier. Error: %s' % e
```
However, with the 0.6.1 version of tpot I get an error:
"Error with TPOT classifier. Error: __init__() got an unexpected keyword argument 'scoring_function'"

How do I specify F1 scoring function to be used with tpot pipeline optimizer instead of accuracy?

**Comment by rhiever** [comment]
You can specify the F1 score as a string. These are your options (emphasis mine):

'accuracy', 'adjusted_rand_score', 'average_precision', **'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted'**, 'log_loss', 'mean_absolute_error', 'mean_squared_error', 'median_absolute_error', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'r2', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'roc_auc'

**Comment by rhiever** [comment]
Were you able to get this sorted out, @matalab?

**Comment by matalab** [comment]
Yes, thanks.
