### ISSUE TITLE
Error in np.recfromcsv arguments in exported python pipeline

### ISSUE THREAD

**Issue by nhrigby** [rhiever/tpot#263]
I went through the Jupyter notebook for the TPOT example using the Titanic data set from Kaggle, and found an error in output python script from export().

To read in the csv file, the output script called the numpy function recfromcsv(). np.recfromcsv in the output script uses the "sep" argument to specify that the file is comma separated. np.recfromcsv, however, does not take "sep" as a argument, but rather, "delimiter." 

Output script from export() : 
[tpot_titanic_pipeline.txt](https://github.com/rhiever/tpot/files/460263/tpot_titanic_pipeline.txt)

**Comment by rhiever** [comment]
@teaearlgraycold, can you please write up a quick patch to `master` for this?

**Comment by rhiever** [comment]
This was fixed in the 0.6.4 release. Thank you for reporting it @nhrigby.
