### ISSUE TITLE
example broken?

### ISSUE THREAD

**Issue by mstampfer** [rhiever/tpot#27]
Getting the following traceback when running the minimal working example from README.

````
Traceback (most recent call last):
  File "example.py", line 9, in <module>
    tpot.fit(X_train, y_train)
  File "/Users/marcel/workspace/tpot/tpot/tpot.py", line 162, in fit
    self.toolbox.register('evaluate', self.evaluate_individual, training_testing_data=training_testing_data)
AttributeError: 'TPOT' object has no attribute 'evaluate_individual'
````

Changing member function name back to _evaluate_individual resolves the issue.

**Comment by rhiever** [comment]
Did you install from source when you got this error? I see that one of the function registrations wasn't updated in #23 now.

**Comment by mstampfer** [comment]
Yes, I'm running a cloned copy. Should the function stay private?

**Comment by rhiever** [comment]
Yep. I'm going to fix this by changing

>self.toolbox.register('evaluate', self.evaluate_individual, training_testing_data=training_testing_data)

to

>self.toolbox.register('evaluate', self._evaluate_individual, training_testing_data=training_testing_data)

Will commit against this issue with any additional fixes as well.

**Comment by mstampfer** [comment]
Thanks. tpot looks quite useful for many things I'm working on.

**Comment by rhiever** [comment]
Great! Fix should be in the source now. Please let us know if you run into any more issues, or have any ideas on how to improve TPOT. :+1:
