### ISSUE TITLE
"Fit" function sometimes never terminates 

### ISSUE THREAD

**Issue by choosehappy** [rhiever/tpot#271]
About 80% of the time tpot never finishes (>30 hours run time currently), and in the other 20% of the time, it finishes with the same code + parameters + input in ~5 hours and produces excellent results.

The code itself isn't anything exceptional:

import time
import numpy as np
from tpot import TPOT
train_data = np.genfromtxt('fold_1_trainFeatVec.csv', delimiter=',')
train_labels= np.genfromtxt('fold_1_trainLabels.csv', delimiter=',')

tpot = TPOT(generations=20, population_size=20)

start= time.time()
tpot.fit(train_data, train_labels)
print "train acc:\t %f" % tpot.score(train_data, train_labels)
end=time.time()

I've tried installing both via:
pip install tpot

as well as using this repo:
git clone [url]
python setup.py sdist
pip install --user TPOT-0.4.1.tar.gz

**Comment by rhiever** [comment]
If you set `verbosity=2` in the `TPOT()` instantiation call, does it look like it's getting stuck on one pipeline evaluation, or is it just taking a long time in general?

Also, I strongly recommend upgrading to the latest version of TPOT (0.6.4). That alone may fix your issue.

**Comment by choosehappy** [comment]
in the instances where it works, the progress bar does move at a fairly
consistent pace.

in the failing ones, it will randomly get stuck at some percent (usually <
50%) and then never move.

i was a bit curious about the version numbers, i'm glad you mentioned it.

this github master branch doesn't contain the latest code?

because when i used "pip install tpot" and it pulled it from a distant
repo, it did in fact load a 0.6.x version, but installing directly from
github results in 0.4.x?

**Comment by rhiever** [comment]
The master branch has the latest stable release of TPOT, which is the same version that will install via pip. Hopefully the upgrade will fix your issues -- we made some major changes in 0.5 that should hopefully prevent TPOT from getting "stuck."

**Comment by choosehappy** [comment]
Unfortunately, same issue after upgrading to the latest version 

it takes about 3 minutes to get to 8/420, and then remains there for 45 minutes afterwards

![image](https://cloud.githubusercontent.com/assets/9681868/18489581/5fcc321e-79fe-11e6-8b91-f27d54d5574c.png)


i've made the code and dataset available here:

http://gleason.case.edu/webdata/tpot/

**Comment by rhiever** [comment]
I will take a closer look at this after I get back from travels late next week. My first thought as to what's occurring is that TPOT is getting "stuck" on evaluating pipelines that take a long time on a data set with many features. This doesn't necessarily mean that TPOT will never finish running, but it may take a long time on data sets with thousands of records or features. Essentially, every TPOT "tick" is performing 3-fold cross-validation on the pipeline.

My best recommendation in the meantime is to run TPOT e.g. overnight and see if it moves past one of the pipelines it gets "stuck" on. If it's still sitting there on the same pipeline 8 hours later, then I will consider this a bug.

#249 is related to this issue. We're working on allowing users to place limits on how much time or memory each pipeline evaluation is allowed to take.
