### ISSUE TITLE
TPOT example docs using incorrect parameter

### ISSUE THREAD

**Issue by kjacks21** [rhiever/tpot#277]
The code examples have the parameter `cv` while the actual parameter should be `num_cv_folds`. You can see it [here](http://rhiever.github.io/tpot/using/#tpot-with-code). This is likely due to a confusion with using -cv in the command line.

## `TPOT example docs using incorrect parameter` screenshot

![image](https://cloud.githubusercontent.com/assets/11047068/18850750/df0fef7c-8406-11e6-998d-ea930ce467b1.png)

**Comment by rhiever** [comment]
Fixed. Thanks for reporting!
