### ISSUE TITLE
Missing module: model_selection

### ISSUE THREAD

**Issue by colingoldberg** [rhiever/tpot#289]
Hi,

On an AWS EC2 (recently created) instance, with python 2.7.10, and having successfully run

$pip install deap update_checker tqdm
$pip install tpot
-- Successfully installed tpot-0.6.5

I did not use virtualenv or anaconda.

When I ran
$tpot filename.csv

it produced:
ImportError: No module named model_selection

## Context of the issue

Detail trace produced:
Traceback (most recent call last):
  File "/usr/local/bin/tpot", line 9, in <module>
    load_entry_point('TPOT==0.6.5', 'console_scripts', 'tpot')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/tpot/__init__.py", line 22, in <module>
    from .tpot import TPOTClassifier, TPOTRegressor
  File "/usr/local/lib/python2.7/site-packages/tpot/tpot.py", line 21, in <module>
    from .base import TPOTBase
  File "/usr/local/lib/python2.7/site-packages/tpot/base.py", line 35, in <module>
    from sklearn.model_selection import cross_val_score
ImportError: No module named model_selection

Output from installing tpot:
$pip install tpot
Collecting tpot
  Downloading TPOT-0.6.5.tar.gz (1.1MB)
    100% |████████████████████████████████| 1.1MB 1.0MB/s 
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/local/lib64/python2.7/site-packages (from tpot)
Requirement already satisfied (use --upgrade to upgrade): scipy in /usr/local/lib64/python2.7/site-packages (from tpot)
Requirement already satisfied (use --upgrade to upgrade): scikit-learn in /usr/local/lib64/python2.7/site-packages (from tpot)
Requirement already satisfied (use --upgrade to upgrade): deap in /usr/local/lib/python2.7/site-packages (from tpot)
Requirement already satisfied (use --upgrade to upgrade): update_checker in /usr/local/lib/python2.7/site-packages (from tpot)
Requirement already satisfied (use --upgrade to upgrade): tqdm in /usr/local/lib/python2.7/site-packages (from tpot)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.3.0 in /usr/local/lib/python2.7/site-packages (from update_checker->tpot)
Installing collected packages: tpot
  Running setup.py install for tpot ... done
Successfully installed tpot-0.6.5

I hope I have given you enough information.

Regards

Colin Goldberg

**Comment by weixuanfu2016** [comment]
Thank you for let us know this issue. I think it is related to the version of scikit learn. The module is included in the latest version (0.18) of scikit learn (it is related to this issue #284). Please update scikit learn with the command below and rerun TPOT with the latest version of scikit learn. 

```
conda update scikit-learn
```

**Comment by colingoldberg** [comment]
Thanks, that made a difference. I now get a deprecation warning running tpot.

/usr/local/lib64/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.

I hope this is useful.

Colin Goldberg

**Comment by weixuanfu2016** [comment]
Thanks. This warning is normal (I think it should not affect the performance of running the current version of TPOT) because this old module will be removed in the coming version of scikit-learn. We are working on adding compatibility into TPOT for the version 0.20 of scikit-learn.

**Comment by rhiever** [comment]
That warning is actually due to XGBoost importing the old version of `cross_validation`. Hopefully they fix it soon!
