### ISSUE TITLE
Add 'sag' solver to LogisticRegression operator for large dataset 

### ISSUE THREAD

**Issue by weixuanfu2016** [rhiever/tpot#292]
Add 'sag' solver to LogisticRegression operator for large dataset to speed up pipeline evaluation.
## Context of the issue

Default 'liblinear' solver works very good for normal dataset. But for the large dataset in the issue #271  and #290, it is very slow to evaluate pipelines with [LogisticRegression](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html) operator. So the 'sag' solver (scikit-learn version > 0.17) should works better for large dataset. It is noted that `dual` argument should be `False` when using 'sag' solver.

Test code:

```
import time
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

heldout = [0.95, 0.90, 0.75, 0.50, 0.01]
rounds = 10

X, y = datasets.make_classification(n_samples=10000, n_features=4000,
                                    n_informative=2, n_redundant=10,
                                    random_state=42)

classifiers = [
    ("liblinear", LogisticRegression(solver='liblinear', tol=1e-1, C=1.e4 / X.shape[0])),
    ("sag", LogisticRegression(solver='sag', tol=1e-1, C=1.e4 / X.shape[0]))
]



xx = (1. - np.array(heldout) )*10000

for name, clf in classifiers:
    print("training %s" % name)
    rng = np.random.RandomState(42)
    yy = []
    for i in heldout:
        yy_ = []
        for r in range(rounds):
            X_train, X_test, y_train, y_test = \
                train_test_split(X, y, test_size=i, random_state=rng)
            time_start = time.time()
            clf.fit(X_train, y_train)
            time_end = time.time()
            yy_.append(time_end-time_start)
        yy.append(np.mean(yy_))
    plt.plot(xx, yy, label=name)

plt.legend(loc="upper right")
plt.xlabel("Training Size (N)")
plt.ylabel("Average Time Usage (s)")
plt.show()
```

![time_usage_liblinearvssag](https://cloud.githubusercontent.com/assets/21084970/19292133/e0cd7568-8fe7-11e6-9641-50af54344897.png)

**Comment by rhiever** [comment]
Should we just always use the sag solver then?

**Comment by weixuanfu2016** [comment]
sag solver is only available from version 0.17 of sciket-learn. Should we add separate options of these solver based on version of sciket-learn?

**Comment by rhiever** [comment]
I think we can assume that TPOT users will be using the latest version of scikit-learn.

**Comment by kadarakos** [comment]
I suggest to use sag and always have dual on False.
