### ISSUE TITLE
Incorporating Pretrained Models

### ISSUE THREAD

**Issue by mynameisvinn** [rhiever/tpot#305]
is it possible to incorporate pretrained models as part of the feature extraction/model selection process? many tasks in computer vision, nlp, etc. often use pre-trained deep net (eg vgg16) to either (1) generate feature representations or (2) classify.

**Comment by rhiever** [comment]
It's possible if you're willing to edit the underlying TPOT code, but this functionality isn't currently built into TPOT. I can describe how to edit the TPOT code to accomplish this if you're interested.

**Comment by rhiever** [comment]
@mynameisvinn, your thoughts?

**Comment by mynameisvinn** [comment]
definitely think it's a good idea... if you give me a quick overview
