### ISSUE TITLE
tutorial files import unused packages

### ISSUE THREAD

**Issue by robinsonkwame** [rhiever/tpot#309]
Why do some tpot tutorial scripts include packages that are not called? This is relevant for understanding the output of TPOT and why or why not unused packages may be imported in the output of the pipeline generation process.

Specfically see: https://github.com/rhiever/tpot/blob/master/tutorials/tpot_titanic_pipeline.py#L5-L6, note `FunctionTransformer` and `make_union`

**Comment by rhiever** [comment]
Thanks for pointing this out! We may have to add some extra checks in the export functionality.

**Comment by rhiever** [comment]
This should be fixed in the upcoming release (currently in the `development` branch).
