### ISSUE TITLE
Making the code citable

### ISSUE THREAD

**Issue by rasbt** [rhiever/tpot#31]
Hey, since TPOT has a release tag for the "first" version as it is described in the accompanying paper, I thought it may be worthwhile to go a step "further" and get a unique DOI to cite the library. There's a nice instruction page on GitHub to set this up: https://guides.github.com/activities/citable-code/

**Comment by rhiever** [comment]
I'd rather pursue the route of requesting that they cite actual papers when using the code. It's unlikely that these code citations will be picked up by Google Scholar, so it's rather pointless to use them until then.

**Comment by rasbt** [comment]
okay sure, make sense! Was just something I stumbled upon!
