### ISSUE TITLE
Getting TPOT to work with sample_weights

### ISSUE THREAD

**Issue by joseortiz3** [rhiever/tpot#310]
Many (all?) of the classifiers and regressors (and probably some of the other pipeline elements) used by TPOT have a `sample_weights` functionality, which gives the relative importance of different samples during fitting.

I would expect the `sample_weights` feature to be used like
`
TPOTRegressor.fit(x_train, y_train, sample_weights=sample_weights)`

Which would result in the `sample_weights` being passed down to any pipeline model that can use it. For instance, if TPOT tries `GradientBoostingClassifier.fit()` (`GBC.fit()`), one of the arguments given to `GBC.fit()` would be the provided `sample_weights` (since GBC supports that already), so that the loss function used by `GBC` is weighted per-sample (not per class!). Any model that _could_ use `sample_weights` is now passed it.

How hard would it be to get this feature working? I tried to answer this question on my own, but it is challenging for someone new to the code.

**Motivation:**
I think sample weighting is important enough that it has become a standard in sklearn, so perhaps it should  also be incorporated into TPOT.

**Specific Use Case:**
In my work, my samples have very different relative importances, so this feature is crucial. My pipeline needs to predict a trinary classification: 0,1,2, for each sample (tens of thousands). But correctness is more important for some samples than others. For instance, it might be 10-1000x more important to correctly classify some samples than other samples.

**Comment by weixuanfu2016** [comment]
Thank you for sharing this idea. I have some thoughts about it. Actually, it is related to a [old issue](https://github.com/scikit-learn/scikit-learn/issues/4632) in scikit-learn. The thing you may want to try is to wrap the cross_val_score from scikit-learn to including the sample weight. Here is a [demo](https://github.com/ndawe/scikit-learn/commit/3da7fb708e67dd27d7ef26b40d29447b7dc565d7).  It's a little hacky and not guaranteed to still work with the lastest version of scikit-learn.

**Comment by rhiever** [comment]
@weixuanfu2016 / @sahilshah1194, can you please verify that all of the classifiers and regressors that we use in TPOT indeed take `sample_weights` into their `fit` functions? If so, it would be a straightforward API change for TPOT to allow `sample_weights` as an optional parameter to the `fit` function, which would simply pass those weights (or `None` by default) to the sklearn pipeline `fit` function.

**Comment by weixuanfu2016** [comment]
@rhiever Not all of them take `sample_weights`. [KNeighborsClassifier](https://github.com/scikit-learn/scikit-learn/blob/a5ab948/sklearn/neighbors/base.py#L747), [KNeighborsRegressor](https://github.com/scikit-learn/scikit-learn/blob/a5ab948/sklearn/neighbors/base.py#L727) , [ElasticNet](https://github.com/scikit-learn/scikit-learn/blob/a5ab948/sklearn/linear_model/coordinate_descent.py#L641) and [LassoLarsCV](https://github.com/scikit-learn/scikit-learn/blob/a5ab948/sklearn/linear_model/least_angle.py#L1089) do not count `sample_weights`

**Comment by rhiever** [comment]
@joseortiz3, can you please explain your specific use case here? Are you trying to balance your scoring metric based on the distribution of data? By default, TPOT uses a [balanced accuracy metric](https://github.com/rhiever/tpot/blob/bd24d60375ea2083ecfddb069eee9b9ef259ecb5/tpot/metrics.py#L25), which computes the accuracy score on a per-class basis then averages them over all classes. This helps account for class imbalance in the sense that a very rare class would be equally important as an abundant class.

**Comment by joseortiz3** [comment]
@rhiever I think I understand what you're saying, that if for instance I'm doing binary classification and I have 100 cases of class [0] and 1000000 cases of class [1] that getting the 100 [0]'s correct is just as important as getting the 10000000 [1]'s correct if I use `balanced accuracy metric`. However that is not what I'm trying to accomplish.

I have samples that I am trying to label as [-1,0,1]. Each sample has a true label [-1,0,1], and many features that I can use to try predict that label (about forty of them). However, some samples are much more important to get right than other samples. For instance, mislabelling one sample could be 100x worse than mislabelling another. Another example, two samples could be both class [1], but labelling the first a [1] could be _much_ more important than labelling the second a [1].

**Comment by rhiever** [comment]
It sounds like it should be feasible to make a custom scoring metric for TPOT, e.g., you could take the weighted average if you know the class weights ahead of time:

```python
def weighted_accuracy(y_true, y_pred):
    class_weights = {-1: 0.25, 0: 1., 1: 8.}
    all_classes = list(set(np.append(y_true, y_pred)))
    all_class_accuracies = []
    for this_class in all_classes:
        this_class_sensitivity = \
            float(sum((y_pred == this_class) & (y_true == this_class))) /\
            float(sum((y_true == this_class)))

        this_class_specificity = \
            float(sum((y_pred != this_class) & (y_true != this_class))) /\
            float(sum((y_true != this_class)))

        this_class_accuracy = (this_class_sensitivity + this_class_specificity) / 2.
        # Weight the accuracy score
        this_class_accuracy *= class_weights[this_class]
        all_class_accuracies.append(this_class_accuracy)

    return np.mean(all_class_accuracies)
```

then that function can simply be passed to TPOT's `scoring` parameter.

However, it may still make sense to integrate sample weights to affect the actual *training* of the models rather than just the evaluation of them. @weixuanfu2016, sklearn Pipeline objects allow for `fit` calls to take a `fit_params`. Maybe we can make this an optional TPOT parameter as well, and only pass it to operators that allow the `sample_weights`parameter. I started typing up a quick demo but keep getting an odd error message:

```python
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import make_classification

X, y = make_classification()

sample_weight = range(1, len(y) + 1) # made-up weights

clf_dt = make_pipeline(StandardScaler(), DecisionTreeClassifier())
clf_knn = make_pipeline(StandardScaler(), KNeighborsClassifier())

clf_dt.fit(X=X, y=y, fit_params={'decisiontreeclassifier__sample_weight': sample_weight})
```

```
sklearn/pipeline.py in _fit(self, X, y, **fit_params)
    225                                 if step is not None)
    226         for pname, pval in six.iteritems(fit_params):
--> 227             step, param = pname.split('__', 1)
    228             fit_params_steps[step][param] = pval
    229         Xt = X

ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by weixuanfu2016** [comment]
@rhiever I just looked into source codes of pipeline object of scikit-learn. the `fit_params` is not a name of argument, just a variable name of a dictionary. However, in cross_val_score, `fit_params` is the name of the argument. Very strange. The codes below works:

```
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score

X, y = make_classification()

sample_weight = range(1, len(y) + 1) # made-up weights

clf_dt = make_pipeline(StandardScaler(), DecisionTreeClassifier())

fit_params_1={'decisiontreeclassifier__sample_weight': sample_weight}
clf_dt.fit(X=X, y=y, **fit_params_1)

cv_score = cross_val_score(clf_dt, X, y, fit_params = fit_params_1 )
print(cv_score)

```

**Comment by weixuanfu2016** [comment]
@joseortiz3  #317  Here is a PR for adding sample weight into TPOT. You may want to try it on your datasets. Let us know if you have any questions or further comments.

**Comment by kkumawat25** [comment]
Hi,
 When we pass sample weights into tpot = TPOTClassifier().fit(sample_weight=sample_weights_train). These weights are only used in the Classifier or it is also used by Selector and Transformer (if applicable). I was going through top 5 evaluated_individuals_ based on internal CV score. I found one of them was -
make_pipeline(
    RFE(estimator=ExtraTreesClassifier(criterion="gini", max_features=0.35, n_estimators=100), 
           step=0.1),
    FeatureAgglomeration(affinity="euclidean", linkage="average"),
    DecisionTreeClassifier(criterion="gini", max_depth=10, min_samples_leaf=4, 
                min_samples_split=19)
                   )
In above pipeline selector step usage ExtraTreesClassifier that can use sample_weights.  When I am calling fit method on above pipeline, Should I pass sample weights to both ExtraTreesClassifier and
DecisionTreeClassifier ?
