### ISSUE TITLE
importing PROBLEM :(

### ISSUE THREAD

**Issue by sam2015** [rhiever/tpot#311]
C:\Users\pc\Anaconda2\envs\ipy_env\lib\site-packages\tpot\base.py in <module>()
     44 from .export_utils import export_pipeline, expr_to_tree, generate_pipeline_code
     45 from .decorators import _gp_new_generation, _timeout
---> 46 from . import operators
     47 from .operators import combine_dfs
     48 from .gp_types import Bool, Output_DF

ImportError: cannot import name operators

can't able to import operators Y??? :(

AND 

ImportError: No module named model_selection

change to (cross_validation) in base.py

**Comment by MrLevo520** [comment]
+1

**Comment by weixuanfu2016** [comment]
The issue related to model_selection is commented in #314. Please update the scikit-learn to 0.18.

The operators issue is strange. Could  you please let us know the python codes or command lines to produce the issue?

**Comment by sam2015** [comment]
Thanks... :)  @weixuanfu2016 problem solved.... after updating(sci kit) and reinstalling (tpot).

thanks once again.... :+1:
