### ISSUE TITLE
Add group validation (Batch validation) in fitting procedure

### ISSUE THREAD

**Issue by michael-kaiser** [rhiever/tpot#312]
Currently it is just possible to make a cross validation inside of the fitting procedure. A group validation isn't possible at the moment.

## Context of the issue

For some cases cross validation isn't the best choice. If you have different subjects, some subjects should be used for training and others for validation. This is done by group validation, where each subject would have a certain group. sklearn supports this kind of validation with LeaveOneGroupOut and LeavePGroupsOut.

**Comment by rhiever** [comment]
Can you please write a short working code example of how you would use this with the `cross_val_score` method? I'd imagine we could parameterize `cross_val_score`'s `cv` parameter to allow custom validation procedures. Currently we limit `cv` to only be integers, but it would be straightforward to allow it to take arbitrary validation procedures as well as integers.

**Comment by zoso95** [comment]
I ran into this issue recently. Sklearn let's you pass in custom cross validation into cross_val_score directly. For example

gkf = GroupKFold(n_splits=5)
X = df["numerical stuff"]
group = df["some category"]
 scores = cross_val_score(model, X,Y, cv=gkf, groups=group)

The only thing to note here is you also need to pass in groups in addition to the CV object.

**Comment by rhiever** [comment]
This feature will be added in the upcoming 0.8 release. Thanks again @zoso95.
