### ISSUE TITLE
Question: Where are the pipelines created?

### ISSUE THREAD

**Issue by bscully** [rhiever/tpot#320]
More specifically, when the pipelines are created, what are all of the permutations?  Can that logic be customized?

Pointing me to the right place in the code would be great.  

Thanks,

Ben

**Comment by rhiever** [comment]
Right now, the initial pipelines are randomly generated. [This line](https://github.com/rhiever/tpot/blob/21aad37930e2bc3cc40822abdeac5efaa1e809ce/tpot/base.py#L257) is used to create new random individuals, which uses [this](https://github.com/rhiever/tpot/blob/21aad37930e2bc3cc40822abdeac5efaa1e809ce/tpot/base.py#L256) generator. Those are the lines you would want to change if you wanted to change TPOT's initialization process.

**Comment by rhiever** [comment]
Hi @bscully, did you have any more questions on this topic?

**Comment by rhiever** [comment]
We're closing all questions that haven't been updated in a while. Please feel free to re-open this issue if your issue persists.
