### ISSUE TITLE
Internal CV for time series?

### ISSUE THREAD

**Issue by andmib** [rhiever/tpot#321]
When using the TPOT regressor on time series, is there a way to specify that TPOT use time series split from SKLearn, as opposed to the other approaches which randomly sample the data set? Time series data sets should be split such that the temporal aspect of the data is preserved in the train and test; curious if there is a way to make sure that happens with TPOT.

**Comment by rhiever** [comment]
You should be able to do this through TPOT's `num_cv_folds` parameter. We pass that parameter directly to `cross_val_score`'s `cv` parameter. Perhaps we should rename `num_cv_folds` to just `cv`, as sklearn does.

**Comment by andmib** [comment]
@rhiever Thanks - I didn't realize that, but noticed in the docs that you do mention you can pass SKLearn CV objects. That should do it.
