### ISSUE TITLE
AssertionError while trying to run Tpot.

### ISSUE THREAD

**Issue by Daniel-Aronovich** [rhiever/tpot#324]
Error while trying to run Tpot.

## Context of the issue

I fail to run tpot, I've tried all the different examples here:
http://rhiever.github.io/tpot/examples/MNIST_Example/

And I get the next error:

>   File "C:\Users\Daniel\Anaconda3\lib\site-packages\tpot\tpot\base.py", line 191, in __init__
>     self._setup_pset()
>   File "C:\Users\Daniel\Anaconda3\lib\site-packages\tpot\tpot\base.py", line 212, in _setup_pset
>     self._pset.addPrimitive(op, *op.parameter_types())
>   File "C:\Users\Daniel\Anaconda3\lib\site-packages\deap\gp.py", line 316, in addPrimitive
>     "second '%s' primitive." % (name,)
> AssertionError: Primitives are required to have a unique name. Consider using the argument 'name' to rename your second 'RobustScaler' primitive.

All the relevant dependent libraries are updated.
What can be the problem?

**Comment by rhiever** [comment]
Can you please provide details on your machine and install? Are you simply running the code in the page you linked?

**Comment by Daniel-Aronovich** [comment]
Thanks for the quick reply,

I've tried the example code as it is (tried them all).  Got the same error.

I'm using python 3 (via anaconda) on windows,  I've installed all the relevant libraries.

**Comment by rhiever** [comment]
What version of `deap` are you using? Execute the following on your command line:

```python -c "import deap; print(deap.__version__)"```

**Comment by teaearlgraycold** [comment]
@rhiever I'd recommend specifying specific versions for each dependency both in setup.py and in the installation instructions (which would need to be updated for each release).

**Comment by rhiever** [comment]
We're closing all questions that haven't been updated in a while. Please feel free to re-open this issue if your issue persists.
