### ISSUE TITLE
ENH: Include parameters in exported pipeline

### ISSUE THREAD

**Issue by westurner** [rhiever/tpot#325]
Given an exported generated pipeline, how do I know what code and parameters were used to generate it?

I can just ``open('exported_pipeline.py.json', 'w')`` and ``json.dumps(**merged_kwargs_dict)``, but it could be somehow inlined in the docstring or maybe more ideally as a data attribute of the generated pipeline?

See also: #282 "ENH: Export PEP8-formatted code"

**Comment by westurner** [comment]
... Use case: For historical purposes, I'd like to keep around generated pipelines with e.g. __00<n>.py as a suffix; as the codebase changes.

I suppose without the source or current commit rev the params are not as useful.

**Comment by westurner** [comment]
So, practically, maybe a kwarg for ``.export()`` which expects a json.dump'able object?

**Comment by westurner** [comment]
(Because if I have a grid around the TPOT hyperparameters, those constants aren't in the source)

**Comment by rhiever** [comment]
When you say parameters, do you mean TPOT parameters? e.g., mutation rate, pop size, etc.?

**Comment by westurner** [comment]
> When you say parameters, do you mean TPOT parameters? e.g., mutation rate, pop size, etc.?

Yup

**Comment by rhiever** [comment]
I know it's not ideal, but you could put that in the file name when you export. Or programmatically write out a README for each file that's exported.

**Comment by westurner** [comment]
> I know it's not ideal, but you could put that in the file name when you export. Or programmatically write out a README for each file that's exported.

- pipeline.py.json works (and maintains somewhat-structured data)
- wrapping the pipeline in a class with a ``__call__`` and a ``params`` attribute could be useful

**Comment by rhiever** [comment]
We're closing all questions that haven't been updated in a while. Please feel free to re-open this issue if your issue persists.
