### ISSUE TITLE
How to let tpot print current best pipeline when Ctrl-C/jupyter notebook interrupt ? [question]

### ISSUE THREAD

**Issue by eromoe** [rhiever/tpot#326]
Env: windows 7x64, python 2.7 32bit
Data: X.shape (9516, 24956)
Code: 
```
tpot = TPOTClassifier(generations=50, population_size=500, verbosity=2, max_eval_time_mins=20)
```

I am using jupyter notebook to train model, due to it is too slow to find best pipeline, so I want to stop at middle, but tpot doesn't print current best pipeline when exit, and the left `python.exe` still taken 90% + cpu resource.

**Comment by rhiever** [comment]
Once you interrupt the TPOT process, it stores the best pipeline internally. If for some reason it's not closing gracefully after the interrupt, you can still access the best pipeline at `tpot._fitted_pipeline`.

**Comment by rhiever** [comment]
We're closing all questions that haven't been updated in a while. Please feel free to re-open this issue if your issue persists.
