### ISSUE TITLE
Any way to speed up tpot ?

### ISSUE THREAD

**Issue by eromoe** [rhiever/tpot#327]
It is realy too slow for my work... 
I setup a 6 core 16G ram ubuntu vm, but I found tpot only use one core.

Does it (I don't see relative docs):

1. Support multi-core? 
2. Support multiple mechine cooperate? (may be something like [spark-sklearn](https://github.com/databricks/spark-sklearn) , I would like to help )
3. Support GPU?

Or is there any other way to speed up currentlly?

**Comment by rhiever** [comment]
We've been looking at parallelization options but haven't found one that quite works for us yet. Perhaps the best option right now is to run multiple instances of TPOT (10+) to get a diversity of recommendations.

**Comment by eromoe** [comment]
But multiple instances of TPOT may build many same pipeline,  why this way is better.

**Comment by arita37** [comment]
@eromoe :  Maybe, you can try Ipypa ?

**Comment by eromoe** [comment]
@arita37 What do you mean, any example ? Simply run multi tpot-instance would waste much calculation resource .The most easy and effcient way I can imagine is : 
Split all combinations of model and params tpot generated into several groups and run parallel. (But tpot not support now) .

**Comment by arita37** [comment]
You can check ipyparall documentation, pretty straightforward

On 21 Dec 2016, at 16:48, eromoe <notifications@github.com> wrote:

@arita37 What do you mean, any example ? Simply run multi tpot-instance would waste much calculation resource .The most easy and effcient way I can imagine is :
Split all combinations of model and params tpot generated into several groups and run parallel. (But tpot not support now) .

―

**Comment by eromoe** [comment]
I read the docs of ipyparall , it is just a distribute framework as my expect. If you want to do a big task efficiently, you must split it into pieces, then send to workers(ipyparall engine) which would excute tasks, but you must schedule tasks in right way first.  Runing tpot in multi-process is simple, but it not so effcient in that way.

**Comment by brianmingus** [comment]
@rhiever A good way to do this would be to focus on algorithms that have parallel implementations, such as xgboost and sklearn SGD, setting n_jobs=-1. Looking at your GECCO '16 paper, I can make the following suggestions:

- Decomposition: Instead of RandomizedPCA, use sklearn.decomposition.SparsePCA and sklearn.linear_model.SGDClassifier. The latter may seem somewhat strange, but by creating an autoencoder with SGD you implement PCA.

- Models: Set n_jobs=-1 for sklearn.ensemble.RandomForestClassifier. Do not use sklearn.ensemble.GradientBoostingClassifier, instead just use xgboost which is massively parallel. Do not use SVM - instead use SGD with n_jobs=-1.

etc. etc.

**Comment by brianmingus** [comment]
I notice that every once in a while tpot is using all the cores. I suspect this is xgboost. I recommend getting rid of as many single-core algorithms as possible - tpot performance should improve as you can afford to search a bigger space.

**Comment by brianmingus** [comment]
Anecdotally, my custom RandomizedSearchCV pipeline search over XGBRegressor is quickly discovering much more performant models than tpot.

**Comment by TheodoreGalanos** [comment]
Hi @brianmingus 

Could I ask the parameters and ranges you are searching for XGBRegressor?

**Comment by brianmingus** [comment]
https://gist.github.com/brianmingus/9628a39cf35b82d6828a6c0ceee9868d

**Comment by brianmingus** [comment]
These are just the defaults.. for some problems I leave this range. In particular n_estimators must sometimes be very large.

**Comment by TheodoreGalanos** [comment]
Thanks Brian,

Appreciate it. I'll test this out.

**Comment by rhiever** [comment]
We're closing all questions that haven't been updated in a while. Please feel free to re-open this issue if your issue persists.

**Comment by csteel45** [comment]
> Anecdotally, my custom RandomizedSearchCV pipeline search over XGBRegressor is quickly discovering much more performant models than tpot.

@ghost Would you be willing to share your custom RandomizedSearchCV?
