### ISSUE TITLE
New Feature : Ability to restrict the field of fitters through list

### ISSUE THREAD

**Issue by arita37** [rhiever/tpot#332]
Sometimes, we need to deal with large datasets, and can only use Tpot
 with only a small sub-sample (ie n= 100,000 data points) to find some high level ideas of the fitting.

Then, it would be nice to re-launch it with higher number of samples (n=1,000,000) but with restricted number of fitters (passed into a list :   **fitter_list= [ 'Ridge', 'Elastic', .... ]**  ), so training would be faster.

In general, it might a strategy to accelerate overall training
 if the pre-training on sub-samples is done in advance, and the results can be re-used for the full sample.
(supposing that data is rather IID.... )

**Comment by rhiever** [comment]
👍 

We are currently working on a feature for TPOT to allow users to fully customize the operators and operator parameters that TPOT optimizes over. That should handle your use case, although that's an up-and-coming feature.

**Comment by arita37** [comment]
Aditionnally, we need to deal with a large number of features (ncol= 1000, 5000, 10000).
Usually, we pre-process the data before feeding into TPOT, so we come up with ncol= 200 to accelerate the training.

It would be be useful to have feature reduction (automatic) models, although there is no unique solutions to this difficult problem.

For Classification, one can use Feature Importance from RF as one indicator.
PCA reduce dimensionnality (but necessary the number of input feature...).

Combining several methods would be of useful interest.
This method can be 'Orthogonal' to model selection and accelerate the model selection...

**Comment by rhiever** [comment]
TPOT has feature selectors built-in, including model-based feature selectors. It will add them to the pipeline if they improve accuracy.

**Comment by arita37** [comment]
Sure, the point : while this is clear which model seems best fit the data as well as the Hyper params,
this is not clear which feature may have of importance....
(Suppose there are 10000 features, but only 100 which gives 95% of the accuracy,...other improve the accuracy at very low marginal rate...).

Feature selection is still 'manual'.

**Comment by rhiever** [comment]
Feature selection is automated in TPOT pipelines in that TPOT decides what
type of feature selection to use and how many features to keep. Do you mean
using TPOT to automate feature selection only?

**Comment by rhiever** [comment]
We're closing all questions that haven't been updated in a while. Please feel free to re-open this issue if your issue persists.
