### ISSUE TITLE
Pywin32 is also a requirement to run on windows

### ISSUE THREAD

**Issue by CamposOnAi** [rhiever/tpot#333]
## Context of the issue
I was doing a basic script just to test TPOT for the first time. I started by installing all the dependencies listed on the website ([TPOT installation](rhiever.github.io/tpot/installing/ ))that I didin't have already. I'm running Windows 10 64 bit.

## Process to reproduce the issue
1. Import TPOT, more specifically, I tested with "from tpot import TPOTClassifier"
2. TPOT crashes with ImportError: No module named 'win32api'

## Expected result
1. Import without errors.

## Current result
1. TPOT crashes with ImportError: No module named 'win32api'

## Possible fix
Download the appropriate pywin32 for your system at [sourceforge](https://sourceforge.net/projects/pywin32/files/pywin32/).
Add pywin32 as a dependency for windows users.

After applying this fix, it worked like a charm.

**Comment by rhiever** [comment]
Was this with an [Anaconda installation](https://www.continuum.io/downloads)?

**Comment by ronico94** [comment]
No, the python distribution being used was download from the official website. Forgot to mention that I'm running python 3.5 64 bit. All other dependencies were download from [Unofficial Windows Binaries for Python Extension Packages](http://www.lfd.uci.edu/~gohlke/pythonlibs/) if available or simply by using pip.

**Comment by rhiever** [comment]
@weixuanfu2016, have you been able to reproduce this? I don't have a Windows machine to check this on, unfortunately.

**Comment by weixuanfu2016** [comment]
`pywin32` is included in anaconda installer and installed as [default](https://docs.continuum.io/anaconda/pkg-docs). But if the python is download form official website, the `pywin32` need to be installed separately. Using this module is to prevent TPOT from crashing due to KeyboardInterrupt when working with scipy, [a old issue in scipy].(http://stackoverflow.com/questions/15457786/ctrl-c-crashes-python-after-importing-scipy-stats)  We may need add this dependency in TPOT document for Windows supports.

**Comment by AStupidBear** [comment]
I have the same issue. Please add this to documentation.

**Comment by weixuanfu2016** [comment]
OK, will do.

**Comment by KatherineKing** [comment]
Even though I successfully installed pywin32, I still have this error.

**Comment by weixuanfu** [comment]
Hmm, how did you install it, via pip or conda? I think anaconda has pywin32 in default package list.

**Comment by KatherineKing** [comment]
The Python Environments in Visual Studio, which I understand as pip.

**Comment by weixuanfu** [comment]
Ok, I think it is related to the issue #605. Please install pywin32 via conda.

**Comment by KatherineKing** [comment]
Thanks. I'm not successful at installing pywin32 using the conda prompt, so I think the issue is not with TPOT.

**Comment by GinoWoz1** [comment]
Hey @KatherineKing   I had the same issue a while back and had to install via pip with a different name (below). Worked for me after. 

pip install pypiwin32
