### ISSUE TITLE
data format is not correct or data for a regression problem

### ISSUE THREAD

**Issue by budaoxiaowanzi** [rhiever/tpot#336]
my data is numpy array(11270*144), which is integer range  from (0,100), when I use TPOT classifier
the error:  <<This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object. Please make sure you passed the data to TPOT correctly.>>, I used SVM kernel (MLP) method ,the accuracy is 78% for two class, I don't know
what error for using TPOT?

**Comment by rhiever** [comment]
Can you please provide the code and data that you used to reproduce this issue?

**Comment by rhiever** [comment]
We're closing all questions that haven't been updated in a while. Please feel free to re-open this issue if your issue persists.
