### ISSUE TITLE
top_score variable unused in outputting top_score pipeline

### ISSUE THREAD

**Issue by kuratsak** [rhiever/tpot#339]
the main idea of tpot was to output the BEST pipeline reached, I believe it is not currently doing THAT specific task (at least based on recent version i installed with anaconda).

My bet is it currently outputs one of the 'recent generation' pipelines rather than the BEST one from it.

## Context of the issue
logic for saving the best pipeline at the end of the tpot learning process.

## Process to reproduce the issue
I seem to notice the top_score variable is not used when doing the loop. am i missing something?
in fact, the last pipeline to have score > -float(inf) will always be the "optimized" one.

1. User creates TPOT instance
2. User calls TPOT `fit()` function with training data
3. TPOT writes out pipeline that is NOT the best product of all its learning

## Expected result

the actual top_score pipeline to be outputted at the end of the process.

## Current result

it seems a random pipeline from the learning is output

## Possible fix

this is the code i belive to have the issue:
```
# Store the pipeline with the highest internal testing score
                    if self._hof:
                        top_score = -float('inf')
                        for pipeline, pipeline_scores in zip(self._hof.items, reversed(self._hof.keys)):
                            if pipeline_scores.wvalues[1] > top_score:
                                self._optimized_pipeline = pipeline
```

i believe adding a `top_score = pipeline_scores.wvalues[1]`
will fix it:
```
# Store the pipeline with the highest internal testing score
                    if self._hof:
                        top_score = -float('inf')
                        for pipeline, pipeline_scores in zip(self._hof.items, reversed(self._hof.keys)):
                            if pipeline_scores.wvalues[1] > top_score:
                                self._optimized_pipeline = pipeline
                                top_score = pipeline_scores.wvalues[1]
```

**Comment by rhiever** [comment]
Fixed - thank you!

**Comment by kuratsak** [comment]
I expect a large improvement of tpot honor and hype after this :muscle:
