### ISSUE TITLE
Using TPOT from command line with simple iris.csv fails with ValueError: There was an error in the TPOT optimization process

### ISSUE THREAD

**Issue by Code4SAFrankie** [rhiever/tpot#344]
Using TPOT from command line with simple iris.csv fails with ValueError: There was an error in the TPOT optimization process. This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object. Please make sure you passed the data to TPOT correctly.

Created a csv file using the IRIS dataset in the following format (ascii file):

sepallength,sepalwidth,petallength,petalwidth,class
5.1,3.5,1.4,0.2,setosa
4.9,3,1.4,0.2,setosa

Can't find any documentation about what the format of the input file should be.

Ran

tpot iris.csv -is , -target class -o tpot_out.py -mode regression -g 5 -p 20 -cv 5 -s 42 -v 2

Got error as above.

Expected it to produce an output file called tpot_out.py

Currently it is not producing any output.

This makes TPOT fairly useless to me since I cannot pass it some of my files to classify. I do not know what format sklearn's load_iris is in either; or how to get my own datasets in that format.

Also tried several other ways of running TPOT, but could not get it to work via command line. Running the example iris as a python file does however work. Did not try it with a input file though.

Python 3.5.2 |Anaconda 4.2.0 (32-bit)| (default, Jul  5 2016, 11:45:57) [MSC v.1900 32 bit (Intel)] on win32

TPOT 0.6.8

**Comment by rhiever** [comment]
All data passed to TPOT needs to be in standard scikit-learn vectorized format with all values as numbers. One potential issue with the data set snippet you posted is that the class labels are strings, not numbers. I recommend using a LabelEncoder to encode them into corresponding numbers.

**Comment by wkew** [comment]
Just a follow up to that - could it be made more explicit that strings shouldn't passed to TPOT? i.e., if you pass strings to the fit or score function, an error message comes up? (Or in a dream world, an automated LabelEncoder runs?)

I successfully ran the tpot.fit command where y_train was a list of strings (class labels). However, it was only when I tried tpot.score did it break - it can't score with string classes. 

Side note: re-running the .fit after doing using LabelEncoder, I get better CV scores? So despite the fact TPOT runs with strings, it clearly doesn't work properly but there is no obvious message to the user about this.

**Comment by rhiever** [comment]
When engineering TPOT, we followed scikit-learn's model and assumed that the data provided to TPOT will be well-formed. Otherwise we would have to add many lines of code checking for the many ways that users can provide ill-formed data to TPOT. Instead, we chose to clearly document the data format that TPOT expects and throw a generic error when TPOT runs into an optimization error (which can result from many different problems, not just data formatting issues).

If the data format expected from TPOT isn't clear from our documentation, please let us know where we can improve the documentation.

**Comment by Code4SAFrankie** [comment]
Changing the class to a number fixed it.
