### ISSUE TITLE
Python crash

### ISSUE THREAD

**Issue by anon3** [rhiever/tpot#346]
my python keeps crashing whenever I run TPOT. It usually happens at the very end of the process (98%+ done). Is this a known issue with a solution? Because of the python error, I don't have access to the last best pipeline either.

**Comment by rhiever** [comment]
What error message does it give you?

**Comment by anon3** [comment]
Python 3.5.2
tpot 0.6.8
I don't get an error in the IDE(jupyter notebook) but a window pop up message which says python has stopped working.

**Comment by rhiever** [comment]
Hmmm, that's not a very helpful error message from Python...

Was it perhaps using too much memory? How large is the dataset?

**Comment by anon3** [comment]
The dataset is about 500K rows and the my machine has 8GB RAM

**Comment by weixuanfu2016** [comment]
You may need more RAM for running this huge dataset. How many features in total?

**Comment by rhiever** [comment]
Yeah, with 500k rows it's likely crashing because your computer ran out of memory. Perhaps you can try running TPOT on a subset of the dataset.

**Comment by rhiever** [comment]
We're closing all questions that haven't been updated in a while. Please feel free to re-open this issue if your issue persists.
