### ISSUE TITLE
More explicit installation requirements 

### ISSUE THREAD

**Issue by Nozdi** [rhiever/tpot#348]
I installed this package using `pip` - it found that I have already installed libraries like scikit-learn or tqdm. Installation should updated versions as tpot is using packages in newer versions.

## Context of the issue
I run sample script and got import error from scikit-learn (I had installed version 0.17 when this library is using 0.18?).
After command: `pip install scikit-learn --upgrade` it kind of work, but blow up because of other dependency (old version of tdqm).

## Process to reproduce the issue

Create an environment with older version of scikit-learn and tqdm and then install tpot via pip.

## Expected result

All dependencies should update automatically when installing this library.

## Current result

Dependencies are not updated. TPOT is raising exception (eg. import error)

## Possible fix

`requirements.txt` file with all versions used in this lib & plug it into `setup.py`

**Comment by rhiever** [comment]
Yes, we should update this information in `setup.py`. Thank you for filing the issue!
