### ISSUE TITLE
[Bug] Operator.get_by_name does not always return correct SelectFromModel

### ISSUE THREAD

**Issue by PG-TUe** [rhiever/tpot#353]
## Context of the issue
There are two operators with the name "SelectFromModel", namely one for regression (contained in `select_from_model_r.py`) and one for classification (`select_from_model.py`).
When calling Operator.get_by_name("SelectFromModel"), either one of the two operators is returned, regardless of TPOTClassifier or TPOTRegressor being used.
Retrieving such an operator happens for example when compiling an individual to evaluate it.
This means that any primitive tree which contains SelectFromModel may have the wrong operator returned, then crash when it is invoked (because the `preprocess_args` method's signature mismatch), and thus not be evaluated.

## Process to reproduce the issue
Create two scripts, `print_names.py`:
```
import tpot.operators as op

for operator_type in op.Operator.__subclasses__():
    for operator in operator_type.__subclasses__():
        if operator.sklearn_class.__name__ == "SelectFromModel":
            print(operator)
```
and `call_print_names.py`:
```
import subprocess

for _ in range(50):
	output = subprocess.check_output(['python','print_names.py'])
	print(output)
```

`print_names.py` behaves the same as Operator.get_by_name in the way it traverses through the subclasses, and `get_by_name` would return the first match, where `print_names` just prints them all.

Run `call_print_names.py` and you will see that two operators will be returned, and the order between them will differ from run to run.

## Expected result
There should be a unique way to describe the different operators (these two specifically), so that always the same operator would be returned by the method.

## Current result
Example output:

b"<class 'tpot.operators.selectors.select_from_model_r.TPOTSelectFromModelR'>\n<class 'tpot.operators.selectors.select_from_model.TPOTSelectFromModel'>\n"
b"<class 'tpot.operators.selectors.select_from_model_r.TPOTSelectFromModelR'>\n<class 'tpot.operators.selectors.select_from_model.TPOTSelectFromModel'>\n"
b"<class 'tpot.operators.selectors.select_from_model.TPOTSelectFromModel'>\n<class 'tpot.operators.selectors.select_from_model_r.TPOTSelectFromModelR'>\n"
b"<class 'tpot.operators.selectors.select_from_model_r.TPOTSelectFromModelR'>\n<class 'tpot.operators.selectors.select_from_model.TPOTSelectFromModel'>\n"
b"<class 'tpot.operators.selectors.select_from_model.TPOTSelectFromModel'>\n<class 'tpot.operators.selectors.select_from_model_r.TPOTSelectFromModelR'>\n"

## Possible fix
Probably by going by operator class name, as those are unique, but I currently did not yet look into what that means for the rest of the code (if there is anywhere else where the mapping should be changed).

**Comment by weixuanfu2016** [comment]
Nice find. We found the limitation for using operators folder thus we are working on the new version of TPOT and will discard the whole folder and use operator dictionary instead. About this function, we will replace it with [this one](https://github.com/weixuanfu2016/tpot/blob/config_dict_rebase_dev/tpot/export_utils.py#L23-46)

**Comment by PG-TUe** [comment]
Okay, at first glance seems a bit more robust, considering there are some sanity checks going on in the functions :) 
(which I suppose is especially necessary given that you are going to allow for users to specify lists of operators)

**Comment by weixuanfu2016** [comment]
Yep, users can specify their own preferred operators and their arguments

**Comment by PG-TUe** [comment]
This specific problem is "fixed" by the rework considering this part is completely revamped, so I will close the issue.
