### ISSUE TITLE
Question - CV score on final generation and score using generated pipeline is off

### ISSUE THREAD

**Issue by naoko** [rhiever/tpot#354]
The below `tpot_1` is instance of `TPOTClassifier` with param `generation=5`

```python
>>> tpot_1.fit(X_train, y_train)
Best pipeline: LogisticRegression(input_matrix, 31.0, 11, False)
```

The 5th generation verbose output shows:
```
Generation 5 - Current best internal CV score: 0.59269085965
```

Which is very close when I run `score` with test data
```python
>>> print(tpot_1.score(X_test, y_test))
0.589534527522
```

The `tpot_1.export` then generated:
```
exported_pipeline = make_pipeline(
    LogisticRegression(C=31.0, dual=False, penalty="l2")
)
```

So I created classifier with the instruction and ran `fit` with training_data
```
clf = make_pipeline(
    LogisticRegression(C=31.0, dual=False, penalty="l2")
)
clf.fit(training_features, training_classes)
```
The average cross_val_score was `0.4600743` with training set and `0.4310142` with testing set.
This is significantly lower.

I have very sparse data
```python
>>> training_features.shape, training_classes.shape
((40050, 126355), (40050,))
```

I'm not sure if that's the cause or if there is anything else I can look into it.

**Comment by ramil** [comment]
This happened to me as well. I tried 4 times running the tool but found that the generated pipeline is off from the final generation and score. I have a sparse data as well and doing text classification. Is there a way to troubleshoot this? Thanks.

**Comment by ramil** [comment]
Hi Naoko, Were you able to figure out the issue last time? Thank you.

**Comment by rhiever** [comment]
Sorry for the slow reply on this issue -- I haven't been getting email notifications from GitHub.

One source of the discrepancy could be that different scoring metrics are being used. What metric did you use for your external test, and are you using the default scoring metric in TPOT? The default scoring metric in TPOT is balanced accuracy, which is a version of standard accuracy that accounts for class imbalance in your data. Is your data imbalanced?

**Comment by ramil** [comment]
Hi rhiever,
Thanks for the response. Yes data is imbalanced. For external test I used accuracy_score and classification_report from scikit. I am reading the posts from #6747 and I can see a lot of information from the ticket. I will post more here if I have further questions. Thanks again.

**Comment by rhiever** [comment]
We're closing all questions that haven't been updated in a while. Please feel free to re-open this issue if your issue persists.
