### ISSUE TITLE
Choosing only certain estimators

### ISSUE THREAD

**Issue by davidbp** [rhiever/tpot#359]
I have seen a couple of issues related to this topic but they seem to be closed. Nevertheless I could not find this capability in the TPOTClassifier class.

## Context of the issue

For certain problems It would be very handy to have TPOTClassifiers instances that can use ```.predict_proba``` since TPOT chooses the classifiers some "fits" will have this option while others will not (depending on the classifiers I guess).

**Is there any right now a way to choose the classifiers that will be used during the optimization process?** 

I have seen a issue and a pull request related to this topic
- https://github.com/rhiever/tpot/issues/146
- https://github.com/rhiever/tpot/pull/297

Thank you for your time

**Comment by weixuanfu2016** [comment]
You can setup a customized estimator dictionary in the current development branch in TPOT. Check the `operator_dict` parameter (`-operator` for command line) in this [manual](https://github.com/rhiever/tpot/blob/development/docs_sources/using.md) under dev

**Comment by rhiever** [comment]
We're closing all questions that haven't been updated in a while. Please feel free to re-open this issue if your issue persists.
