### ISSUE TITLE
Classifier with classifier instead of a preprocessor?

### ISSUE THREAD

**Issue by mficek** [rhiever/tpot#360]
I've spotted that some pipelines are created with classifiers instead of preprocessors:

XGBClassifier(input_matrix, 0.01, 6, 6, 30, 0.85000000000000009)
ExtraTreesClassifier(input_matrix, False, 'entropy', 0.85000000000000009, 1, 20)
ExtraTreesClassifier(ExtraTreesClassifier(input_matrix, True, 'entropy', 0.10000000000000001, 13, 6), True, 'gini', 0.75, 17, 4)

The third line shows, that ExtraTreesClassifier will be run with data preprocessed with ExtraTressClassifier, which I don't understand.

## Context of the issue

As far as I understood the concept of Tpot, there are classifiers/regressors, selectors and preprocessors. Preprocessors massage the data, classifiers do the black magic. 

To understand better, what's going on, I added some debug printouts into `eaMuPlusLambda` function:
```
for ind in population:
      pbar.write(str(ind))
```
What I observed is that sometimes a classifier (I'm solving classification task) is used as preprocessor. I wonder, if that is an intention or not?

## Process to reproduce the issue
Hard to reproduce consistently. If run several times in a row, it appears. 

1. Add debug printouts into `eaMuPlusLambda` function.
2. Comment out all classifiers except the following ones (I'm limiting the number of classifiers that should suite my needs)
 - 'sklearn.ensemble.ExtraTreesClassifier':
 - 'sklearn.linear_model.LogisticRegression': 
 - 'xgboost.XGBClassifier': 
3. Run Tpot with parameters
```
tpot = TPOTClassifier(generations=40,
                          population_size=3,
                          random_state=seed, # seed is the randomly chosen number
                          verbosity=3,
                          cv=5,
                          n_jobs=3,
                          max_eval_time_mins=5)
```
Note that I'm using some random number as random_state. 

## Expected result
I would expect only preprocessors at the place of preprocessors. But maybe I'm missing something or don't understand, what is expected.

## Current result

Pipeline like this, for example:
ExtraTreesClassifier(ExtraTreesClassifier(input_matrix, True, 'entropy', 0.10000000000000001, 13, 6), True, 'gini', 0.75, 17, 4)

## Possible fix

Is there any way now to distinguish classifiers from preprocessors? Add some?

**Comment by mficek** [comment]
Ok, I dived into the code and understood, that the preprocessors and classifiers are distinguished by what are they a subclass of. So far so good. 

My understanding is, that classifiers and regressors should appear ONLY in the root of the evaluation tree. I don't understand much, why we should have xgboost(xgboost(input_matrix, args), args) for example, it does not makes much sense to me. 

Following code from `def _setup_pset(self)` puzzles me: may I please ask why do we want rooted opperators to appear somewhere else in the tree?
```
        # Add all operators to the primitive set
        for op in self.operators:

            if op.root:
                # We need to add rooted primitives twice so that they can
                # return both an Output_DF (and thus be the root of the tree),
                # and return a np.ndarray so they can exist elsewhere in the tree.
                p_types = (op.parameter_types()[0], Output_DF)
                self._pset.addPrimitive(op, *p_types)

            self._pset.addPrimitive(op, *op.parameter_types())
```

**Comment by weixuanfu2016** [comment]
You are right about the `op.root`. 

The expression is pipeline in TPOT which [chain estimators (including classifier/regressors and preprocessors)](http://scikit-learn.org/stable/modules/pipeline.html#pipeline). For example, in the pipeline `ExtraTreesClassifier(ExtraTreesClassifier(input_matrix, True, 'entropy', 0.10000000000000001, 13, 6), True, 'gini', 0.75, 17, 4)`, the ExtraTreesClassifier in second step would use the result from the first one to fit model. You may found similar method in Grid Search, like [this](http://www.codiply.com/blog/hyperparameter-grid-search-across-multiple-models-in-scikit-learn/).

**Comment by rhiever** [comment]
Yes, what @weixuanfu2016 said. The pipeline `ExtraTreesClassifier(ExtraTreesClassifier(input_matrix, True, 'entropy', 0.10000000000000001, 13, 6), True, 'gini', 0.75, 17, 4)` does the following:

1) Fit all of the original features using an ExtraTreesClassifier
2) Take the predictions from that ExtraTreesClassifier and create a new feature using those predictions
3) Pass the original features plus the new "predicted feature" to the 2nd ExtraTreesClassifier and use its predictions as the final predictions of the pipeline

This process is called stacking classifiers, which is a fairly common tactic in machine learning.

**Comment by mficek** [comment]
Thanks for explanation, guys, I missed that. I understood it might be useful to have a new feature as a result of some classifier, but I didn't see from pipeline printout that the outer classifier consumes [X,new_feature] and not only [new_feature].

**Comment by rhiever** [comment]
Yes, sorry, the string format of the TPOT solutions is a bit confusing because of the internal representation that our optimization tool uses.
