### ISSUE TITLE
Missing cloning in varOr function

### ISSUE THREAD

**Issue by mficek** [rhiever/tpot#362]
I observed that genetic algorithm created populations of identical individuals and that the mutation happend for all the individual at once. I traced the problem down and found out, that cloning of individuals is missign and therefore some shallow copying might happen, preventing the population from healthy grow and mutation.

## Context of the issue
To understand better the functionality of Tpot, I added debugging print outs in eaMuPlusLambda showing for each generation the population, offspring and the operation used to raise the offspring (mutation, crossover, reproduction). I observed, that with small population (10 individuals) and many generations (40) the population starts to degenerate with every generation loop and all the individuals are identical. Then, once some operation is applied, it changes all the population at once. 

## Process to reproduce the issue

- Set population size = 10
- Set generations = 40
- Give random_state really a random number
- Add debug print outs to show population_individual -> operation -> offspring_individual
- Observe how population gets degenerated into one identical individual and that the population is ALL changed with one operation

## Expected result

Healthy population with a lot of variety.

## Current result

Population consists of a set of identical individuals.

## Possible fix

Add cloning into varOr function in gp_deap.py:

    offspring = []
    for _ in range(lambda_):
        op_choice = np.random.random()
        if op_choice < cxpb:            # Apply crossover
            idxs = np.random.randint(0, len(population),size=2)
    --->             ind1, ind2 = toolbox.clone(population[idxs[0]]), toolbox.clone(population[idxs[1]])
            ind_str = str(ind1)
            ind1, ind2 = toolbox.mate(ind1, ind2)
            if ind_str != str(ind1): # check if crossover generated a new pipeline
                del ind1.fitness.values
            offspring.append(ind1)
        elif op_choice < cxpb + mutpb:  # Apply mutation
            idx = np.random.randint(0, len(population))
    --->            ind = tolbox.clone(population[idx])
            ind_str = str(ind)
            ind, = toolbox.mutate(ind)
            if ind_str != str(ind): # check if mutation happend
                del ind.fitness.values
            offspring.append(ind)
        else: # Apply reproduction
            idx = np.random.randint(0, len(population))
    --->            offspring.append(toolbox.clone(population[idx]))

(sorry for not posting git patch, I'm not at my work laptop)

**Comment by weixuanfu2016** [comment]
Thank you for catching this bug. PR was just posted.
