### ISSUE TITLE
_pre_test decorator hides exceptions and does not work well on mutation/crossover

### ISSUE THREAD

**Issue by mficek** [rhiever/tpot#366]
I spotted that _pre_test decorator allows for invalid pipelines when those are a result of mutation or crossover operators.

## Context of the issue
`_pre_test` decorator should serve as a safety measure that a generated/mutated/mated pipeline is valid and could be used for data classification/regression. I observed the following behavior:

1. When  `_pre_test` decorator is used in base.py during registering functions into toolbox, such as ```self._toolbox.register('mutate', _pre_test(self._random_mutation_operator))```, it does not pass the function arguments. I tested it with debug printouts. A way to fix it is to decorate class function and register only decorated function: ```self._toolbox.register('mutate', self._random_mutation_operator)```

2. ```_pre_test(gp.cxOnePoint)``` does not pass `self` parameter of the base class into the decorator. Decorator's code fails on ```self.operators``` and ```self.operators_context```

3. The decorator works well when only a function that outputs an individual is used (such as `_generate`). Mutation and Crossover functions return a tuple, `(ind, )` and `(ind1, ind2)` respectively. Decorator than fails on `expr_to_tree(expr_test)` expression. 

4. Decorator hides all exceptions by catching them and not handling. Therefore above mentioned behavior remained undetected.   

## Process to reproduce the issue

- Add debug printout inside the decorator into `except:` section.
- Run any TPOT example.

## Expected result

- `_pre_test` should work with function that returns an individual or a tuple.
- In high verbosity mode (==3), there should be a debug printout showing that something's not going well inside the decorator.
- mutation and crossover operators should be tested by `_pre_test` and not only returne after 10 cycles of `_pre_test` inner cycle.   

## Current result

Looks good, but only because all exceptions in `_pre_test` are not handled.

## Possible fix

I'm posting PR right now that fixes this issue.

**Comment by weixuanfu2016** [comment]
Thank you for the PR #367 to fix the issue in the `_pre_test`.

**Comment by mficek** [comment]
Resolved in PR #367. Thanks for merging. Closing.
