### ISSUE TITLE
error while importing tpot

### ISSUE THREAD

**Issue by YannisPap** [rhiever/tpot#372]
I'm trying tpot in Jupyter Notebook.
I had a couple of nice runs and then when I'm trying to import it:

```{python}
from tpot import TPOTClassifier
```

I'm getting:

```OSError: PATH/TO/DATA/FILE not found.```

let me know if you need the whole Traceback.

(I'm using Python 3.5)

**Comment by weixuanfu2016** [comment]
Hmm, it is weird. `PATH/TO/DATA/FILE` should be in scripts exported by TPOT not for import. 

Could you please provide your codes or Jupyter Notebook for reproducing this issue?

**Comment by YannisPap** [comment]
Actually it crashes during the import, so I don't have any code to send you.
I'm sending you the Traceback it throughs.

It crashes when I'm trying import it in my code (tested it with Jupyter Notebook & Spyder) but I was able to run it as a command in the terminal.

```{python}
OSError                                   Traceback (most recent call last)
<ipython-input-1-b6ddd0209001> in <module>()
----> 1 from tpot import TPOTClassifier

/home/yannis/Projects/Identify-Fraud-using-Machine-Learning/tpot.py in <module>()
      8 
      9 # NOTE: Make sure that the class is labeled 'class' in the data file
---> 10 tpot_data = np.recfromcsv('PATH/TO/DATA/FILE', delimiter='COLUMN_SEPARATOR', dtype=np.float64)
     11 features = np.delete(tpot_data.view(np.float64).reshape(tpot_data.size, -1), tpot_data.dtype.names.index('class'), axis=1)
     12 training_features, testing_features, training_classes, testing_classes = \

/home/yannis/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py in recfromcsv(fname, **kwargs)
   2044     kwargs.setdefault("delimiter", ",")
   2045     kwargs.setdefault("dtype", None)
-> 2046     output = genfromtxt(fname, **kwargs)
   2047 
   2048     usemask = kwargs.get("usemask", False)

/home/yannis/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py in genfromtxt(fname, dtype, comments, delimiter, skip_header, skip_footer, converters, missing_values, filling_values, usecols, names, excludelist, deletechars, replace_space, autostrip, case_sensitive, defaultfmt, unpack, usemask, loose, invalid_raise, max_rows)
   1510                 fhd = iter(np.lib._datasource.open(fname, 'rbU'))
   1511             else:
-> 1512                 fhd = iter(np.lib._datasource.open(fname, 'rb'))
   1513             own_fhd = True
   1514         else:

/home/yannis/anaconda3/lib/python3.6/site-packages/numpy/lib/_datasource.py in open(path, mode, destpath)
    149 
    150     ds = DataSource(destpath)
--> 151     return ds.open(path, mode)
    152 
    153 

/home/yannis/anaconda3/lib/python3.6/site-packages/numpy/lib/_datasource.py in open(self, path, mode)
    499             return _file_openers[ext](found, mode=mode)
    500         else:
--> 501             raise IOError("%s not found." % path)
    502 
    503 

OSError: PATH/TO/DATA/FILE not found.
```

**Comment by rhiever** [comment]
It looks like you're trying to run code that was exported by TPOT, is that right? That's what the traceback seems to indicate. If that's the case, you need to replace the string `'PATH/TO/DATA/FILE'` with the actual path to your data file. Same for the `'COLUMN_SEPARATOR'`, with the character that separates your columns in the data file.

**Comment by YannisPap** [comment]
Actually I wasn't trying to run any code.
I opened a new notebook trying to import the library and the error was appearing.

What it is more strange is that today I tried it again and it worked just fine!

I don't know, probably something was wrong with my environment (I did some changes since then). In any case I cannot reproduce it so let's close it and if it happens again we can reopen it.

Taking advantage of the opportunity I want to thank you for this nice peace of software.
Keep up the good work.

**Comment by YannisPap** [comment]
No, it happens again.
On this [notebook](https://github.com/YannisPap/Identify-Fraud-using-Machine-Learning/blob/master/Project0.5.ipynb), look at the last cell. I'm trying to import TPOTClassifier to make a validation of my results and it appears again.

**Comment by rhiever** [comment]
Oh interesting. This looks like some strange sort of Python import error. `tpot.py` is one of the files in the TPOT project, and it seems to read your local `tpot.py` first in place of TPOT project's `tpot.py`. I'm going to file this as a separate bug report so we can figure out what to do here. In the meantime, yes, avoid having a file called `tpot.py` in your local working directory when using TPOT. Sorry for the strange bug!

**Comment by YannisPap** [comment]
According to #374 it is an unfortunate / mistaken name selection.  
I didn't realize it earlier.

**Comment by rhiever** [comment]
Yes, it seems we may not be able to work around it. Will have to investigate further.

**Comment by YannisPap** [comment]
We can live with a different filename :-)

Keep up the good work :+1:
