### ISSUE TITLE
TPOT fails to run when running in a directory with a file named "tpot.py"

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#374]
(see #372 for original context)

If the user creates a file called `tpot.py` in their working directory and runs the following line

```from tpot import TPOTClassifier```

They will have an issue using TPOT because Python imports the local `tpot.py` in place of the TPOT project `tpot.py`.

From the bug reports, this doesn't seem to be an incredibly common issue, but we should figure out a workaround so this doesn't happen.

cc @weixuanfu2016 @teaearlgraycold

**Comment by teaearlgraycold** [comment]
This isn't a bug, this just a classic rookie mistake.

Python files are treated as modules just the same as system/user libraries. They share the same namespace, and a collision in the form of a file named `tpot.py` will cause the installed library to be overwritten (this can happen with other library, `json.py` would overwrite the json library).

**Comment by teaearlgraycold** [comment]
http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-name-shadowing-trap
