### ISSUE TITLE
Add a check for invalid metrics

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#376]
If the user passes an invalid metric, we should catch that and throw an error before even starting the evaluation process. This can be accomplished by checking if the metric is in the `SCORERS` dictionary.

cc @weixuanfu2016

**Comment by weixuanfu2016** [comment]
Do you mean typo in `scoring` parameter?

**Comment by rhiever** [comment]
Yes exactly.

**Comment by rhiever** [comment]
While we're at it on this issue, maybe we can also catch when the user passes invalid data to TPOT at the beginning of `fit`.

e.g., we create a very simple sklearn pipeline (just a DecisionTree Classifier/Regressor) and try a simple fit with it on the data the user provides. If it fits without an exception (which would be caught in a try/except), then TPOT proceeds as normal. If it fails, then TPOT throws an exception stating that the data is not in proper shape.

**Comment by weixuanfu2016** [comment]
Hmm, I agree. We need a friendly warning message for input data

**Comment by rhiever** [comment]
Let's do both in this issue/PR.

**Comment by weixuanfu2016** [comment]
All right~
