### ISSUE TITLE
random_state doesn't seem to be working

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#392]
I was testing the hot patch on the development branch and noticed that `random_state` doesn't seem to be working again.

To reproduce, run this >1 times.

```time tpot https://github.com/EpistasisLab/penn-ml-benchmarks/raw/master/datasets/Hill_Valley_without_noise/Hill_Valley_without_noise.csv.gz -njobs -1 -v 2 -s 10 -p 20 -g 5```

It doesn't seem to work on the dev nor master branch. Doesn't matter the value of `n_jobs`.

cc @weixuanfu2016

**Comment by weixuanfu2016** [comment]
Hmm, I remember this issue was fixed once and confirmed by one user before. I will look into it

**Comment by weixuanfu2016** [comment]
I have run some tests for this issue. These issue happened to both [this pmlb benchmark](https://github.com/EpistasisLab/penn-ml-benchmarks/raw/master/datasets/Hill_Valley_without_noise/Hill_Valley_without_noise.csv.gz) and `digits` benchmark with `n_jobs` or without `n_jobs` (disable `pathos.multiprocessing`). So I think this issue may not be related to `n_jobs`. 

I suspect it may be from the new mu + lambda algorithm. It will need more tests for confirming it. We also need a unit test for this issue.

**Comment by rhiever** [comment]
This bug seems to be fixed on the dev branch. Will roll it out with the next release.
