### ISSUE TITLE
Unable to import TPOTClassifier

### ISSUE THREAD

**Issue by stokjakub** [rhiever/tpot#393]
I've installed all dependencies and followed the installation manual, but when I run a code, I get this error every time:

Traceback (most recent call last):
  File "tpot.py", line 1, in <module>
    from tpot import TPOTClassifier
  File "C:\Users\Kuba\tpot.py", line 1, in <module>
    from tpot import TPOTClassifier
ImportError: cannot import name 'TPOTClassifier'

The code I have is:

from tpot import TPOTClassifier
pipeline_optimizer = TPOTClassifier()

I'm not sure what I'm doing wrong. I checked path variables, all installed libraries, but nothing seems to work. All other libraries work just fine. Using Anaconda 3.6. Thanks for help!

**Comment by weixuanfu2016** [comment]
Please change the file name rather than tpot.py. Check the closed issue #372 for more details.

**Comment by stokjakub** [comment]
Thank you!!! It was all because of the wrong naming.

**Comment by ijeffking** [comment]
UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - tpot -> deap >=1.0 -> python 3.4*
Use "conda info <package>" to see the dependencies for each package.

I get the above error while trying to install tpot using Anaconda
