### ISSUE TITLE
AttributeError: 'InterruptableThread' object has no attribute '_stop'

### ISSUE THREAD

**Issue by dinhju** [rhiever/tpot#395]
tpot works with python3 but not python2
just installed tpot on top of python2 Anaconda 4.2.0 with xgboost installed.
When I try to run:

from tpot import TPOTClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target,train_size=0.75, test_size=0.25)
tpot = TPOTClassifier(generations=5, population_size=20, verbosity=2)
tpot.fit(X_train, y_train)

I get the following error
Traceback (most recent call last):
  File "<input>", line 10, in <module>
  File "C:\Program Files\Anaconda2\lib\site-packages\tpot\base.py", line 413, in fit
    verbose=self.verbosity, max_time_mins=self.max_time_mins)
  File "C:\Program Files\Anaconda2\lib\site-packages\tpot\gp_deap.py", line 138, in eaMuPlusLambda
    fitnesses = toolbox.evaluate(invalid_ind)
  File "C:\Program Files\Anaconda2\lib\site-packages\tpot\base.py", line 753, in _evaluate_individuals
    resulting_score = _wrapped_cross_val_score(sklearn_pipeline)
  File "C:\Program Files\Anaconda2\lib\site-packages\tpot\decorators.py", line 119, in limitedTime
    tmp_it.stop()
  File "C:\Program Files\Anaconda2\lib\site-packages\tpot\decorators.py", line 99, in stop
    self._stop()
AttributeError: 'InterruptableThread' object has no attribute '_stop'

Can someone please help?
PS: sklearn & xgboost work fine.

**Comment by weixuanfu2016** [comment]
It seems that _stop attribute is not available for some versions (like python2.*) of python in Windows. I will look into it and fix the bug.

Meanwhile, could you please create a python 3.5 environment with a command `conda create -n py35 python=3.5 anaconda` in your DOS [More Info](https://conda.io/docs/py2or3.html#create-a-python-3-5-environment) and then activate it by `activate py3.5` for solving the issue for now?

**Comment by weixuanfu2016** [comment]
It seems that _stop attribute is not available for some versions (like python2.*) of python in Windows. I will look into it and fix the bug.

Meanwhile, could you please create a python 3.5 environment with a command `conda create -n py35 python=3.5 anaconda` in your DOS ([More Info](https://conda.io/docs/py2or3.html#create-a-python-3-5-environment)) and then activate it by `activate py35` for solving the issue for now?

**Comment by dinhju** [comment]
thanks a lot. 
in the meantime I migrated part of the code to 3.5 and running tpot on that.
