### ISSUE TITLE
Example  in the animated GIF on front page needs updating

### ISSUE THREAD

**Issue by lesshaste** [rhiever/tpot#396]
The example in the animated GIF on the main front page is out of date.  

## Context of the issue

The animated GIF at https://github.com/rhiever/tpot includes the line

from tpot import TPOT

However in version 0.7.0 that gives an error "cannot import name TPOT"

## Process to reproduce the issue

```
from tpot import TPOT
```

## Expected result

There should be no error message.

## Current result

 "cannot import name TPOT"

## Possible fix

Update example

**Comment by weixuanfu2016** [comment]
Thank you for let us know this issue. Yes, the animated example need to be updated. Just FYI, please check the updated non-animated examples in this [link](http://rhiever.github.io/tpot/examples/)

**Comment by rhiever** [comment]
This has been on my TODO list since the 0.7 release. Hope to update it soon!

**Comment by rhiever** [comment]
Updated on master!
