### ISSUE TITLE
Boston housing prices example stalls in python 2

### ISSUE THREAD

**Issue by lesshaste** [rhiever/tpot#399]
I tested the Boston housing prices example from https://github.com/rhiever/tpot in ipython.  It appears to stall at 6% although this is different on different runs. When I run `top` I see that the CPU is mostly idle.

## Process to reproduce the issue

Run

```
from tpot import TPOTRegressor
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

digits = load_boston()
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target,
                                                    train_size=0.75, test_size=0.25)

tpot = TPOTRegressor(generations=5, population_size=20, verbosity=2)
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))
tpot.export('tpot_boston_pipeline.py')
```

and look at the progress

## Expected result

I expect it to make steady progress and finish in a reasonable amount of time.

## Current result

It makes it to 6%, although this is different on different runs, and then stops.

Optimization Progress:   6%|▊             | 7/120 [00:01<00:17,  6.31pipeline/s]

## Possible fix

Unsure

**Comment by weixuanfu2016** [comment]
Hmm, I just tested the examples more than 10 times but could not reproduce the issue. Could you please provide more information about your running environment, like OS, TPOT version, conda version and these dependencies' version etc.?

**Comment by lesshaste** [comment]
That's odd. Here is the information:

Ubuntu 16.04.2 LTS
tpot 0.7.0
scikit-learn 0.18.1

I ran `strace python boston.py` and at the point it is stalling it just prints out

`select(0, NULL, NULL, NULL, {0, 200000}) = 0 (Timeout)` repeatedly.

**Comment by lesshaste** [comment]
I just tried it on a completely different machine (OS X) at work and it gives the same problem.    Maybe discuss it at https://gitter.im/rhiever/tpot ?

**Comment by weixuanfu2016** [comment]
Thank you for these information. I have tested it with Conda and python 3.6 and could not reproduce the issue. What is your python version? I will try to build the same environment on my ubuntu for more tests.

**Comment by lesshaste** [comment]
python 2.7.12.  

I just tested python 3 and it works (apart from the odd `Invalid pipeline encountered. Skipping its evaluation.` message). 

 Is TPOT python 3 only?

**Comment by weixuanfu2016** [comment]
I tested the example in my Ubuntu 16.04.2 with built-in python 2.7.12. The issue was indeed reproduced. Then I disable the `pathos` in source codes and the example works fine then. 

Then I tried to used conda to install a new python 2.7 environment then the example works fine with `pathos` module

I think that the reason of this issue may be related to the `pathos` module which is possibly not work well with other dependencies in the built-in environment. I am thinking about using other alternative module to replace `pathos` in TPOT.

**Comment by lesshaste** [comment]
That's great you tracked down the problem.

**Comment by rhiever** [comment]
@weixuanfu2016, why do you suspect that `pathos` is the problem? It's been working fine on my install.

**Comment by weixuanfu2016** [comment]
@rhiever Oh, working fine with Ubuntu built-in python instead of anaconda python? I met the same issue in built-in python with installing all other dependencies by `pip` but had no issue with anaconda python.

So I tried to disable 'pathos' in TPOT and tested in Ubuntu  built-in python, then it worked fine. So I suspect `pathos` for this issue in built-in environment.

**Comment by rhiever** [comment]
Let's focus on finding a patch to make it work in this specific case. We've explored many different parallelization options and spent too much time on it. I want to move on.

If the issue turns out to be too complicated---and the issue is limited to Python 2---then we may just drop Python 2 support. It's too old a version of the language anyway.

**Comment by weixuanfu2016** [comment]
It works fine in anaconda python 2.7

**Comment by rhiever** [comment]
Okay. So it's a Python environment issue. @lesshaste, can you please run the following in your environment and let us know the versions that come out?

```
python --version
python -c "import numpy; print('numpy %s' % numpy.__version__)"
python -c "import scipy; print('scipy %s' % scipy.__version__)"
python -c "import sklearn; print('sklearn %s' % sklearn.__version__)"
python -c "import deap; print('deap %s' % deap.__version__)"
python -c "import xgboost; print('xgboost %s ' % xgboost.__version__)"
python -c "import update_checker; print('update_checker %s' % update_checker.__version__)"
python -c "import tqdm; print('tqdm %s' % tqdm.__version__)"
python -c "import pathos; print('pathos %s' % pathos.__version__)"
python -c "import multiprocessing; print('multiprocessing %s' % multiprocessing.__version__)"
```

**Comment by lesshaste** [comment]
Python 2.7.12

numpy 1.12.1

scipy 0.19.0

sklearn 0.18.1

deap 1.0

xgboost 0.4 

update_checker 0.16

tqdm 4.11.2

pathos 0.2.0

multiprocessing 0.70a1

**Comment by weixuanfu2016** [comment]
Hmm, do you mean python 3 also did not work? Is the python 3 environment created by anaconda?

**Comment by lesshaste** [comment]
That's right. Python 3 does not fix the problem for me. I thought it did but it just turns out the amount of progress you make varies for each run. 

I don't think I have anaconda installed at all. All the python modules are installed using pip.  Here is my python 3 environment.

Python 3.5.2
numpy 1.12.1
scipy 0.19.0
sklearn 0.18.1
deap 1.0
xgboost 0.6 
update_checker 0.16
tqdm 4.11.2
pathos 0.2.0

**Comment by weixuanfu2016** [comment]
Somehow, I fixed the issue on Ubuntu built-in python 2.7.12 by updating `pip` (`sudo pip install --upgrade pip`) and then removing `sudo pip uninstall xgboost `. Could you please try it on your Ubuntu and let me know if it works? @lesshaste

**Comment by rhiever** [comment]
I can confirm the freezing issue on my system (Python 3 with Anaconda) when I install XGBoost. It does not happen when I uninstall XGBoost.

We're going to rework the multiprocessing support in TPOT a bit so TPOT doesn't use pathos at all when `n_jobs==1`. This should allow the use of XGBoost without issue, I hope. But until we sort out the problem that XGBoost has with pathos/multiprocessing, we will need to add a block to where users cannot use `n_jobs!=1` and XGBoost within TPOT.

Thanks for reporting the issue, @lesshaste.

**Comment by lesshaste** [comment]
Deleting xgboost does seem to have done it. Thank you.

Any idea what the underlying problem could have been?

**Comment by rhiever** [comment]
My initial guess is that there is a clash between XGBoost's parallelization method (OpenMP, IIRC) and pathos/multiprocessing. But we'll need to dig into that more to find out.
