### ISSUE TITLE
Add n_estimators for ensemble methods

### ISSUE THREAD

**Issue by weixuanfu2016** [rhiever/tpot#401]
## Context of the issue

`n_estimators` parameter is missing in  operator dictionary of TPOT 0.7. We need add `n_estimators` of 100 into ensemble methods in TPOT

**Comment by rhiever** [comment]
This was done in https://github.com/rhiever/tpot/commit/c36d6cefa8219c975c8aa8f4f602b0e2258848ed

Tests need fixing though.
