### ISSUE TITLE
Extremely slow

### ISSUE THREAD

**Issue by subratac** [rhiever/tpot#404]
Running TPOT on a Windows machine with 24G RAM  Xeon E5 Processor on a dataset with ~50K records and 217 features (train_X). It's a three class problem (Kaggle Housing Listing competition dataset) 

from tpot import TPOTClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

tpot = TPOTClassifier(generations=5, population_size=50, verbosity=2)
tpot.fit(train_X, train_y)
tpot.export('tpot_housing_pipeline.py') 

====
Optimization progress: 50%  | 152|300 [3:38:30<3:10:42,  77.31/pipeline]

Completed 2 generations 

Any suggestions on speeding this up? Thanks for the nice program. Randal, full credit to you if it shows improvement on the leaderboard! Thanks!

**Comment by weixuanfu2016** [comment]
For Windows OS, I think the only way to speed up TPOT is to set a maximum evaluation time of a single pipeline with the `max_eval_time_mins` parameters in TPOT. The default `max_eval_time_mins` is 5 minutes. For the case in this issue, the average time per pipeline is around 77 seconds. You may try to set this parameter to `max_eval_time_mins=2` for skipping these time-consuming pipeline. This parameter is available in version > 0.6.6 of TPOT. Also, please try this parameter in python 3.5 environment for current TPOT 0.7. A patch for supporting python 2.7 in Windows was updated yesterday in GitHub but I am not sure the TPOT in PyPi is up to date.

**Comment by weixuanfu2016** [comment]
BTW, `n_jobs` parameter (default value = 1) can set the number of CPUs for evaluating pipelines in parallel during the TPOT optimization process. It can speed up a lot with using multiple cores, but sadly this function is not available in Windows OS now. For such a good machine you have, you may build a virtual machine running Linux for this jobs.

**Comment by subratac** [comment]
Thanks for your notes. You are right, building a virtual Linux machine could be a good solution. I am afraid thought that I might screw up somewhere since I am not at all good with this! But, it seems like I have to learn how to do it. 
I am finding out (very quickly) that a lot of the functionalities are not available or don't work properly on Windows, but work perfectly on MacOS and Linux machines. I was using mlxtend to build stacked classifier and it would not take Xgboost as the meta classifier on my machine. It worked when other tried on their Mac and Linux machines. Maybe, because most of the developers are using Mac & Linux ...
Your help and suggestions much appreciated.

**Comment by weixuanfu2016** [comment]
Just FYI, I just add Parallelization function for Windows OS in the PR #406. But it has not been fully tested yet. If you want to speed up in the Windows OS, please try it in this git branch of my tpot repo.

**Comment by subratac** [comment]
I uninstalled tpot using pip on Anaconda: pip uninstall tpot
Then, went to your branch and did the following on my Windows Anaconda prompt:
pip install git+https://github.com/weixuanfu2016/tpot.git
Looks like it installed TPOT==0..7.0

However, when I run TPOT with n_jobs = -1, I get the following:

**Comment by weixuanfu2016** [comment]
Thank you for testing this new function. You install master branch in my repo. Try to the command below for switching to the branch with this new function. 

```
pip install git+https://github.com/weixuanfu2016/tpot.git@replace_pathos
```

Alternatively, for the tests, you could try to use `git` command to run these new codes in repo without installing into you system environment. Commands are list below and more information can be found in this [link](http://rhiever.github.io/tpot/contributing/).

```
git clone git@github.com:weixuanfu2016/tpot.git
cd tpot
# switch to the branch with new function in Windows OS
git checkout replace_pathos 
# Once some changes are saved locally, you can use your tweaked version of TPOT by navigating to the project's base directory (the command of `cd tpot` above)
```

**Comment by rhiever** [comment]
Hi @subratac,

Has the latest release of TPOT helped with your run-time issue? We've changed to a better multiprocessing scheme in the latest release.

**Comment by rhiever** [comment]
Closing this issue for now. Please re-open if the issue continues.
