### ISSUE TITLE
Boston housing prices example stalls on OS X

### ISSUE THREAD

**Issue by lesshaste** [rhiever/tpot#405]
This is related to https://github.com/rhiever/tpot/issues/399. 

On OS X the Boston housing prices example stalls when using python 2 even without xgboost installed.

## Context of the issue

System Version: macOS 10.12.4

My OS X system which shows this problem has the following version numbers

Python 2.7.10
numpy 1.12.0
scipy 0.18.1
sklearn 0.18.1
deap 1.0
ImportError: No module named xgboost
update_checker 0.16
tqdm 4.11.2
pathos 0.2.0
multiprocessing 0.70a1

## Process to reproduce the issue

Run

```
from tpot import TPOTRegressor
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

digits = load_boston()
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target,
                                                    train_size=0.75, test_size=0.25)

tpot = TPOTRegressor(generations=5, population_size=20, verbosity=2)
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))
tpot.export('tpot_boston_pipeline.py')
```

and look at the progress

## Expected result

I expect it to make steady progress and finish in a reasonable amount of time.

## Current result

It makes it to around 5%  although this is different on different runs, and then stops.

Optimization Progress:   5%|▋             | 9/180 [00:01<00:19,  8.81pipeline/s]

## Possible fix

Unsure

**Comment by lesshaste** [comment]
It is very inconsistent, something running to completion and sometimes stalling right at the start at 1%.

**Comment by weixuanfu2016** [comment]
I remove `pathos` dependency in the PR #406, which may should the issue in built-in environment. Could you please have a try in this git branch of my repo?

**Comment by rhiever** [comment]
Hi @lesshaste---just wanted to check if the recent fixes on the dev branch helped on your end. We're still doing internal testing and everything seems fine in our tests.

**Comment by lesshaste** [comment]
I may not be able to test it for a couple of weeks as I won't have access to the OS X machine. My apologies.

**Comment by rhiever** [comment]
Hi @lesshaste, we're eager to hear how the latest release has helped with your run-time issues. It seems to be working quite well on our end with the latest multiprocessing changes. All of the changes that @weixuanfu2016 mentioned are now in the latest `pip` release.

**Comment by lesshaste** [comment]
It works perfectly now, thank you.  

Now I just have to work out how to install xgboost on OS X.

**Comment by weixuanfu2016** [comment]
Good to know that the issue is fixed. 

BTW, the instruction in this [link](https://www.ibm.com/developerworks/community/blogs/jfp/entry/Installing_XGBoost_on_Mac_OSX?lang=en) may help you install xgboost on MacOS.

**Comment by rhiever** [comment]
Great to hear. Good luck with installing XGBoost on OS X. It can be a big pain.
