### ISSUE TITLE
[Development Branch] Not all tests pass?

### ISSUE THREAD

**Issue by PG-TUe** [rhiever/tpot#408]
While working on my own branch, I ran into an issue with some failing tests. After some investigation, it seems this issue arises (for me) already on the development branch (unmodified).

Running `nosetests -s -v` gives (in the end):
```
======================================================================
ERROR: Assert that the TPOTRegressor score function outputs a known score for a fix pipeline
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/name/anaconda3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/name/tpottest/tpot/tests.py", line 263, in test_score_3
    tpot_obj._optimized_pipeline = creator.Individual.from_string(pipeline_string, tpot_obj._pset)
  File "/home/name/anaconda3/lib/python3.5/site-packages/deap/gp.py", line 127, in from_string
    .format(primitive, primitive.ret, type_))
TypeError: Primitive <deap.gp.Terminal object at 0x7fc1f533bb88> return type <class 'tpot.operator_utils.GradientBoostingRegressor__subsample'> does not match the expected one: <class 'tpot.operator_utils.GradientBoostingRegressor__n_estimators'>.

======================================================================
ERROR: Assert that the TPOTRegressor score function outputs a known score for a fixed pipeline with sample weights
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/name/anaconda3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/name/tpottest/tpot/tests.py", line 291, in test_sample_weight_func
    tpot_obj._optimized_pipeline = creator.Individual.from_string(pipeline_string, tpot_obj._pset)
  File "/home/name/anaconda3/lib/python3.5/site-packages/deap/gp.py", line 127, in from_string
    .format(primitive, primitive.ret, type_))
TypeError: Primitive <deap.gp.Terminal object at 0x7fc1f541d7e0> return type <class 'tpot.operator_utils.GradientBoostingRegressor__subsample'> does not match the expected one: <class 'tpot.operator_utils.GradientBoostingRegressor__n_estimators'>.

======================================================================
FAIL: Assert that generate_pipeline_code() returns the correct code given a specific pipeline
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/name/anaconda3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/name/tpottest/tpot/tests.py", line 516, in test_generate_pipeline_code
    assert expected_code == generate_pipeline_code(pipeline, tpot_obj.operators)
AssertionError

----------------------------------------------------------------------
```
My sklearn version is 0.18.1.
## Possible fix
*I have not had the time to properly look into this, so these are simple guesses*
I think the issue with the with the first two errors has to do with the fact that the default `from_string` method does not take into account omitted parameters (in this case n_estimators)?

In the fail case, the two strings also differ with `n_estimators` and `subsample`:

`generated code`: `'make_pipeline(\n    make_union(\n        make_union(VotingClassifier([(\'branch\',\n            GradientBoostingClassifier(learning_rate=38.0, max_depth=5, max_features=5, min_samples_leaf=5, min_samples_split=0.05, n_estimators=0.5)\n        )]), FunctionTransformer(lambda X: X)),\n        make_union(VotingClassifier([(\'branch\',\n            make_pipeline(\n                ZeroCount(),\n                GaussianNB()\n            )\n        )]), FunctionTransformer(lambda X: X))\n    ),\n    KNeighborsClassifier(n_neighbors=18, p="uniform", weights=2)\n)'`

`expected_code`: `'make_pipeline(\n    make_union(\n        make_union(VotingClassifier([(\'branch\',\n            GradientBoostingClassifier(learning_rate=38.0, max_depth=5, max_features=5, min_samples_leaf=5, min_samples_split=0.05, subsample=0.5)\n        )]), FunctionTransformer(lambda X: X)),\n        make_union(VotingClassifier([(\'branch\',\n            make_pipeline(\n                ZeroCount(),\n                GaussianNB()\n            )\n        )]), FunctionTransformer(lambda X: X))\n    ),\n    KNeighborsClassifier(n_neighbors=18, p="uniform", weights=2)\n)'`

Maybe different versions of sklearn come into play? In the case of the failed test, this certainly does not seem future proof, perhaps we should force a certain (latest?) version of sklearn for the tests. Not sure how to approach this.

**Comment by weixuanfu2016** [comment]
Yes, a few unit tests in dev branch are not fixed yet after refining some operators's parameters in default operator dictionary. This [commit](https://github.com/weixuanfu2016/tpot/commit/544fdf3450c2a056db30f31f945712ef8382e8a9) (not merged yet) fixed these unit tests.

**Comment by PG-TUe** [comment]
Okay, good. I wasn't sure if this was known :+1:

**Comment by PG-TUe** [comment]
Closing since an upcoming commit will fix this.

**Comment by PG-TUe** [comment]
Sorry for the spam. Is there a timeline when this will be merged? I noticed it also removes pathos - and I have just been working all afternoon merging in those changes into my own branch ^^', I am not completely done yet - so I could put it on hold if the merge would happen soon?

**Comment by rhiever** [comment]
Merged just now. Sorry---was taking a break this weekend. :-)

**Comment by PG-TUe** [comment]
Great to hear, thanks!
