### ISSUE TITLE
TPOT Error on Running in Jupyter Notebook

### ISSUE THREAD

**Issue by skackar** [rhiever/tpot#419]
This will help people deal with issues relating to correct installation of TPOT

## Error on Importing TPOT in Jupyter Notebook

Exact Error Name: "No Module Named TPOT"

I installed TPOT using PIP and it was installed as one of Anaconda's site packages. Not sure why I am still getting this error. It seems like TPOT is installed correctly.
## Process to reproduce the issue

[ordered list the process to finding and recreating the issue, example below]

1. User creates TPOT instance
2. User calls TPOT `fit()` function with training data
3. TPOT crashes with a `KeyError` after 5 generations

## Expected result

[describe what you would expect to have resulted from this process]

## Current result

[describe what you currently experience from this process, and thereby explain the bug]

## Possible fix

[not necessary, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by weixuanfu2016** [comment]
Could you please let me know more details about your Anaconda environment, like which version of python? 

Could you please try the commands below in DOS in Windows or Terminal in macOS/Linux and then let me know what shows up in stdout?

python --version
python -c "import tpot; print('tpot %s' % tpot.__version__)"

**Comment by weixuanfu2016** [comment]
Oh, I think I may know the reason for this issue.

Please try `import tpot` instead of `import TPOT` in the Jupyter Notebook

**Comment by skackar** [comment]
I am using Anaconda 2.5 with Python 2.7

![image](https://cloud.githubusercontent.com/assets/19595496/25208184/c88e6b12-2527-11e7-8f0c-59a070a27824.png)

**Comment by weixuanfu2016** [comment]
Oh, I think I may know the reason for this issue.

Please try import tpot instead of import TPOT in the Jupyter Notebook

**Comment by skackar** [comment]
I am using "from tpot import TPOTClassifier"

**Comment by weixuanfu2016** [comment]
? same error?

**Comment by skackar** [comment]
yes

**Comment by weixuanfu2016** [comment]
Hmm, could you please upload your jupyter notebook herein with more detailed error message?

**Comment by skackar** [comment]
Not allowing me to upload a Jupyter notebook. The error is "No Module Named tpot".

Here is the screenshot:

![image](https://cloud.githubusercontent.com/assets/19595496/25208412/673dcd6a-2529-11e7-80cf-e391d9f7bedd.png)

The python version is 2.7, anaconda 2.5.

TPOT version is 0.7.1

**Comment by weixuanfu2016** [comment]
Oh, I just noticed that there were two version of python in the screenshot on the comment above. One is 2.7.12 and another one is 2.7.13. It seems that you have two different environments but one of them did not have tpot module.

For better managing environment, I recommend to use conda to set/create/ a new environment. Check the [link](https://conda.io/docs/py2or3.html#install-a-different-version-of-python)

**Comment by rhiever** [comment]
What if you run the command ```!pip install tpot``` within one of the IPython Notebook cells? Can you import TPOT then? I suspect what @weixuanfu2016 suspects, which is that you have multiple Python installations on your computer.

**Comment by skackar** [comment]
ok, I updated python version and environment to python3.5. It works fine there. I guess it doesnt work for python 2.7

**Comment by rhiever** [comment]
TPOT does work for Python 2.7, as Python 2.7 is included in our continuous integration testing. I suspect that your latest installation of Python 3.5 fixed your environment issues.

Glad to hear everything is sorted out and working for you!
