### ISSUE TITLE
Too long idling of multiprocessing between each generation in TPOT 0.7.2 or 0.7.1

### ISSUE THREAD

**Issue by YukiSakai1209** [rhiever/tpot#422]
When I analyze my data using TPOT 0.7.2 or 0.7.1, it somehow works, but sometimes I have to wait too much idling time (stop of multiprocessing) between each generation. It often costs only about 5-10 minutes but sometimes up to several hours. I analyzed same data several times, it happened irregularly. For example, if I set max_time_mins = 480, sometimes 13000 pipelines have finished but sometimes only 2000 pipelines. It is too slow sometimes, but it seems not to stop since it restarts multiprocessing several hours later. During idling time only 1 thread is working.

Example: idling between 1:41:07 and 3:09:10, 3:22:39 and 6:33:23
Optimization Progress: 100%|| 200/200 [16:43<00:00, 117.68s/pipeline]Generation 1 - Current best internal CV score: 0.6093781690008105
Optimization Progress: 100%|| 300/300 [17:59<00:00, 58.66s/pipeline]Generation 2 - Current best internal CV score: 0.6093781690008105
Optimization Progress: 100%|| 400/400 [19:11<00:00, 29.34s/pipeline]  Generation 3 - Current best internal CV score: 0.6093781690008105
Optimization Progress: 100%|| 500/500 [22:27<00:00, 16.38s/pipeline]Generation 4 - Current best internal CV score: 0.6093781690008105
Optimization Progress: 100%|| 600/600 [25:13<00:00,  9.43s/pipeline]Generation 5 - Current best internal CV score: 0.6093781690008105
Optimization Progress: 100%|| 700/700 [30:41<00:00,  7.01s/pipeline]Generation 6 - Current best internal CV score: 0.6093781690008105
Optimization Progress: 100%|| 800/800 [38:33<00:00,  8.67s/pipeline]Generation 7 - Current best internal CV score: 0.6135697635697636
Optimization Progress: 100%|| 900/900 [41:21<00:00,  6.60s/pipeline]Generation 8 - Current best internal CV score: 0.6171742094383603
Optimization Progress: 100%|| 1000/1000 [47:07<00:00,  7.06s/pipeline]Generation 9 - Current best internal CV score: 0.6171742094383603
Optimization Progress: 100%|| 1100/1100 [51:27<00:00,  6.82s/pipeline]Generation 10 - Current best internal CV score: 0.6171742094383603
Optimization Progress: 100%|| 1200/1200 [1:07:34<00:00, 14.93s/pipeline]Generation 11 - Current best internal CV score: 0.6171742094383603
Optimization Progress: 100%|| 1300/1300 [1:13:39<00:00, 10.61s/pipeline]Generation 12 - Current best internal CV score: 0.6171742094383603
Optimization Progress: 100%|| 1400/1400 [1:17:34<00:00,  7.45s/pipeline]Generation 13 - Current best internal CV score: 0.6171742094383603
Optimization Progress: 100%|| 1500/1500 [1:21:49<00:00,  5.65s/pipeline]Generation 14 - Current best internal CV score: 0.6171742094383603
Optimization Progress: 100%|| 1600/1600 [1:41:07<00:00, 12.69s/pipeline]Generation 15 - Current best internal CV score: 0.6171742094383603
Optimization Progress: 100%|| 1700/1700 [3:09:10<00:00, 57.32s/pipeline]Generation 16 - Current best internal CV score: 0.6171742094383603
Optimization Progress: 100%|| 1800/1800 [3:12:19<00:00, 29.56s/pipeline]Generation 17 - Current best internal CV score: 0.6171742094383603
Optimization Progress: 100%|| 1900/1900 [3:22:39<00:00, 18.61s/pipeline]Generation 18 - Current best internal CV score: 0.6171742094383603
Optimization Progress: 100%|| 2000/2000 [6:33:23<00:00, 104.47s/pipeline]e]Generation 19 - Current best internal CV score: 0.6171742094383603
Optimization Progress: 100%|| 2100/2100 [6:35:20<00:00, 52.13s/pipeline]   Generation 20 - Current best internal CV score: 0.6171742094383603
Optimization Progress: 100%|| 2200/2200 [6:47:16<00:00, 31.04s/pipeline]Generation 21 - Current best internal CV score: 0.6171742094383603
Optimization Progress: 100%|| 2300/2300 [6:58:15<00:00, 21.19s/pipeline]Generation 22 - Current best internal CV score:

## Context of the issue
This kind of issue around multiprocessing has often been discussed. I tried uninstall of xgboost, but I cannot fix it.

My environment is like below:
 Ubuntu 14.04 LTS (22 CPUSs, 44 threads)(RAM: 128G)
 Python 3.5.3
 numpy 1.12.1
 scipy 0.19.0
 sklearn 0.18.1
 deap 1.0
 xgboost: No
 update_checker 0.16
 tqdm 4.11.2
 pathos 0.2.0
 multiprocess 0.70.5

## What are the relevant issues?
#399
#390 

## Process to reproduce the issue
1. Creates TPOT instance
2. Calls TPOT `fit()` function with training data
3. TPOT seems to work fine, but sometimes it idles several hours and restarts multiprocessing suddenly.

## Expected result
Move to next generation quickly.

## Current result
Too long idling between each generation. During it, multiprocessing is not working and only 1 CPU is working.

## Possible fix
Not sure.

**Comment by weixuanfu2016** [comment]
I have set chunk size of multiprocessing is equal to 4 X n_jobs for updating process bar after finishing  a chunk. So it is possible that a pipeline which takes a lot of time in one chunk. I think we may need better way to update process bar during multiprocessing. For now, you may try to set the max evaluation time of a single pipeline via `max_eval_time_mins` parameters (5 minutes by defaults) to skip these time-consuming (or stucked) pipelines.

**Comment by YukiSakai1209** [comment]
Thank you very much for your quick response.
Now I set max_eval_time_mins =5 (default values). Like the case above, idling is sometimes about 3 hours. During that, only 1 thread is working. Although I'm not sure how multiprocessing steps are organized in TPOT, do you mean that many pipelines are calculated sequentially in one thread and the time for [about 5minutes * the number of calculated piplines] are consuming? Is there any way to assign multiprocessing resource again to thouse almost stucked pipelines?
If not, I have to decrease max_eval_time_mins. I think that it is practical, but it will not lead to fundamental resolution.

**Comment by weixuanfu2016** [comment]
Hmm, it should not be 3 hours. Could you please share your test codes and dataset (if available) with us? I would like to run more tests for this issue.

**Comment by YukiSakai1209** [comment]
I cannot share my own data with you. I'm sorry for inconvenience.
I tried to reproduce the issue in MNIST example. If I use the code below (the differences with MNIST example are generations and population_size were changed into default values, and n_jobs=-1 was inserted), everythings worked well. 

from tpot import TPOTClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, train_size=0.75, test_size=0.25)
tpot = TPOTClassifier(verbosity=2, n_jobs=-1)
tpot.fit(X_train, y_train)

In addition, I increased the feature size by 36 times (X_train: 1347 x 64 -> 1347 x 2304) using np.concatenate (X_train x 36), since the number of features is similar with my case.
In this trial, the idling happened between 4:33:24 and 5:53:54 for about 1.5 hours (as you can see, other steps are 5-10 minutes). During this, only 1 CPU was working and other resources (e.g. RAM) was not so working. But, after this idling, everything goes well again.
Is this issue reproducible? Are there something hard to be treated in parallel during each generation? Maybe due to my local resources??

Optimization Progress:   2%|▏         | 200/10100 [21:21<298:06:29, 108.40s/pipeline]Generation 1 - Current best internal CV score: 0.9666839080558811
Optimization Progress:   3%|▎         | 300/10100 [31:38<177:30:15, 65.21s/pipeline]Generation 2 - Current best internal CV score: 0.9666839080558811
Optimization Progress:   4%|▍         | 400/10100 [39:21<101:26:42, 37.65s/pipeline]Generation 3 - Current best internal CV score: 0.9822110227694297
Optimization Progress:   5%|▍         | 500/10100 [51:15<69:25:47, 26.04s/pipeline]Generation 4 - Current best internal CV score: 0.9822110227694297
Optimization Progress:   6%|▌         | 600/10100 [1:01:48<52:05:06, 19.74s/pipeline]Generation 5 - Current best internal CV score: 0.9822110227694297
Optimization Progress:   7%|▋         | 700/10100 [1:08:13<33:54:45, 12.99s/pipeline]Generation 6 - Current best internal CV score: 0.9822110227694297
Optimization Progress:   8%|▊         | 800/10100 [1:18:38<34:16:31, 13.27s/pipeline]Generation 7 - Current best internal CV score: 0.9822110227694297
Optimization Progress:   9%|▉         | 900/10100 [1:27:39<28:10:51, 11.03s/pipeline]Generation 8 - Current best internal CV score: 0.9837096564596672
Optimization Progress:  10%|▉         | 1000/10100 [1:38:46<34:29:15, 13.64s/pipeline]Generation 9 - Current best internal CV score: 0.9837096564596672
Optimization Progress:  11%|█         | 1100/10100 [1:48:44<29:43:31, 11.89s/pipeline]Generation 10 - Current best internal CV score: 0.9837096564596672
Optimization Progress:  12%|█▏        | 1200/10100 [1:57:25<25:13:44, 10.20s/pipeline]Generation 11 - Current best internal CV score: 0.9837096564596672
Optimization Progress:  13%|█▎        | 1300/10100 [2:04:02<20:57:00,  8.57s/pipeline]Generation 12 - Current best internal CV score: 0.984447663839741
Optimization Progress:  14%|█▍        | 1400/10100 [2:09:34<15:43:57,  6.51s/pipeline]Generation 13 - Current best internal CV score: 0.984447663839741
Optimization Progress:  15%|█▍        | 1500/10100 [2:41:56<38:32:18, 16.13s/pipeline]Generation 14 - Current best internal CV score: 0.984447663839741
Optimization Progress:  16%|█▌        | 1600/10100 [2:46:53<23:19:49,  9.88s/pipeline]Generation 15 - Current best internal CV score: 0.984447663839741
Optimization Progress:  17%|█▋        | 1700/10100 [3:01:11<22:13:03,  9.52s/pipeline]Generation 16 - Current best internal CV score: 0.984447663839741
Optimization Progress:  18%|█▊        | 1800/10100 [3:04:03<12:54:42,  5.60s/pipeline]Generation 17 - Current best internal CV score: 0.984447663839741
Optimization Progress:  19%|█▉        | 1900/10100 [3:09:35<9:44:45,  4.28s/pipeline]Generation 18 - Current best internal CV score: 0.984447663839741
Optimization Progress:  20%|█▉        | 2000/10100 [3:32:25<24:48:26, 11.03s/pipeline]Generation 19 - Current best internal CV score: 0.984447663839741
Optimization Progress:  21%|██        | 2100/10100 [3:43:46<19:49:51,  8.92s/pipeline]Generation 20 - Current best internal CV score: 0.984447663839741
Optimization Progress:  22%|██▏       | 2200/10100 [3:45:47<10:58:05,  5.00s/pipeline]Generation 21 - Current best internal CV score: 0.984447663839741
Optimization Progress:  23%|██▎       | 2300/10100 [3:48:45<7:26:33,  3.44s/pipeline]Generation 22 - Current best internal CV score: 0.984447663839741
Optimization Progress:  24%|██▍       | 2400/10100 [3:59:05<9:54:56,  4.64s/pipeline]Generation 23 - Current best internal CV score: 0.984447663839741
Optimization Progress:  25%|██▍       | 2500/10100 [4:05:01<8:22:48,  3.97s/pipeline]Generation 24 - Current best internal CV score: 0.984447663839741
Optimization Progress:  26%|██▌       | 2600/10100 [4:18:08<11:59:03,  5.75s/pipeline]Generation 25 - Current best internal CV score: 0.984447663839741
Optimization Progress:  27%|██▋       | 2700/10100 [4:28:49<12:17:02,  5.98s/pipeline]Generation 26 - Current best internal CV score: 0.9844476638397411
Optimization Progress:  28%|██▊       | 2800/10100 [4:33:24<8:28:08,  4.18s/pipeline]Generation 27 - Current best internal CV score: 0.985182716555299
Optimization Progress:  29%|██▊       | 2900/10100 [5:53:54<48:41:05, 24.34s/pipeline]Generation 28 - Current best internal CV score: 0.985182716555299
Optimization Progress:  30%|██▉       | 3000/10100 [6:01:47<28:02:24, 14.22s/pipeline]Generation 29 - Current best internal CV score: 0.985182716555299
Optimization Progress:  31%|███       | 3100/10100 [6:16:29<21:35:34, 11.10s/pipeline]Generation 30 - Current best internal CV score: 0.985182716555299
Optimization Progress:  32%|███▏      | 3200/10100 [6:25:28<15:46:54,  8.23s/pipeline]Generation 31 - Current best internal CV score: 0.985182716555299
Optimization Progress:  33%|███▎      | 3300/10100 [6:31:13<10:40:25,  5.65s/pipeline]Generation 32 - Current best internal CV score: 0.985182716555299

**Comment by weixuanfu2016** [comment]
After more tests, I suspected it may be a issue related to memory usage for multiprocessing with large data sets and some memory-consuming pipeline. As a quick test: what if you use the [TPOT light configuration on 0.7.2](http://rhiever.github.io/tpot/using/#built-in-tpot-configurations)

**Comment by rhiever** [comment]
Closing this issue for now. Please feel free to re-open if you have any more questions or comments.
