### ISSUE TITLE
Should the TPOT score function return the abs of the scoring metric?

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#425]
TPOT's scoring function currently returns the `abs` of the scoring metric: https://github.com/rhiever/tpot/blob/7970e73788ac8d834bb3dbd9b28b66a0d3343504/tpot/base.py#L567

Yet we don't `abs` the score from `cross_val_score` during the TPOT optimization process. After some discussions with @teaearlgraycold, we recalled that some regression metrics return negative values, which is likely the logic behind applying `abs`. However, it seems strange that we don't also `abs` the resulting score from `cross_val_score`. I've had a bit of a long day and can't quite work this out right now, but I'd like to get to the bottom of whether applying `abs` to the score is correct here.

cc @weixuanfu2016

**Comment by weixuanfu2016** [comment]
For now, the score for time-consuming or failed pipeline is set to be `-float(inf)`. `abs` should not works for all the scoring in TPOTClassifier. Maybe we should add some exception for these specific regression metrics which return negative values.

**Comment by rhiever** [comment]
Right. Currently when processing scoring functions, we assume that any scoring functions with "loss" or "error" in the name should be minimized. So we set the `greater_is_better` parameter in the `make_scorer` function to `False`: https://github.com/rhiever/tpot/blob/7970e73788ac8d834bb3dbd9b28b66a0d3343504/tpot/base.py#L258

That means the scoring function returns the negative of the score, so any optimizers (grid search, etc.) using `cross_val_score` can still assume that "greater is better" for the score.

So I suppose the `abs` in the `score` function offsets the negative of the score that is applied when `greater_is_better==False`.

As far as I can tell, none of the functions supported by TPOT (https://github.com/rhiever/tpot/blob/7970e73788ac8d834bb3dbd9b28b66a0d3343504/tpot/base.py#L123) return actual negative values. So perhaps we're fine with leaving the `abs` in the TPOT `score` function.
