### ISSUE TITLE
Error when reading config dictionary

### ISSUE THREAD

**Issue by alfonsomhc** [rhiever/tpot#429]
This is the example provided in the documentation:

```
from tpot import TPOTClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target,
                                                    train_size=0.75, test_size=0.25)

classifier_config_dict = {
    'sklearn.naive_bayes.GaussianNB': {
    },

    'sklearn.naive_bayes.BernoulliNB': {
        'alpha': [1e-3, 1e-2, 1e-1, 1., 10., 100.],
        'fit_prior': [True, False]
    },

    'sklearn.naive_bayes.MultinomialNB': {
        'alpha': [1e-3, 1e-2, 1e-1, 1., 10., 100.],
        'fit_prior': [True, False]
    }
}

tpot = TPOTClassifier(generations=5, population_size=20, verbosity=2,
                      config_dict=classifier_config_dict)
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))
tpot.export('tpot_mnist_pipeline.py')
```

When I run it, I get this:

```
TypeError                                 Traceback (most recent call last)
/home/user/anaconda3/lib/python3.6/site-packages/tpot/base.py in __init__(self, generations, population_size, offspring_size, mutation_rate, crossover_rate, scoring, cv, n_jobs, max_time_mins, max_eval_time_mins, random_state, config_dict, warm_start, verbosity, disable_update_check)
    210                 try:
--> 211                     with open(config_dict, 'r') as input_file:
    212                         file_string =  input_file.read()

TypeError: expected str, bytes or os.PathLike object, not dict

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-1-f4f30d147b28> in <module>()
     23 
     24 tpot = TPOTClassifier(generations=5, population_size=20, verbosity=2,
---> 25                       config_dict=classifier_config_dict)
     26 tpot.fit(X_train, y_train)
     27 print(tpot.score(X_test, y_test))

/home/user/anaconda3/lib/python3.6/site-packages/tpot/base.py in __init__(self, generations, population_size, offspring_size, mutation_rate, crossover_rate, scoring, cv, n_jobs, max_time_mins, max_eval_time_mins, random_state, config_dict, warm_start, verbosity, disable_update_check)
    213                     operator_dict = eval(file_string[file_string.find('{'):(file_string.rfind('}') + 1)])
    214                 except:
--> 215                     raise TypeError('The operator configuration file is in a bad format or not available. '
    216                                     'Please check the configuration file before running TPOT.')
    217         else:

TypeError: The operator configuration file is in a bad format or not available. Please check the configuration file before running TPOT.
```

I'm running version '0.7.2'

**Comment by weixuanfu2016** [comment]
Oh, this is a mistake in our document and we need update the using of configuration dictionary  in version 0.7.2. From 0.7.2, this parameter do not support python dictionary anymore. Please write to a text file and use the path (string) of the file for this parameter.

**Comment by weixuanfu2016** [comment]
@rhiever I think we need restore the support for python dictionary in `config_dict ` parameter in interactive mode (shown in the TPOT example) as I removed this support when including TPOT light and TPOT MDR for this parameter.

**Comment by weixuanfu2016** [comment]
@alfonsomhc I just make a quick PR for restoring python dictionary support in TPOT but for now you still need use file path instead of a python dictionary unless you pull the commit to your local repo. Sorry for the inconvenience.

**Comment by alfonsomhc** [comment]
@weixuanfu2016 , thanks a lot :)

**Comment by alfonsomhc** [comment]
By the way, sending the config to an external file gives an error as well:

`from tpot import TPOTClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target,
                                                    train_size=0.75, test_size=0.25)

classifier_config_dict = 'test.conf'

tpot = TPOTClassifier(generations=5, population_size=20, verbosity=2,
                      config_dict=classifier_config_dict)
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))
tpot.export('tpot_mnist_pipeline.py')`

Where test.conf is a file that contains the dictionary definition. This produces this error:

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-3e350f442b73> in <module>()
     10 
     11 tpot = TPOTClassifier(generations=5, population_size=20, verbosity=2,
---> 12                       config_dict=classifier_config_dict)
     13 tpot.fit(X_train, y_train)
     14 print(tpot.score(X_test, y_test))

/home/user/anaconda3/lib/python3.6/site-packages/tpot/base.py in __init__(self, generations, population_size, offspring_size, mutation_rate, crossover_rate, scoring, cv, n_jobs, max_time_mins, max_eval_time_mins, random_state, config_dict, warm_start, verbosity, disable_update_check)
    220         self.operators = []
    221         self.arguments = []
--> 222         for key in sorted(self.config_dict.keys()):
    223             op_class, arg_types = TPOTOperatorClassFactory(key, self.config_dict[key],
    224             BaseClass=Operator, ArgBaseClass=ARGType)

AttributeError: 'TPOTClassifier' object has no attribute 'config_dict'`

**Comment by weixuanfu2016** [comment]
Opps, this is a bug for this function...it is fixed in dev branch but not merged yet...

**Comment by weixuanfu2016** [comment]
@rhiever I make a patch #431  for master branch for this issue. Could you please merge it?

@alfonsomhc Thank you for let us know this issue. Sorry for the inconvenience.

**Comment by weixuanfu2016** [comment]
@alfonsomhc if you want to use TPOT 0.7.2 with this patch in your environment today or this weekend. Please try the command below to reinstall tpot

```
pip install --upgrade --no-deps --force-reinstall git+https://github.com/weixuanfu2016/tpot.git@config_dict_patch
```

**Comment by alfonsomhc** [comment]
@weixuanfu2016 , the fix seems to work. You are awesome! Thanks a lot :D

**Comment by rhiever** [comment]
Merged into master. Release going out soon.

**Comment by weixuanfu2016** [comment]
Thanks @rhiever

**Comment by rhiever** [comment]
0.7.3 is now out with the patch. Thanks for raising the issue!

**Comment by alfonsomhc** [comment]
Thanks to you all! It's so cool that you managed to fix the bug and release an update within 8 hours :)

**Comment by rhiever** [comment]
While on travel nonetheless. :-)
