### ISSUE TITLE
some un-tested error/except code paths include python2 uncompliant code

### ISSUE THREAD

**Issue by kuratsak** [rhiever/tpot#435]
found a few lines with:

`Exception('some message').with_traceback(traceback)`

in their except clauses.

Just checked, this breaks on python 2. might be worth adding tests for exception paths and make sure they are python 2 viable too.

I havent checked the whole project, might have similar problems with py2 code that is not py3 compliant.

## Process to reproduce the issue

[ordered list the process to finding and recreating the issue, example below]

1. User creates TPOT instance
2. User calls TPOT `fit()` function with training data
3. TPOT raise an `IndexError` in the _generate function under base.py (line 979 for example)
4. The exception keeps going up because under py2 the except clause also raises an exception.

**Comment by weixuanfu2016** [comment]
Which version of python 2? Could you please provide more details about running environment or/and codes for reproducing this issue?

**Comment by kuratsak** [comment]
Add a line: raise IndexError('blabla') In the location I wrote in the
issue. As far as I've checked, python 2 doesn't have the method
"with_traceback" under the BaseException class as opposed to python 3..

**Comment by rhiever** [comment]
`with_traceback` is indeed a Python 3-only function. I don't think it's really necessary that we use it there, right @weixuanfu2016?

**Comment by weixuanfu2016** [comment]
I agree. I will submit a PR for removing these lines with `with_traceback`

**Comment by kuratsak** [comment]
I recommend using traceback module. As far as I know it's both 2 and 3
compliant and very useful to see traceback in many cases.
I intend to add traceback info in some places in tpot myself.

**Comment by rhiever** [comment]
Merged on the dev branch.
