### ISSUE TITLE
Break export() down into 3 separate functions

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#44]
`export()` is currently too large. Break it down into 3 functions based on the primary steps of the function:

- Replace all of the mathematical operators with their results

- Unroll the nested function calls into serial code

- Replace the function calls with their corresponding Python code

This change will make it easier to unit test the `export()` function as well.

**Comment by UniqueFool** [comment]
also, the website/example may need to be updated to ensure that the examples there actually work with what's currently available via pip

**Comment by pronojitsaha** [comment]
@rhiever While I am working on this, can you provide some inputs on the 'type' and 'contents' of the following just to be sure
-exported_pipeline, 
-pipeline_list, and 
-operator_text

**Comment by rhiever** [comment]
@pronojitsaha, it may be best to hold off on this issue until we see what affect @dmarx's refactor (see https://github.com/rhiever/tpot/issues/43#issuecomment-165660908) has on the export function. I suspect it will shrink the export function significantly.

**Comment by pronojitsaha** [comment]
Ok. I see that @dmarx's implementation still has the first two functions in export i.e. 

- Replace all of the mathematical operators with their results

- Unroll the nested function calls into serial code

Should I break that into separate functions, it will streamline export() further and then incorporate @dmarx's refactor?

**Comment by dmarx** [comment]
@pronojitsaha: Sounds good to me

**Comment by pronojitsaha** [comment]
@dmarx Ok..great! Will get it done tomorrow.

**Comment by rhiever** [comment]
:+1:

**Comment by pronojitsaha** [comment]
@rhiever While we await the integration of #63, it will be good to break the final part i.e. 'Replace the function calls with their corresponding Python code' into a separate function or a code that the main tpot file imports from for improved code readability and comprehensibility significantly (similar way that I did the first two). I already have a basic structure, if you want can create a PR for it and you can look at it?

**Comment by rhiever** [comment]
Sounds good to me.

On Wednesday, December 23, 2015, PRONOjit Saha <notifications@github.com>
wrote:

> @rhiever <https://github.com/rhiever> While we await the integration of
> #63 <https://github.com/rhiever/tpot/pull/63>, it will be good to break
> the final part i.e. 'Replace the function calls with their corresponding
> Python code' into a separate function or a code that the main tpot file
> imports from for improved code readability and comprehensibility
> significantly (similar way that I did the first two). I already have a
> basic structure, if you want can create a PR for it and you can look at it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/tpot/issues/44#issuecomment-166890685>.
>


-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com
