### ISSUE TITLE
How to update to 0.7.3 in anaconda

### ISSUE THREAD

**Issue by Ajay95** [rhiever/tpot#442]
Hi ,
I am using tpot V 0.6.4 for a long time ,and when i saw that there is a 0.7.3 version available .
But when I check for updating the package it shows only 0.6.4 is available .
How can I update to 0.7.3?

**Comment by weixuanfu2016** [comment]
Please try `sudo pip install tpot --upgrade`

**Comment by Ajay95** [comment]
Thank You

**Comment by weixuanfu2016** [comment]
Please let me know if the command didn't work.

**Comment by weixuanfu2016** [comment]
Great

**Comment by Ajay95** [comment]
The pywin command needs to be updated in the tpot installation page as I was getting error 
  
 No matching distribution found

**Comment by rhiever** [comment]
I don't recommend running `pip install --upgrade <package>` with Anaconda. A better way to upgrade is to run:

`pip uninstall tpot -y; pip install tpot --no-cache`

**Comment by weixuanfu2016** [comment]
Looks good. Should we add a upgrading section in docs about installation?

**Comment by rhiever** [comment]
Maybe, but this isn't really something that's specific to TPOT. It's a general Anaconda/pip issue.
