### ISSUE TITLE
Export intermediate results

### ISSUE THREAD

**Issue by jimmywan** [rhiever/tpot#448]
While TPOTRegressor gives me some one stop shopping in terms of generating a model, I'd really like to analyze how other top candidates were constructed. I don't currently see a way to export all of the candidate models that get built via TPOT.
For instance, I may want to do one or more of the following:
 - Apply some type of checks to the model that are not easily captured by a single scoring method.
 - Compare/contrast selected features among the different top models to understand their differences.

It looks like I currently can only get the output of the winning model via the exported pipeline.

**Comment by weixuanfu2016** [comment]
Please check my comments in #337. A demo there may help you to get intermediate results.

**Comment by jimmywan** [comment]
Thanks @weixuanfu2016 , I will take a look.

**Comment by rhiever** [comment]
Closing this issue for now. Please feel free to re-open if you have any more questions or comments.
