### ISSUE TITLE
Add more feature selection operators

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#45]
Add more feature selection operators from sklearn:

- [x] VarianceThreshold: http://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.VarianceThreshold.html#sklearn.feature_selection.VarianceThreshold

- [x] SelectKBest: http://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectKBest.html#sklearn.feature_selection.SelectKBest

- [x] SelectPercentile: http://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectPercentile.html#sklearn.feature_selection.SelectPercentile

- [x] Recursive Feature Elimination: http://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html#sklearn.feature_selection.RFE

**Comment by bartleyn** [comment]
Would these be options that fall under the _dt_feature_selection method?

**Comment by rhiever** [comment]
Nope - these will be separate functions.

On Friday, December 4, 2015, Nathan <notifications@github.com> wrote:

> Would these be options that fall under the _dt_feature_selection method?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/tpot/issues/45#issuecomment-162125985>.
>


-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by bartleyn** [comment]
Right, duh, because dt stands for decision tree. These operators would then act as alternatives to _dt_feature_selection. I'd be interested in taking a stab at it tonight/this weekend.

**Comment by rhiever** [comment]
Awesome. I'll keep an eye out for the PR!

On Friday, December 4, 2015, Nathan <notifications@github.com> wrote:

> Right, duh, because dt stands for decision tree. These operators would
> then act as alternatives to _dt_feature_selection. I'd be interested in
> taking a stab at it tonight/this weekend.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/tpot/issues/45#issuecomment-162132367>.
>


-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by rhiever** [comment]
@bartleyn, just wanted to ping you about this one to see if you're working on it. If not, I'll likely try to tackle this issue this week.

**Comment by bartleyn** [comment]
Was actually about to submit my PR -- I've gotten all four to work as additional operators, but could probably use some optimization (no caching, etc). Also could probably abstract a couple additional things.

**Comment by rhiever** [comment]
Woohoo! :+1:

In your PR, please note what operators are slow (and how they can be optimized) and how else the code can be improved so we can file them as PRs or fix them on the spot.

Cheers!
