### ISSUE TITLE
config_dict='TPOT MDR' Error

### ISSUE THREAD

**Issue by ilyes495** [rhiever/tpot#450]
[provide general introduction to the issue and why it is relevant to this repository]
I'm trying to run TPOT classifier on my dataset using MDR configuration option, but I get the following error 
![screenshot from 2017-05-16 17-24-20](https://cloud.githubusercontent.com/assets/17175391/26111077/c8947238-3a5c-11e7-9674-715a28987d03.png)
 .........
![screenshot from 2017-05-16 17-27-29](https://cloud.githubusercontent.com/assets/17175391/26111137/f784096e-3a5c-11e7-822e-bea02b6e17f2.png)

Any help with the problem........ Thanks

**Comment by weixuanfu2016** [comment]
It seems that no valid pipeline was randomly generated. Could you please let me know which version of scikit-MDR? I think `TPOT MDR` should work with version 0.4.3 and 0.4.4.

**Comment by ilyes495** [comment]
scikit-MDR was 0.4.4  and I changed it to 0.4.3 and still give the same error

**Comment by weixuanfu2016** [comment]
Thank you for letting us know this issue. The issue is caused by a recent update in [scikit-MDR](https://github.com/EpistasisLab/scikit-mdr/commit/6046ac963000de6ba90d2c0194a2a7446ea4b755#diff-102b1487e5185df93069d2af9ffce457) where MDR was not setting as a subclass of `ClassifierMixin` .

I will submit a PR soon to fix this compatibility issue in TPOT. 

For solving the issue temperately, please try the codes below to use TPOT MDR.

```
tpot_mdr_classifier_config_dict = {

    # Classifiers

    'mdr.MDRClassifier': {
        'tie_break': [0, 1],
        'default_label': [0, 1]
    },

    # Feature Selectors

    'skrebate.ReliefF': {
        'n_features_to_select': range(1, 6),
        'n_neighbors': [2, 10, 50, 100, 250, 500]
    },

    'skrebate.SURF': {
        'n_features_to_select': range(1, 6)
    },

    'skrebate.SURFstar': {
        'n_features_to_select': range(1, 6)
    },

    'skrebate.MultiSURF': {
        'n_features_to_select': range(1, 6)
    }

}

tpot = TPOTClassifier(generations=5, population_size=50, verbosity=3, config_dict=tpot_mdr_classifier_config_dict)

```

**Comment by weixuanfu2016** [comment]
Or you can try this dictionary in dev branch.
```
tpot_mdr_classifier_config_dict = {

    # Classifiers

    'sklearn.linear_model.LogisticRegression': {
        'penalty': ["l1", "l2"],
        'C': [1e-4, 1e-3, 1e-2, 1e-1, 0.5, 1., 5., 10., 15., 20., 25.],
        'dual': [True, False]
    },

    # Feature constructors

    'mdr.MDR': {
        'tie_break': [0, 1],
        'default_label': [0, 1]
    },

    # Feature Selectors

    'skrebate.ReliefF': {
        'n_features_to_select': range(1, 6),
        'n_neighbors': [2, 10, 50, 100, 250, 500]
    },

    'skrebate.SURF': {
        'n_features_to_select': range(1, 6)
    },

    'skrebate.SURFstar': {
        'n_features_to_select': range(1, 6)
    },

    'skrebate.MultiSURF': {
        'n_features_to_select': range(1, 6)
    }

}

```

**Comment by rhiever** [comment]
Fixed and rolled out in the latest TPOT release.
