### ISSUE TITLE
Incompatible with newest Xgboost

### ISSUE THREAD

**Issue by gaw89** [rhiever/tpot#469]
TPOT does not work with newest version of Xgboost.

## Context of the issue

@rhiever, as of [this PR](https://github.com/dmlc/xgboost/pull/2323) which we discussed [here](https://github.com/dmlc/xgboost/issues/2321), Xgboost now supports the proper Sklearn parameter `'random_state'` and has deprecated the old parameter `'seed'`.  As a result, when running TPOTClassifier's fit method with the newest version of Xgboost, the usage of Sklearn's `clone()` raises a `RunTimeError`. 

## Process to reproduce the issue
1. Install Xgboost from source
2. Install TPOT (from source, as I couldn't get the pip install to work - probably should raise a separate issue for that)
3. TPOT crashes with a `RuntimeError` before producing any output.

## Expected result

It should fit a TPOTClassifier without error.

## Current result

`clone()` raises a `RunTimeError`.  Here are the pertinent sections of the traceback:

  File "build\bdist.win-amd64\egg\tpot\gp_deap.py", line 346, in _wrapped_cross_val_score
    tmp_it = Interruptable_cross_val_score(clone(sklearn_pipeline), features, classes,

RuntimeError: Cannot clone object XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=9, min_child_weight=16, missing=None, n_estimators=100,
       n_jobs=1, nthread=1, objective='binary:logistic', random_state=42,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=0, silent=True,
       subsample=0.3), as the constructor does not seem to set parameter seed

## Note
I have not been able to reproduce this issue manually either by cloning and XGBClassifier or by cloning a Pipeline that contains an XGBClassifier.

**Comment by weixuanfu2016** [comment]
It is related to this issue #466

**Comment by gaw89** [comment]
Yes, sorry.  Just saw that.  Any updates on getting this compatibility issue fixed?

**Comment by gaw89** [comment]
Got it.  Closing this and installing your branch for now until it gets merged.
