### ISSUE TITLE
Input data is not in valid format

### ISSUE THREAD

**Issue by ryanallen82** [rhiever/tpot#478]
When I try to fit on the X_train and y_train (from train_test_split) I get the following error:

ValueError: Error: Input data is not in a valid format. Please confirm that the input data is scikit-learn compatible. For example, the features must be a 2-D array and target labels must be a 1-D array.

Here is the code:

```
from tpot import TPOTClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, f1_score

import pandas as pd

df = pd.read_csv('data.csv')
df.drop('Unnamed: 0', inplace=True, axis=1)

X = df.drop('PAIDFLAG', axis=1)
y = df['PAIDFLAG']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.3)

tpot = TPOTClassifier(max_time_mins=60, verbosity=2)
tpot.fit(X_train, y_train)

```
And the full error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-18-98a85d84ca90> in <module>()
----> 1 tpot.fit(X_train, y_train)

/Users/m097654/anaconda/lib/python2.7/site-packages/tpot/base.pyc in fit(self, features, classes, sample_weight)
    397             clf = clf.fit(features, classes)
    398         except:
--> 399             raise ValueError('Error: Input data is not in a valid format. '
    400                              'Please confirm that the input data is scikit-learn compatible. '
    401                              'For example, the features must be a 2-D array and target labels '

ValueError: Error: Input data is not in a valid format. Please confirm that the input data is scikit-learn compatible. For example, the features must be a 2-D array and target labels must be a 1-D array.

I've gotten tpot to work on other examples doing the same exact thing, but using the regressor instead of the classifier.

**Comment by weixuanfu2016** [comment]
From the error message `tpot.fit(X_train.as_matrix(), y_train.as_matrix())`, I think you may add `as_matrix()` in the codes. Could you try the codes again with `as_matrix()`?

**Comment by weixuanfu2016** [comment]
From the error message `tpot.fit(X_train.as_matrix(), y_train.as_matrix())`, I think you might add `as_matrix()` in the codes. Could you try the codes again without `as_matrix()`?

**Comment by ryanallen82** [comment]
No luck, then I get:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-98a85d84ca90> in <module>()
----> 1 tpot.fit(X_train.as_matrix(), y_train.as_matrix())

/Users/m097654/anaconda/lib/python2.7/site-packages/tpot/base.pyc in fit(self, features, classes, sample_weight)
    397             clf = clf.fit(features, classes)
    398         except:
--> 399             raise ValueError('Error: Input data is not in a valid format. '
    400                              'Please confirm that the input data is scikit-learn compatible. '
    401                              'For example, the features must be a 2-D array and target labels '

ValueError: Error: Input data is not in a valid format. Please confirm that the input data is scikit-learn compatible. For example, the features must be a 2-D array and target labels must be a 1-D array.


Same things but with the updated code.

**Comment by ryanallen82** [comment]
Oh sorry, I did both and neither worked.

**Comment by weixuanfu2016** [comment]
Please try this codes below in your data and Let me know what happens.
```
from sklearn.tree import DecisionTreeClassifier\
clf = DecisionTreeClassifier(max_depth=5)
clf = clf.fit(X_train, y_train)

**Comment by ryanallen82** [comment]
Done and dusted, I had NA's in my X_train. Did a fillna and it's golden. Thanks for helping me walk through it.

**Comment by weixuanfu2016** [comment]
My pleasure. BTW, next version of TPOT will have imputation function to deal with NA. #253

**Comment by ryanallen82** [comment]
Fantastic! This tools is quickly becoming an integral part of the 'experimentation' phase of my projects. Thanks for all the hard work.
