### ISSUE TITLE
tpot should handle --version argument

### ISSUE THREAD

**Issue by UniqueFool** [rhiever/tpot#48]
I was running into runtime errors when executing the example (MNIST data set): "AttributeError: TPOT instance has no attribute 'export'", and was hoping to check if the correct tpot version is installed, but it seems that --version isn't supported.

**Comment by rhiever** [comment]
Fair enough. If you import the library, you can check the version with:

    import tpot
    print(tpot.__version__)

Should be easy enough to add --version as a command line parameter.

BTW: the `export()` functionality has not been included with a release yet; it's only available in the dev version.

**Comment by UniqueFool** [comment]
re: export() - thanks for clarifying - you may want to add a corresponding note to the example on the website, because that is kinda unexpected, i.e. most people will probably try to run your examples first

**Comment by rhiever** [comment]
I'll push out a new version to pip today with the export feature.

**Comment by rhiever** [comment]
TPOT v0.2.0 is out on pip with the export functionality. Enjoy, and thanks for your feedback!

**Comment by UniqueFool** [comment]
once again, thank you for being so responsive!
