### ISSUE TITLE
Add a list of related projects to the docs

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#494]
This can be another section in the docs. We should list some related AutoML projects that are open source:

* [Auto-Weka](http://www.cs.ubc.ca/labs/beta/Projects/autoweka/)

* [auto-sklearn](https://github.com/automl/auto-sklearn)

* [devol](https://github.com/joeddav/devol)

* [Xcessiv](https://github.com/reiinakano/xcessiv)

Please list more AutoML projects here.

**Comment by tnlin** [comment]
Maybe should create an awesome list?
Here is another one call [automl](https://github.com/ClimbsRocks/auto_ml)

**Comment by rhiever** [comment]
Thanks @tnlin! I'll be honest: I'm not a fan of the awesome lists. :-) So I'll probably just keep it to a section of the docs for TPOT.

**Comment by rhiever** [comment]
@teaearlgraycold is taking on this issue.

**Comment by rhiever** [comment]
@teaearlgraycold, think you can PR this early this week? Would be good to get this issue finished before we start anything larger.

**Comment by teaearlgraycold** [comment]
I've added a table of related projects. Any other information I should provide?

**Comment by rhiever** [comment]
Looks good---thanks @teaearlgraycold.
