### ISSUE TITLE
Question about implications of LGPL

### ISSUE THREAD

**Issue by reiinakano** [rhiever/tpot#495]
Apologies if this isn't the correct place to ask the question, but I was wondering what the implications of TPOT's LGPL license are in relation to using it in my own open source projects.

Xcessiv is currently under Apache 2.0 and I was wondering if I used TPOT (i.e. just ``import TPOT`` without changing any of TPOT's source code), I would have to switch Xcessiv to use LGPL as well? Thanks!

**Comment by weixuanfu2016** [comment]
I think you need relicense Xcessiv for importing TPOT based on the [link](https://www.apache.org/legal/resolved.html#category-x).

**Comment by reiinakano** [comment]
I actually realized that because of how Xcessiv is built, I wouldn't actually need to do `import TPOT`.

I'd just be using Python's duck typing and assume I'm working with a TPOT object. It's not even a hack or a workaround, as for my particular use case, it's literally the straightforward way to do things.

Of course, now my question is if I could include TPOT in my setup.py as a dependency. Would still work if not, but then users would have to install TPOT separately.

**Comment by rhiever** [comment]
If you import TPOT as a core part of the software you release, then yes, our understanding of the LGPL is that you must relicense Xcessiv to LGPL as well. An exception to this is if you're using the code exported from TPOT, though, which does not have the LGPL license applied to it.

Including TPOT in your `setup.py` should not entail that requirement. It sounds like you found a good workaround for it. :-)

**Comment by reiinakano** [comment]
Neat. Thanks for clarification!

**Comment by pa0ti** [comment]
I still have to do a lot of reading on LGPL implications, but first google hits are not promising https://nikmav.blogspot.com/2013/03/the-perils-of-lgplv3.html (all this reading and possibly paying a lawyer...when I just wanted to go ahead and start coding :) 

What about some good ol' MIT license that allows developers to simply get to coding? :)

**Comment by rhiever** [comment]
Unfortunately a core dependency of TPOT requires LGPL, so unless we re-code TPOT to exclude that dependency, re-licensing isn't possible.
