### ISSUE TITLE
tpot.evaluated_individuals_ to pipeline

### ISSUE THREAD

**Issue by CSNoyes** [rhiever/tpot#516]
Is there a helper function to convert pipelines represented as strings into sklearn pipeline objects? This isn't in the documentation but I assume there must be.

For example, the following individual from evalued_individuals_:

`LinearSVC(PolynomialFeatures(input_matrix, PolynomialFeatures__degree=2, PolynomialFeatures__include_bias=False, PolynomialFeatures__interaction_only=False), LinearSVC__C=25.0, LinearSVC__dual=False, LinearSVC__loss=DEFAULT, LinearSVC__penalty=DEFAULT, LinearSVC__tol=0.0001)`

**Comment by weixuanfu** [comment]
For now, we do not have built-in help function to covert string to sklearn pipeline. Please check the demo below. It should be helpful for building a function for this purpose.

```python
import numpy as np
from deap import creator
from sklearn.model_selection import cross_val_score
from tpot.export_utils import generate_pipeline_code

# print part of pipeline dictionary
print(dict(list(tpot.evaluated_individuals_.items())[0:2]))
# print a pipeline and its values
pipeline_str = list(tpot.evaluated_individuals_.keys())[0]
print(pipeline_str)
print(tpot.evaluated_individuals_[pipeline_str])
for pipeline_string in sorted(tpot.evaluated_individuals_.keys()):
    # convert pipeline string to scikit-learn pipeline object
    deap_pipeline = creator.Individual.from_string(pipeline_string, tpot._pset)
    sklearn_pipeline = tpot._toolbox.compile(expr=deap_pipeline)
    # print sklearn pipeline string
    sklearn_pipeline_str = generate_pipeline_code(expr_to_tree(deap_pipeline, tpot._pset), tpot.operators)
    print(sklearn_pipeline_str)
    # Fix random state when the operator allows  (optional) just for get consistent CV score 
    tpot._set_param_recursive(sklearn_pipeline.steps, 'random_state', 42)

    try:
        cv_scores = cross_val_score(sklearn_pipeline, training_features, training_target, cv=5, scoring='accuracy', verbose=0)
        mean_cv_scores = np.mean(cv_scores)
    except Exception as e:
        print(e)
        mean_cv_scores = -float('inf')
    print(mean_cv_scores)

**Comment by weixuanfu2016** [comment]
Note: just edit some codes on the comments above because of messing up `tpot_obj` and `tpot`

**Comment by CSNoyes** [comment]
Thanks @weixuanfu2016 that works perfectly. The key line here is 
`deap_pipeline = creator.Individual.from_string(pipeline_string, tpot._pset)`

Worth noting for others that the tpot object can be an unfit object of the same model (TPOTClassifier or TPOTRegressor) used for tpot._pset.

I'll try to find some time this weekend to work on the documentation if that is something you guys would find helpful. I've discovered a lot of the functionality through trial and error, I think that there's room for improvement in that department.

**Comment by rhiever** [comment]
Feedback (and PRs) on the docs are always welcome!

**Comment by rhiever** [comment]
Closing this issue for now. Please feel free to re-open if you have any more questions or comments.

We look forward to your suggestions for improvement, especially in the docs. :-)

**Comment by pyacciITT** [comment]
When I try to utilize,  tpot._pset on unfitted TPOTClassifier (as suggested by @CSNoyes), I receive the following error

AttributeError: 'TPOTClassifier' object has no attribute '_pset'

Is there a way to get the _pset attribute without fitting?

**Comment by weixuanfu** [comment]
@pyacciITT please run `tpot._fit_init()` to get `_pset` attribute without fitting.

**Comment by pyacciITT** [comment]
Perfect - thank you @weixuanfu !

**Comment by NaelsonDouglas** [comment]
> For now, we do not have built-in help function to covert string to sklearn pipeline. Please check the demo below. It should be helpful for building a function for this purpose.
> 
> ```python
> import numpy as np
> from deap import creator
> from sklearn.model_selection import cross_val_score
> from tpot.export_utils import generate_pipeline_code
> 
> # print part of pipeline dictionary
> print(dict(list(tpot.evaluated_individuals_.items())[0:2]))
> # print a pipeline and its values
> pipeline_str = list(tpot.evaluated_individuals_.keys())[0]
> print(pipeline_str)
> print(tpot.evaluated_individuals_[pipeline_str])
> for pipeline_string in sorted(tpot.evaluated_individuals_.keys()):
>     # convert pipeline string to scikit-learn pipeline object
>     deap_pipeline = creator.Individual.from_string(pipeline_string, tpot._pset)
>     sklearn_pipeline = tpot._toolbox.compile(expr=deap_pipeline)
>     # print sklearn pipeline string
>     sklearn_pipeline_str = generate_pipeline_code(expr_to_tree(deap_pipeline, tpot._pset), tpot.operators)
>     print(sklearn_pipeline_str)
>     # Fix random state when the operator allows  (optional) just for get consistent CV score 
>     tpot._set_param_recursive(sklearn_pipeline.steps, 'random_state', 42)
> 
>     try:
>         cv_scores = cross_val_score(sklearn_pipeline, training_features, training_target, cv=5, scoring='accuracy', verbose=0)
>         mean_cv_scores = np.mean(cv_scores)
>     except Exception as e:
>         print(e)
>         mean_cv_scores = -float('inf')
>     print(mean_cv_scores)
> ```


Turning it into a function.

```python
def get_dead_pipelines(tpot:TPOTClassifier) -> Container[sklearn.pipeline.Pipeline]:
    pipelines = []
    for pipeline_string, metadata in sorted(tpot.evaluated_individuals_.items()):
        deap_pipeline = creator.Individual.from_string(pipeline_string, tpot._pset)
        sklearn_pipeline = tpot._toolbox.compile(expr=deap_pipeline)
        pipelines.append((sklearn_pipeline, metadata['internal_cv_score']))
    return pipelines
```
