### ISSUE TITLE
run tpot says missing dll

### ISSUE THREAD

**Issue by tiefan** [rhiever/tpot#517]
I followed the steps and successfully installed tpot, but i failed to run tpot. It says missing **libgomp-1.dll**

## Context of the issue
I followed the steps and successfully installed tpot, but i failed to run tpot. It says missing **libgomp-1.dll**
my os is windows 7 64, and i use python 3.5 and conda 

**Here is info from jupyter notebook when I try the iris example:**
OSError                                   Traceback (most recent call last)
<ipython-input-5-ff8c35921b3c> in <module>()
      8     iris.target.astype(np.float64), train_size=0.75, test_size=0.25)
      9 
---> 10 tpot = TPOTClassifier(generations=5, population_size=50, verbosity=2)
     11 tpot.fit(X_train, y_train)
     12 print(tpot.score(X_test, y_test))

C:\Program Files\Anaconda3\lib\site-packages\tpot\base.py in __init__(self, generations, population_size, offspring_size, mutation_rate, crossover_rate, scoring, cv, subsample, n_jobs, max_time_mins, max_eval_time_mins, random_state, config_dict, warm_start, verbosity, disable_update_check)
    226                 self.config_dict[key],
    227                 BaseClass=Operator,
--> 228                 ArgBaseClass=ARGType
    229             )
    230             if op_class:

C:\Program Files\Anaconda3\lib\site-packages\tpot\operator_utils.py in TPOTOperatorClassFactory(opsourse, opdict, BaseClass, ArgBaseClass)
    136     class_profile = {}
    137     dep_op_list = {}
--> 138     import_str, op_str, op_obj = source_decode(opsourse)
    139 
    140     if not op_obj:

C:\Program Files\Anaconda3\lib\site-packages\tpot\operator_utils.py in source_decode(sourcecode)
     68             exec('from {} import {}'.format(import_str[4:], op_str))
     69         else:
---> 70             exec('from {} import {}'.format(import_str, op_str))
     71         op_obj = eval(op_str)
     72     except ImportError:

C:\Program Files\Anaconda3\lib\site-packages\tpot\operator_utils.py in <module>()

C:\Program Files\Anaconda3\lib\site-packages\xgboost\__init__.py in <module>()
      9 import os
     10 
---> 11 from .core import DMatrix, Booster
     12 from .training import train, cv
     13 from . import rabit                   # noqa

C:\Program Files\Anaconda3\lib\site-packages\xgboost\core.py in <module>()
    110 
    111 # load the XGBoost library globally
--> 112 _LIB = _load_lib()
    113 
    114 

C:\Program Files\Anaconda3\lib\site-packages\xgboost\core.py in _load_lib()
    104     if len(lib_path) == 0:
    105         return None
--> 106     lib = ctypes.cdll.LoadLibrary(lib_path[0])
    107     lib.XGBGetLastError.restype = ctypes.c_char_p
    108     return lib

C:\Program Files\Anaconda3\lib\ctypes\__init__.py in LoadLibrary(self, name)
    423 
    424     def LoadLibrary(self, name):
--> 425         return self._dlltype(name)
    426 
    427 cdll = LibraryLoader(CDLL)

C:\Program Files\Anaconda3\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    345 
    346         if handle is None:
--> 347             self._handle = _dlopen(self._name, mode)
    348         else:
    349             self._handle = handle

OSError: [WinError 126] 找不到指定的模块。

**I try the cmdline, and got the same error info:**
C:\Users\tiefan>tpot C:\Users\tiefan\py\shebao\data\wgxx_zh2.csv -is , -target l
abel -mode classification
c:\program files\anaconda3\lib\site-packages\sklearn\cross_validation.py:44: Dep
recationWarning: This module was deprecated in version 0.18 in favor of the mode
l_selection module into which all the refactored classes and functions are moved
. Also note that the interface of the new CV iterators are different from that o
f this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):
  File "c:\program files\anaconda3\lib\runpy.py", line 184, in _run_module_as_ma
in
    "__main__", mod_spec)
  File "c:\program files\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Anaconda3\Scripts\tpot.exe\__main__.py", line 9, in <mo
dule>
  File "c:\program files\anaconda3\lib\site-packages\tpot\driver.py", line 438,
in main
    disable_update_check=args.DISABLE_UPDATE_CHECK
  File "c:\program files\anaconda3\lib\site-packages\tpot\base.py", line 228, in
 __init__
    ArgBaseClass=ARGType
  File "c:\program files\anaconda3\lib\site-packages\tpot\operator_utils.py", li
ne 138, in TPOTOperatorClassFactory
    import_str, op_str, op_obj = source_decode(opsourse)
  File "c:\program files\anaconda3\lib\site-packages\tpot\operator_utils.py", li
ne 70, in source_decode
    exec('from {} import {}'.format(import_str, op_str))
  File "<string>", line 1, in <module>
  File "c:\program files\anaconda3\lib\site-packages\xgboost\__init__.py", line
11, in <module>
    from .core import DMatrix, Booster
  File "c:\program files\anaconda3\lib\site-packages\xgboost\core.py", line 112,
 in <module>
    _LIB = _load_lib()
  File "c:\program files\anaconda3\lib\site-packages\xgboost\core.py", line 106,
 in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "c:\program files\anaconda3\lib\ctypes\__init__.py", line 425, in LoadLib
rary
    return self._dlltype(name)
  File "c:\program files\anaconda3\lib\ctypes\__init__.py", line 347, in __init_
_
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

[the remaining entries are only necessary if you are reporting a bug]

## Process to reproduce the issue

[ordered list the process to finding and recreating the issue, example below]
install tpot on win7 64bit, run the iris example

## Expected result

[describe what you would expect to have resulted from this process]

## Current result

[describe what you currently experience from this process, and thereby explain the bug]

## Possible fix

[not necessary, but suggest fixes or reasons for the bug]

## `missing dll` screenshot
I tried to upload screenshot, but something went wrong. 

The dialog box just says missing libgomp-1.dll, try reinstall to fix this problem. And i reinstalled, still not work

**Comment by weixuanfu2016** [comment]
It seems a Xgboost import error. Could you try the command `from xgboost import XGBClassifier`? I think it may reproduce the error. If so, please uninstall or reinstall xgboost. If not, please let us know which version of xgboost is in your environment.

**Comment by tiefan** [comment]
thanks a lot @weixuanfu2016 , i confirmed it is a xgboost error. after i uninstalled xgboost, everything works fine. then i reinstalled xgboost, the error still exists. my xgboost version:

C:\Users\tiefan>conda install py-xgboost
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment C:\Program Files\Anaconda3:

The following NEW packages will be INSTALLED:

    py-xgboost: 0.60-py35np112h24854b6_0

Proceed ([y]/n)? y

**Comment by weixuanfu2016** [comment]
Hmm, not sure why the conda recipe of xgboost is not working in Windows. Maybe you need install xgboost following [official installation guide](http://xgboost.readthedocs.io/en/latest/build.html)

**Comment by rhiever** [comment]
I think this is a known issue for XGBoost. It's historically been difficult to install XGBoost on Windows. I did hear recently that they plan to add better support for Windows via conda, though.

**Comment by rhiever** [comment]
Closing this issue for now. Please feel free to re-open if you have any more questions or comments.
