### ISSUE TITLE
API for report

### ISSUE THREAD

**Issue by djKooks** [rhiever/tpot#524]
Hello! Thanks for a good project first.

Instead of export py code file, is there some kind of API for returning report of Classification/Regression research result? It is good to suggest optimized code, but some one may be want to know the result as report.

This is just a suggestion. If this concept is not fit with this project, please ignore it.
Thanks!

**Comment by rhiever** [comment]
TPOT integrates directly with the scikit-learn API, so you could use a package like [scikit-plot](https://github.com/reiinakano/scikit-plot) and scikit-learn's plotting functions to generate reports of the results. I'm not sure if it's currently in the scope of TPOT to generate reports itself; even if we did develop something like that, it'd probably be best to develop it as a separate package that works with any scikit-learn estimator. (Unless, of course, you're speaking of reports about things specific to TPOT, such as the pipelines explored, etc.)

**Comment by djKooks** [comment]
@rhiever Thanks for answer! I was just think about this, but also not sure if this function is fit on this project.
