### ISSUE TITLE
[dev] OneHotEncoder bug?

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#525]
I've been using the OneHotEncoder that we ported from auto-sklearn for a separate project and keep getting an error message when using it in a pipeline.

Here's a minimal example that reproduces the issue:

```python
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_val_score, KFold
from tpot.builtins import OneHotEncoder

boston = load_boston()

clf = make_pipeline(OneHotEncoder(sparse=False, minimum_fraction=0.05), LinearRegression())
cross_val_score(clf, boston.data, boston.target, cv=KFold(n_splits=10, shuffle=True))
```

>ValueError: X has different shape than during fitting. Expected 2, got 3.

Oddly, this doesn't happen with lower `n_splits`. It's also not limited to classification problems.

Any ideas what's going on? My initial guess is that it's not resetting for each fold, i.e., it learns the transformation on one fold and tries to use the same transformation on other folds.

cc @teaearlgraycold @mfeurer

**Comment by mfeurer** [comment]
When did you port the code? I fixed an issue at some point between March and May. If the code is older than that, you may consider updating it? Also, could you please post a link? I can't find the code with the github search?

**Comment by rhiever** [comment]
[OneHotEncoder](https://github.com/rhiever/tpot/blob/development/tpot/builtins/one_hot_encoder.py)

**Comment by rhiever** [comment]
Ping... any ideas?

**Comment by teaearlgraycold** [comment]
Well I may have pulled the code some time in May.

It looks like the last change to autosklearn's OHE implementation on master is from March - https://github.com/automl/auto-sklearn/commits/master/autosklearn/pipeline/implementations/OneHotEncoder.py.

**Comment by rhiever** [comment]
Seems possible (probable?) the bug is present in both softwares, then.

**Comment by mfeurer** [comment]
That would be very unfortunate. @rhiever could you provide me a pickle/csv of the data which produces the error?

**Comment by mfeurer** [comment]
I cannot reproduce the error in Auto-sklearn. This piece of code works all fine (tried >10 times):
```
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_val_score, KFold
from autosklearn.pipeline.implementations.OneHotEncoder import OneHotEncoder

boston = load_boston()

clf = make_pipeline(OneHotEncoder(sparse=False, minimum_fraction=0.05), LinearRegression())
cross_val_score(clf, boston.data, boston.target, cv=KFold(n_splits=10, shuffle=True))
```
Does this work for you?

I'm not sure if the latest fix from March 28 would make a difference, but it seems that you guys didn't pull that. Another possibility is that you introduced a bug when refactoring the class.

**Comment by rhiever** [comment]
@teaearlgraycold, can you look into this please? Could any of the changes you made introduce this bug?

**Comment by weixuanfu** [comment]
Just have a quick look on the `OneHotEncoder` codes in TPOT. I think [_auto_select_categorical_features](https://github.com/rhiever/tpot/blob/development/tpot/builtins/one_hot_encoder.py#L45-L75) causes `ValueError: X has different shape than during fitting. Expected 2, got 3` in this issue. Because `KFold` provides different train/test indices to split data but `_auto_select_categorical_features` only uses one threshold (less than 10 unique values are considered categorical) to check categorical features, it cause the inconsistent number of categorical features among train/test indices. `OneHotEncoder` in Auto-sklearn just considers all features are categorical by default.

**Comment by teaearlgraycold** [comment]
Given that the shape from fitting is `3` and should be `2`, and the indices array looks like `[ 0,  6, 35]`, I believe the difference in shape comes from the addition of a `0` at line 333:

https://github.com/rhiever/tpot/blob/development/tpot/builtins/one_hot_encoder.py#L333

```python
n_values = np.hstack([[0], n_values])
indices = np.cumsum(n_values)
self.feature_indices_ = indices
```

Can anyone explain the addition of the `0` here?

**Comment by rhiever** [comment]
That seems to be right, @weixuanfu. I've changed the default behavior of OHE to be in-line with @mfeurer's OHE (i.e., treating all features as categorical features) until we figure out what's going on with the auto_select function.

**Comment by mfeurer** [comment]
The implementation is in line with the implementation of scikit-learn, and the categorical features need to be specified by the user. Did you find that having less than ten unique values is a good predictor of categorical features?

**Comment by rhiever** [comment]
>Did you find that having less than ten unique values is a good predictor of categorical features?

That's a rule of thumb that we've often used in the lab, but we haven't evaluated it experimentally. Usually we make that a parameter for the user.
