### ISSUE TITLE
Sparse matrix not supported because np.isnan does not work there

### ISSUE THREAD

**Issue by RensDimmendaal** [rhiever/tpot#526]
Tpot does not accept sparse matrix format (scipy.sparse.csr_matrix)  because np.isnan is not supported.

## Context of the issue

In my usage context: I use gensim to transform a text corpus to some matrix format.
When the data is large this library use the scipy scipy.sparse.csr_matrix format to store the results.
When I use this as an input in tpot I get an error because numpy's np.isnan function is not supported for this data format.

## Process to reproduce the issue

Below a minimum example to reproduce the error:

```
import scipy
from tpot import TPOTClassifier

X = scipy.sparse.csr.csr_matrix(np.array([0,0.5,0.7]))
y = scipy.sparse.csr.csr_matrix(np.array([0,1,0]))

tpot = TPOTClassifier(generations=5, population_size=50, verbosity=2)
tpot.fit(X,y)
```
## Current result

..../tpot/base.py in fit(self, features, target, sample_weight, groups)
```
    450         self._fitted_imputer = None
    451 
--> 452         if np.any(np.isnan(features)):
    453             features = self._impute_values(features)
    454 
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by weixuanfu2016** [comment]
The current version (0.8.3) of TPOT do not supported sparse matrix as input array and `np.isnan` is for 
imputation function in TPOT. In the future version of TPOT, we may add the support for sparse matrix since one hot encoder supports sparse matrix (related PR #462 has been merged under dev branch)

For now, please try to use `X.toarray()` to convert to a dense numpy array.

**Comment by RensDimmendaal** [comment]
Thanks. Appreciate the background info.

**Comment by lesshaste** [comment]
Support for sparse matrices would be great!
