### ISSUE TITLE
Can't fit multilabel?

### ISSUE THREAD

**Issue by DBCerigo** [rhiever/tpot#529]
I'm struggling to fit for a multilabel problem - getting response that I'm feeding invalid data into scikitlean; "target labels must be a 1-D array".

I tried wrapping TPOT with scikit's One-Rest classified i.e.
`OneVsRestClassifier(TPOTClassifier(...)).fit...`
but still struggling.

Is this the correct way of using TPOT with mutlilabel problems or am I missing something?

Thanks

**Comment by rhiever** [comment]
TPOT doesn't currently support multi-label classification problems, only multi-class problems. TPOT performs a check at the beginning of a run that includes a check to ensure that the labels are a 1-D array, which is likely why you're receiving the error you quoted.

This question is related to #196.

**Comment by weixuanfu** [comment]
Closing this issue for now. Please feel free to re-open if you have any more questions or comments.
