### ISSUE TITLE
Feature Selection scoring using `f_classif` in both `regressor.py` and `regressor_light.py`

### ISSUE THREAD

**Issue by dclambert** [rhiever/tpot#536]
## Context of the issue

The standard and light configs for regression use `sklearn.feature_selection.f_classif` as the score function for both `SelectPercentile` and `SelectFwe` rather than `sklearn.feature_selection.f_regression`.  

Is this intentional?

**Comment by weixuanfu** [comment]
Hmm, I think it is a bug. I will submit a PR for fixing it.

**Comment by weixuanfu** [comment]
@dclambert Thank you for reporting this issue.

I just posted a PR #538 for it and it is based on dev branch. You may try the commands below to reinstall TPOT with the patch

```
pip install --upgrade --no-deps --force-reinstall git+https://github.com/weixuanfu/tpot.git@f_regression
```

Also I made another branch with the patch based on Master branch (I did not post PR for it for avoiding conflicts). Try the commands below for installing the branch. 

```
pip install --upgrade --no-deps --force-reinstall git+https://github.com/weixuanfu/tpot.git@f_regression_patch
```
