### ISSUE TITLE
tpot.fit() error

### ISSUE THREAD

**Issue by Valdi** [rhiever/tpot#537]
I am trying to use tpot for the first time, but I have been getting the following error which has to do with fit() function

'list' object has no attribute 'astype'

the data I am using I import it from matlab and save it in numpy array.

**Comment by weixuanfu** [comment]
Could you please provide more details about this issue, like detail stderr or codes for reproducing the issue?

**Comment by Valdi** [comment]
![capture](https://user-images.githubusercontent.com/1936480/28626507-70eaa49e-721f-11e7-9914-4d99029e520d.JPG)

This is the error I am getting

I am trying to run tpot using jupyter

**Comment by weixuanfu** [comment]
It seem that `input_nn` is a list instead a numpy array based on the error message. Could you please print out `type(input_nn)` for checking the type of `input_nn`?

**Comment by Valdi** [comment]
Thanks! it was actually a list and I have just converted to numpy array, however I am now getting the following error

![image](https://user-images.githubusercontent.com/1936480/28629395-94d85588-7227-11e7-8f9d-3699aaf4790c.png)

I am getting the following error now, which has to do with the shape of my data. 

my input data is definitely 2D array with each column being an example, while my output data is also a 2D array with each column being a label. How should format my data?

**Comment by weixuanfu** [comment]
I think maybe `outputnn` is not a 1-D array. Could please change the shape of `outputnn`?

**Comment by Valdi** [comment]
It's definitely not a 1D array, because this is how I stored my data in matlab and now I have no idea how to format it to work for tpot.

I basically have a 2D array as an input in which each column corresponds to an example and another 2D array as the output with each column corresponding to a label for the corresponding data in the input array.

so outputnn[:,1] corresponds to input[:,1]

This is my output in matlab:
![image](https://user-images.githubusercontent.com/1936480/28630474-9f961d22-722a-11e7-8a7e-5f2fa62f2657.png)

and this is my input:

![image](https://user-images.githubusercontent.com/1936480/28630498-b0ca0086-722a-11e7-9e26-0c1e3c23a47d.png)


and each column is an example/label

**Comment by weixuanfu** [comment]
Is this a multilabel problem as mentioned in #529?

If not, I suggest to use one label out of output to each `tpot.fit()`.  You just need select one column out of output as `y` in fit().

**Comment by Valdi** [comment]
No its not a multi label problem. So I need to feed one set of examples and their corresponding class? because I have 19 classes in my problem, I need to do this for each set of examples? I am not quite sure how this works

**Comment by weixuanfu** [comment]
Oh, sorry for the misunderstanding before. I think you need to reformat the output table to 1-D array, like nameing these classes as 1-19 in the array.

**Comment by weixuanfu** [comment]
Closing this issue for now. Please feel free to re-open if you have any more questions or comments.
