### ISSUE TITLE
Using predefined X_train/y_train in TPOT command line

### ISSUE THREAD

**Issue by lperozzi** [rhiever/tpot#548]
Thanks for this beautiful tool. 
From the documentation I see that the input are the dataset and the column name of the target variable, however I wonder if there are a way to give `X_train`, `y_train`, `X_test` and `y_test` as input, since my train/test split is not done using `train_test_split`?

**Comment by weixuanfu** [comment]
Sorry, the current CLI mode in TPOT do not have this option. You may need write python scripts for this purpose.
