### ISSUE TITLE
Pickling TPOT objects

### ISSUE THREAD

**Issue by QCaudron** [rhiever/tpot#65]
I wonder if there'd be any interest in generating something to pickle TPOT pipelines. Aside from the immediate use-case of "I want to import my pipeline and work with it more easily than with the `.export()`-generated .py file", it'd also help immensely in parallelising pipeline search, say if I wanted to find several different pipelines simultaneously and compare their scores afterwards. Admittedly, I haven't looked into the structure of TPOT pipelines, so I'm not sure how complex they are. Is this completely nontrivial ?

**Comment by rhiever** [comment]
There's definitely interest. I've discussed pickling TPOT pipelines with @rasbt in #2 if you'd like to join the conversation there.

**Comment by QCaudron** [comment]
Thanks ! Apologies, I hadn't seen that that discussion encompassed pickling. I'll close up over here.
