### ISSUE TITLE
Add verbosity parameter

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#7]
Allow the user to tune the level of output from TPOT. Default to no output.

**Comment by MichaelMarkieta** [comment]
I'm not seeing any output in python3 when running `fit` for any verbosity level. What is one of the first things TPOT is supposed to report, and how soon after starting `fit` should that happen?

**Comment by MichaelMarkieta** [comment]
Looks like there is very little in the way of print statements... only at the end of the `fit` routine do we learn the best pipeline. I thought there would be more along the way. Hmm.

**Comment by rhiever** [comment]
With maximum verbosity (=2), it should also report the best/worst/average scores every generation. Depending on your data size, each generation may take a while.

We've been thinking about ways to provide an update on the best model every generation in #2. What information are you looking for while TPOT is running?

**Comment by MichaelMarkieta** [comment]
I got greedy... the dataset was too large and I didn't wait long enough for the first gen (0) to get reported. Working as expected. Carry on...

**Comment by rhiever** [comment]
It would probably help if we added an "Expectations" section explaining that TPOT will be rather slow for large data sets. Although in #59 we're exploring ideas on speeding the initial seeding phase up to get the user *something* useful right off the bat.

**Comment by MichaelMarkieta** [comment]
Could also print some stuff out right off the bat to tell the user things have been initialized. The fit statement is lonely waiting for gen 0 to finish.

**Comment by rhiever** [comment]
True enough. We do this for the command-line version, so it seems reasonable to do it for the scripted version as well. Filed as issue #74.
