### ISSUE TITLE
Allow regular checkpointing

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#79]
As suggested in #2, allow TPOT to regularly checkpoint (say, every generation at most) and save its state over time. A checkpoint file would allow contain all of the information necessary for another TPOT instance to pick up where the last one left off:
- All settings
- The current population
- The current hall of fame

**Comment by manugarri** [comment]
Is there any update on this? I would be willing to contribute (this seems like an easy implementation), if you gave me some pointer to where to look at in the code and the discussed approaches.

**Comment by rhiever** [comment]
That's great, @manugarri! We haven't made any progress on this yet. At a high level, we would want to make it so the user can stop and restart TPOT at any point during the optimization process. This would mostly entail editing [base.py](https://github.com/rhiever/tpot/blob/master/tpot/base.py) in the `fit()` function to store the current state every generation of the optimization process.

**Comment by manugarri** [comment]
got it, basically [here](https://github.com/rhiever/tpot/blob/master/tpot/base.py#L335), isnt it? Il ltake a look :)

**Comment by rhiever** [comment]
That bit of code is where we catch user interrupts and close TPOT gracefully. This checkpointing process would need to be inserted into the evolutionary algorithm itself.

I'd imagine we could do something similar to how we update TPOT's progress bar at the end of every generation. We can create a [decorator](https://github.com/rhiever/tpot/blob/21aad37930e2bc3cc40822abdeac5efaa1e809ce/tpot/base.py#L184) over the selection function, which can [checkpoint the current generation](https://github.com/rhiever/tpot/blob/master/tpot/decorators.py#L26) at the end of every optimization cycle.

**Comment by rhiever** [comment]
Checkpointing of the best pipeline from every generation has been added to the dev branch and will be included in the next release.

**Comment by manugarri** [comment]
Neat! Looking forward to it

**Comment by saddy001** [comment]
It's been released. I think the ticket can be closed.

**Comment by weixuanfu** [comment]
@saddy001 yep, thank you for finding it.
