### ISSUE TITLE
[Major refactor] Incorporate OO redesign

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#91]
See #63 for an example of the new OO design on an old version of TPOT. This will require a large overhaul of TPOT.

**Comment by rhiever** [comment]
@tonyfast: I just remembered that we have this issue open to discuss the major refactor coming up after the 0.4 release.

@teaearlgraycold, please link your WIP refactor here so we can take a look at it.

**Comment by teaearlgraycold** [comment]
**Don't try to run this code - atm it's just a structural layout**

https://github.com/teaearlgraycold/tpot/tree/refactor

**Comment by teaearlgraycold** [comment]
So with this setup if you want to do something like refactor TPOT so it just uses Numpy matrices you can edit the Operator class, Classifer class, and PreProcessor class and leave all actually classifiers and preprocessors untouched.

**Comment by tonyfast** [comment]
I started looking into a refactor myself to understand the project a little bit more.  I haven't put this into scripts yet, but the idea in [drawn out in the notebook](https://anaconda.org/tonyfast/untitled154/notebook).

There were a few main opinions for this to study.

* `training` and `testing`  classes information are contained in a Pandas DataFrame multiindex.
* Make a custom ` BaseEstimator` that has a `fit_predict` classmethod.  This method fits the model with the training then applies a `transform`, `predict`, or `selection/support` operation.
* New models are created by subclassing an existing `sklearn` model with some defaults.

With a limited corpus of models so far this gets all the way through.  There is a problem with the scoring function at the moment.

Are there are reasons not to use a direct `sklearn` models as subclasses?  The [`BaseEstimator`](http://scikit-learn.org/stable/modules/generated/sklearn.base.BaseEstimator.html#sklearn.base.BaseEstimator) provides method for `get_params` and `set_params` which [may help here](https://github.com/teaearlgraycold/tpot/blob/refactor/tpot/operators/base.py#L48).

**Comment by teaearlgraycold** [comment]
@tonyfast I pushed out a commit so your line number is off. You were referring to the _apply_default_params() method though, correct?

That method is largely there so that certain parameters can be blindly applied to all estimators (regardless of whether they're applicable), and behaves differently than set_params.
