### ISSUE TITLE
Revisit TPOT GP defaults

### ISSUE THREAD

**Issue by rhiever** [rhiever/tpot#93]
The TPOT GP defaults (mutation rate, crossover rate, population size) were previously chosen based on benchmarks on an earlier version of TPOT that included only a few pipeline operators. TPOT has grown tremendously since then, and we should revisit the defaults to see if:

* Is a high-mutation-rate, low-crossover-rate scheme still better? Look at `5% XR / 90% MR`, `90% XR / 5% MR`, and `50% XR / 50% MR`

* Is a population size of 100 sufficient? Look at population sizes of 10, 50, 100, 250, 500, and 1000 with a fixed XR/MR scheme.

**Comment by pronojitsaha** [comment]
OK...will look into this.

**Comment by rhiever** [comment]
Ping. How's this coming along? Should I mark it as "being worked on"? This job will require quite a lot of TPOT runs, so I may take this one on myself because I have access to a HPCC.

**Comment by pronojitsaha** [comment]
I dint start on this one. Ok, please go ahead.
